---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    PaymentEvent:
      type: "object"
      properties:
        payment_event_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value for the referenc... Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
          exampleSetFlag: false
        payment_event_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique key value for the reference recor... Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
          exampleSetFlag: false
        payment_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "The unique key identifying the reference... Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the reference."
          exampleSetFlag: false
        old_payment_status_type:
          $ref: "#/components/schemas/PaymentStatusTypes"
          exampleSetFlag: false
        new_payment_status_type:
          $ref: "#/components/schemas/PaymentStatusTypes"
          exampleSetFlag: false
        payment_transaction_id:
          type: "string"
          description: "Optional: The specific transaction ID ca..."
          exampleSetFlag: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the paymentMethod was ..."
          format: "date-time"
          exampleSetFlag: false
      description: "Reference to a PaymentMethod (Party) Aggregate Root for financing\
        \ details."
      exampleSetFlag: false
    PaymentEventCreate:
      required:
      - "payment_event_key"
      type: "object"
      description: "PaymentEvent Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/PaymentEvent"
        exampleSetFlag: false
    PaymentEventUpdate:
      type: "object"
      properties:
        new_payment_status_type:
          $ref: "#/components/schemas/PaymentStatusTypes"
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the reference."
          exampleSetFlag: false
        old_payment_status_type:
          $ref: "#/components/schemas/PaymentStatusTypes"
          exampleSetFlag: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the paymentMethod was ..."
          format: "date-time"
          exampleSetFlag: false
      description: "PaymentEvent Update for Patch and Put"
      exampleSetFlag: false
    PaymentStatusTypes:
      type: "string"
      description: "types of payment status."
      exampleSetFlag: false
      enum:
      - "CREATED"
      - "PENDING"
      - "PROCESSING"
      - "PROCESSED"
      - "COMPLETED"
      - "SUCCEEDED"
      - "PAID"
      - "REJECTED"
      - "SCHEDULED"
      - "SUBMITTED"
      - "DEFERRED"
      - "DEFERRED_INTERNAL"
      - "CLEARED"
      - "FRAUD_REVIEW"
      - "APPROVED"
      - "ACCEPTED"
      - "REQUIRES_ACTION"
      - "REQUIRES_PAYMENT_STATUS"
      - "AUTO_SCHEDULED"
      - "AUTO_INITIATED"
      - "MANUAL_INITIATED"
      - "PENDING_PAYER_FUNDS"
      - "FAILED"
      - "DENIED"
      - "EXPIRED"
      - "CANCELLED"
      - "VOIDED"
      - "REVERSED"
      - "REFUNDED"
      - "PAYROLL_PENDING"
      - "PAYROLL_FINALIZED"
      - "ACTIVE"
      - "INACTIVE"
      - "FUNDED"
      - "RETURNED"
