---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    Codes:
      type: "array"
      description: "List of Codes"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    Link:
      type: "array"
      description: "Quick Link"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    Links:
      type: "array"
      description: "List of Links"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    PaymentEvent:
      type: "object"
      properties:
        payment_event_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value for the reference record. Pattern:\
            \ ^[a-zA-Z0-9_]+$ (Alphanumeric and underscores allowed)"
          nullable: false
          exampleSetFlag: false
        payment_event_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique key value for the reference record. Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
          nullable: false
          exampleSetFlag: false
        payment_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "The unique key identifying the referenced PaymentMethod (Party)\
            \ aggregate. Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric and underscores allowed)"
          nullable: false
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the reference."
          nullable: true
          exampleSetFlag: false
        old_payment_status_type:
          description: "Type of payment method used for the transaction (e.g., CREDIT_CARD,\
            \ ACH)."
          $ref: "#/components/schemas/PaymentStatusTypes"
          nullable: false
          example: "CREDIT_CARD"
          exampleSetFlag: true
        new_payment_status_type:
          description: "Type of payment method used for the transaction (e.g., CREDIT_CARD,\
            \ ACH)."
          $ref: "#/components/schemas/PaymentStatusTypes"
          nullable: false
          example: "CREDIT_CARD"
          exampleSetFlag: true
        payment_transaction_id:
          type: "string"
          description: "Optional: The specific transaction ID causing the status change."
          nullable: true
          exampleSetFlag: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the paymentMethod was associated with the\
            \ order."
          format: "date-time"
          nullable: false
          exampleSetFlag: false
      description: "Reference to a PaymentMethod (Party) Aggregate Root for financing\
        \ details."
      exampleSetFlag: false
    PaymentStatusTypes:
      type: "string"
      description: "types of payment status."
      extensions:
        x-governance:
          REQUIRES_ACTION:
            sortIndex: 0
            description: "Payment status: Requires action."
            is_unique: true
            depreciated: false
            published: false
            id: 16
          ACTIVE:
            sortIndex: 0
            description: "Payment status: Active."
            is_unique: true
            depreciated: false
            published: false
            id: 31
          REQUIRES_PAYMENT_STATUS:
            sortIndex: 0
            description: "Payment status: Requires a specific status."
            is_unique: true
            depreciated: false
            published: false
            id: 17
          PROCESSING:
            sortIndex: 0
            description: "Payment status: Processing."
            is_unique: true
            depreciated: false
            published: false
            id: 2
          EXPIRED:
            sortIndex: 0
            description: "Payment status: Expired."
            is_unique: true
            depreciated: false
            published: false
            id: 24
          AUTO_INITIATED:
            sortIndex: 0
            description: "Payment status: Auto-initiated."
            is_unique: true
            depreciated: false
            published: false
            id: 19
          SCHEDULED:
            sortIndex: 0
            description: "payment.status.types.scheduled.desc"
            is_unique: true
            depreciated: false
            published: false
            id: 8
          AUTO_SCHEDULED:
            sortIndex: 0
            description: "Payment status: Auto-scheduled."
            is_unique: true
            depreciated: false
            published: false
            id: 18
          PAYROLL_PENDING:
            sortIndex: 0
            description: "Payroll Pending"
            is_unique: true
            depreciated: false
            published: false
            id: 29
          VOIDED:
            sortIndex: 0
            description: "Payment status: Voided."
            is_unique: true
            depreciated: false
            published: false
            id: 26
          CLEARED:
            sortIndex: 0
            description: "payment.status.types.cleared.desc"
            is_unique: true
            depreciated: false
            published: false
            id: 12
          CREATED:
            sortIndex: 0
            description: "Payment status: Created."
            is_unique: true
            depreciated: false
            published: false
            id: 0
          COMPLETED:
            sortIndex: 0
            description: "Payment status: Completed."
            is_unique: true
            depreciated: false
            published: false
            id: 4
          ACCEPTED:
            sortIndex: 0
            description: "Payment status: Accepted."
            is_unique: true
            depreciated: false
            published: false
            id: 15
          FAILED:
            sortIndex: 0
            description: "Payment status: Failed."
            is_unique: true
            depreciated: false
            published: false
            id: 22
          RETURNED:
            sortIndex: 0
            description: "Returned"
            is_unique: true
            depreciated: false
            published: false
            id: 34
          DEFERRED_INTERNAL:
            sortIndex: 0
            description: "payment.status.types.deferred_internal.desc"
            is_unique: true
            depreciated: false
            published: false
            id: 11
          DEFERRED:
            sortIndex: 0
            description: "payment.status.types.deferred.desc"
            is_unique: true
            depreciated: false
            published: false
            id: 10
          REJECTED:
            sortIndex: 0
            description: "payment.status.types.rejected.desc"
            is_unique: true
            depreciated: false
            published: false
            id: 7
          DENIED:
            sortIndex: 0
            description: "Payment status: Denied."
            is_unique: true
            depreciated: false
            published: false
            id: 23
          FUNDED:
            sortIndex: 0
            description: "Funded"
            is_unique: true
            depreciated: false
            published: false
            id: 33
          REVERSED:
            sortIndex: 0
            description: "Payment status: Reversed."
            is_unique: true
            depreciated: false
            published: false
            id: 27
          REFUNDED:
            sortIndex: 0
            description: "Payment status: Refunded."
            is_unique: true
            depreciated: false
            published: false
            id: 28
          FRAUD_REVIEW:
            sortIndex: 0
            description: "payment.status.types.fraud_review.desc"
            is_unique: true
            depreciated: false
            published: false
            id: 13
          PAID:
            sortIndex: 0
            description: "payment.status.types.paid.desc"
            is_unique: true
            depreciated: false
            published: false
            id: 6
          PENDING:
            sortIndex: 0
            description: "Payment status: Pending."
            is_unique: true
            depreciated: false
            published: false
            id: 1
          CANCELLED:
            sortIndex: 0
            description: "Payment status: Cancelled."
            is_unique: true
            depreciated: false
            published: false
            id: 25
          PENDING_PAYER_FUNDS:
            sortIndex: 0
            description: "payment.status.types.pending_payer_funds.desc"
            is_unique: true
            depreciated: false
            published: false
            id: 21
          INACTIVE:
            sortIndex: 0
            description: "Payment status: Inactive."
            is_unique: true
            depreciated: false
            published: false
            id: 32
          SUCCEEDED:
            sortIndex: 0
            description: "Payment status: Succeeded."
            is_unique: true
            depreciated: false
            published: false
            id: 5
          PROCESSED:
            sortIndex: 0
            description: "Payment status: Processed."
            is_unique: true
            depreciated: false
            published: false
            id: 3
          SUBMITTED:
            sortIndex: 0
            description: "payment.status.types.submitted.desc"
            is_unique: true
            depreciated: false
            published: false
            id: 9
          APPROVED:
            sortIndex: 0
            description: "Payment status: Approved."
            is_unique: true
            depreciated: false
            published: false
            id: 14
          MANUAL_INITIATED:
            sortIndex: 0
            description: "Payment status: Manually initiated."
            is_unique: true
            depreciated: false
            published: false
            id: 20
          PAYROLL_FINALIZED:
            sortIndex: 0
            description: "Payroll Finalized"
            is_unique: true
            depreciated: false
            published: false
            id: 30
      exampleSetFlag: false
      enum:
      - "CREATED"
      - "PENDING"
      - "PROCESSING"
      - "PROCESSED"
      - "COMPLETED"
      - "SUCCEEDED"
      - "PAID"
      - "REJECTED"
      - "SCHEDULED"
      - "SUBMITTED"
      - "DEFERRED"
      - "DEFERRED_INTERNAL"
      - "CLEARED"
      - "FRAUD_REVIEW"
      - "APPROVED"
      - "ACCEPTED"
      - "REQUIRES_ACTION"
      - "REQUIRES_PAYMENT_STATUS"
      - "AUTO_SCHEDULED"
      - "AUTO_INITIATED"
      - "MANUAL_INITIATED"
      - "PENDING_PAYER_FUNDS"
      - "FAILED"
      - "DENIED"
      - "EXPIRED"
      - "CANCELLED"
      - "VOIDED"
      - "REVERSED"
      - "REFUNDED"
      - "PAYROLL_PENDING"
      - "PAYROLL_FINALIZED"
      - "ACTIVE"
      - "INACTIVE"
      - "FUNDED"
      - "RETURNED"
