---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    Codes:
      type: "array"
      description: "List of Codes"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    EventTypes:
      type: "string"
      description: "types of events."
      exampleSetFlag: false
      enum:
      - "INVOICE_RECEIVED"
      - "ITEM_SHIPPED"
    Identifier:
      type: "object"
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          nullable: false
          exampleSetFlag: false
        identifier_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Business key for the identifier Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          nullable: false
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          nullable: true
          exampleSetFlag: false
        value:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
          exampleSetFlag: false
        detail:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
          exampleSetFlag: false
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
          exampleSetFlag: false
        system_codes:
          description: "Associated system codes for this identifier"
          $ref: "#/components/schemas/Codes"
          nullable: true
          exampleSetFlag: false
      description: "External system identifier"
      exampleSetFlag: false
    IdentifierCreate:
      required:
      - "identifier_key"
      type: "object"
      description: "Identifier Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/Identifier"
        exampleSetFlag: false
    IdentifierUpdate:
      type: "object"
      properties:
        system_codes:
          description: "Associated system codes for this identifier"
          $ref: "#/components/schemas/Codes"
          nullable: true
          exampleSetFlag: false
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          nullable: true
          exampleSetFlag: false
        detail:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
          exampleSetFlag: false
        value:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
          exampleSetFlag: false
      description: "Identifier Update for Patch and Put"
      exampleSetFlag: false
    Link:
      type: "array"
      description: "Quick Link"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    Links:
      type: "array"
      description: "List of Links"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    NotificationReference:
      type: "object"
      properties:
        notification_reference_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value for the reference record. Pattern:\
            \ ^[a-zA-Z0-9_]+$ (Alphanumeric and underscores allowed)"
          nullable: false
          exampleSetFlag: false
        notification_reference_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique key value for the reference record. Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
          nullable: false
          exampleSetFlag: false
        source_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "The unique key identifying the referenced PartOrder aggregate.\
            \ Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric and underscores allowed)"
          nullable: false
          exampleSetFlag: false
        source_actor:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "The unique key identifying the referenced PartOrder aggregate.\
            \ Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric and underscores allowed)"
          nullable: false
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier (e.g., 'CRM', 'ERP')."
          nullable: true
          exampleSetFlag: false
        system_codes:
          description: "Associated system codes for this identifier"
          $ref: "#/components/schemas/Codes"
          nullable: true
          exampleSetFlag: false
        identifier:
          description: "Details of the PartOrder reference, potentially including\
            \ an external PartOrder number."
          $ref: "#/components/schemas/Identifier"
          nullable: false
          exampleSetFlag: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the reference was created or last updated."
          format: "date-time"
          nullable: false
          exampleSetFlag: false
        event_type:
          description: "The date and time the reference was created or last updated."
          $ref: "#/components/schemas/EventTypes"
          nullable: false
          exampleSetFlag: false
      description: "Reference to a PartOrder Aggregate Root, often used by external\
        \ systems."
      exampleSetFlag: false
    NotificationReferenceCreate:
      required:
      - "notification_reference_key"
      type: "object"
      description: "NotificationReference Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/NotificationReference"
        exampleSetFlag: false
    NotificationReferenceUpdate:
      type: "object"
      properties:
        system_codes:
          description: "Associated system codes for this identifier"
          $ref: "#/components/schemas/Codes"
          nullable: true
          exampleSetFlag: false
        identifier:
          description: "Details of the PartOrder reference, potentially including\
            \ an external PartOrder number."
          $ref: "#/components/schemas/Identifier"
          nullable: false
          exampleSetFlag: false
        event_type:
          description: "The date and time the reference was created or last updated."
          $ref: "#/components/schemas/EventTypes"
          nullable: false
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier (e.g., 'CRM', 'ERP')."
          nullable: true
          exampleSetFlag: false
        source_actor:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "The unique key identifying the referenced PartOrder aggregate.\
            \ Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric and underscores allowed)"
          nullable: false
          exampleSetFlag: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the reference was created or last updated."
          format: "date-time"
          nullable: false
          exampleSetFlag: false
      description: "NotificationReference Update for Patch and Put"
      exampleSetFlag: false
