---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths:
  /notification-references:
    get:
      tags:
      - "NotificationReference"
      summary: "Retrieve a list of all NotificationReference records."
      operationId: "listNotificationReferences"
      parameters:
      - name: "limit"
        in: "query"
        description: "Maximum number of records to return."
        schema:
          maximum: 100
          minimum: 1
          type: "integer"
          
          default: 50
      - name: "cursor"
        in: "query"
        description: "starting point for next set of results"
        schema:
          type: "string"
          
      responses:
        "200":
          description: "A list of NotificationReference records."
          content:
            application/json:
              schema:
                type: "array"
                
                items:
                  $ref: "#/components/schemas/NotificationReference"
                  
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"
    post:
      tags:
      - "NotificationReference"
      summary: "Create a new NotificationReference record."
      operationId: "createNotificationReference"
      requestBody:
        description: "NotificationReference data to create the new resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NotificationReference_Create"
              
        required: true
      responses:
        "201":
          description: "NotificationReference created successfully."
          headers:
            Location:
              description: "The URI of the newly created resource."
              schema:
                type: "string"
                example: "//notification-references/PR-1234567"

          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotificationReference"
                
        "400":
          $ref: "#/components/responses/BadRequestError"
        "409":
          $ref: "#/components/responses/ConflictError"
  /notification-references/{notificationReferenceKey}:
    get:
      tags:
      - "NotificationReference"
      summary: "Retrieve a specific NotificationReference record."
      operationId: "getNotificationReferenceById"
      responses:
        "200":
          description: "The requested NotificationReference record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotificationReference"
                
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    put:
      tags:
      - "NotificationReference"
      summary: "replace a NotificationReference record."
      operationId: "replaceNotificationReference"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NotificationReference"
              
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotificationReference"
                
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    delete:
      tags:
      - "NotificationReference"
      summary: "Delete a NotificationReference Record"
      description: "Marks the NotificationReference record as inactive or removes\
        \ it entirely."
      operationId: "deleteNotificationReferenceRecord"
      responses:
        "204":
          description: "Record successfully deleted (or deactivated)."
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    patch:
      tags:
      - "NotificationReference"
      summary: "Partially update a NotificationReference record."
      operationId: "updateNotificationReference"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NotificationReference_Update"
              
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotificationReference"
                
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    parameters:
    - name: "notificationReferenceKey"
      in: "path"
      description: "The unique identifier for the specific NotificationReference."
      required: true
      schema:
        type: "string"
        example: "PR-1234567"
        exampleSetFlag: true
  /notification-references/{notificationReferenceKey}/identifiers:
    get:
      tags:
      - "Identifier"
      summary: "Retrieve a list of all Identifier records."
      operationId: "listIdentifiers"
      parameters:
      - name: "limit"
        in: "query"
        description: "Maximum number of records to return."
        schema:
          maximum: 100
          minimum: 1
          type: "integer"
          
          default: 50
      - name: "cursor"
        in: "query"
        description: "starting point for next set of results"
        schema:
          type: "string"
          
      responses:
        "200":
          description: "A list of Identifier records."
          content:
            application/json:
              schema:
                type: "array"
                
                items:
                  $ref: "#/components/schemas/Identifier"
                  
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"
    post:
      tags:
      - "Identifier"
      summary: "Create a new Identifier record."
      operationId: "createIdentifier"
      requestBody:
        description: "Identifier data to create the new resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Identifier_Create"
              
        required: true
      responses:
        "201":
          description: "Identifier created successfully."
          headers:
            Location:
              description: "The URI of the newly created resource."
              schema:
                type: "string"
                example: "//notification-references/{notificationReferenceKey}/identifiers/PR-1234567"

          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identifier"
                
        "400":
          $ref: "#/components/responses/BadRequestError"
        "409":
          $ref: "#/components/responses/ConflictError"
  /notification-references/{notificationReferenceKey}/identifiers/{identifierKey}:
    get:
      tags:
      - "Identifier"
      summary: "Retrieve a specific Identifier record."
      operationId: "getIdentifierById"
      responses:
        "200":
          description: "The requested Identifier record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identifier"
                
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    put:
      tags:
      - "Identifier"
      summary: "replace a Identifier record."
      operationId: "replaceIdentifier"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Identifier"
              
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identifier"
                
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    delete:
      tags:
      - "Identifier"
      summary: "Delete a Identifier Record"
      description: "Marks the Identifier record as inactive or removes it entirely."
      operationId: "deleteIdentifierRecord"
      responses:
        "204":
          description: "Record successfully deleted (or deactivated)."
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    patch:
      tags:
      - "Identifier"
      summary: "Partially update a Identifier record."
      operationId: "updateIdentifier"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Identifier_Update"
              
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identifier"
                
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    parameters:
    - name: "identifierKey"
      in: "path"
      description: "The unique identifier for the specific Identifier."
      required: true
      schema:
        type: "string"
        example: "PR-1234567"
        exampleSetFlag: true
components:
  schemas: {}
