---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths:
  /notification-references:
    get:
      tags:
      - "NotificationReference"
      summary: "Retrieve a list of all NotificationReference re..."
      operationId: "listNotificationReferences"
      parameters:
      - name: "limit"
        in: "query"
        description: "Maximum number of records to return."
        schema:
          maximum: 100
          minimum: 1
          type: "integer"
          exampleSetFlag: false
          default: 50
      - name: "cursor"
        in: "query"
        description: "starting point for next set of results"
        schema:
          type: "string"
          exampleSetFlag: false
      responses:
        "200":
          description: "A list of NotificationReference records."
          content:
            application/json:
              schema:
                type: "array"
                exampleSetFlag: false
                items:
                  $ref: "#/components/schemas/NotificationReference"
                  exampleSetFlag: false
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"
    post:
      tags:
      - "NotificationReference"
      summary: "Create a new NotificationReference record."
      operationId: "createNotificationReference"
      requestBody:
        description: "NotificationReference data to create the new re..."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NotificationReferenceCreate"
              exampleSetFlag: false
        required: true
      responses:
        "201":
          description: "NotificationReference created successfully."
          headers:
            Location:
              description: "The URI of the newly created resource."
              schema:
                type: "string"
                example: "/notification-references/PR-1234567"
                exampleSetFlag: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotificationReference"
                exampleSetFlag: false
        "400":
          $ref: "#/components/responses/BadRequestError"
        "409":
          $ref: "#/components/responses/ConflictError"
  /notification-references/{notificationReferenceKey}:
    get:
      tags:
      - "NotificationReference"
      summary: "Retrieve a specific NotificationReference record."
      operationId: "getNotificationReferenceById"
      responses:
        "200":
          description: "The requested NotificationReference record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotificationReference"
                exampleSetFlag: false
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    put:
      tags:
      - "NotificationReference"
      summary: "Replace a NotificationReference record."
      operationId: "replaceNotificationReference"
      requestBody:
        description: "Full record data to replace the existing resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NotificationReference"
              exampleSetFlag: false
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the update..."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotificationReference"
                exampleSetFlag: false
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    delete:
      tags:
      - "NotificationReference"
      summary: "Delete a NotificationReference Record"
      description: "Marks the NotificationReference record as inact..."
      operationId: "deleteNotificationReferenceRecord"
      responses:
        "204":
          description: "Record successfully deleted (or deactivated)."
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    patch:
      tags:
      - "NotificationReference"
      summary: "Partially update a NotificationReference record."
      operationId: "updateNotificationReference"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NotificationReferenceUpdate"
              exampleSetFlag: false
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the update..."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotificationReference"
                exampleSetFlag: false
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    parameters:
    - name: "notificationReferenceKey"
      in: "path"
      description: "The unique identifier for the specific NotificationReference."
      required: true
      schema:
        type: "string"
        example: "PR-1234567"
        exampleSetFlag: true
  /notification-references/{notificationReferenceKey}/identifiers:
    get:
      tags:
      - "Identifier"
      summary: "Retrieve a list of Identifier records scoped by..."
      operationId: "listIdentifiersByNotificationReferenceKey"
      parameters:
      - name: "limit"
        in: "query"
        description: "Maximum number of records to return."
        schema:
          maximum: 100
          minimum: 1
          type: "integer"
          exampleSetFlag: false
          default: 50
      - name: "cursor"
        in: "query"
        description: "starting point for next set of results"
        schema:
          type: "string"
          exampleSetFlag: false
      responses:
        "200":
          description: "A list of Identifier records."
          content:
            application/json:
              schema:
                type: "array"
                exampleSetFlag: false
                items:
                  $ref: "#/components/schemas/Identifier"
                  exampleSetFlag: false
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"
    post:
      tags:
      - "Identifier"
      summary: "Create a new Identifier record."
      operationId: "createIdentifier"
      requestBody:
        description: "Identifier data to create the new resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IdentifierCreate"
              exampleSetFlag: false
        required: true
      responses:
        "201":
          description: "Identifier created successfully."
          headers:
            Location:
              description: "The URI of the newly created resource."
              schema:
                type: "string"
                example: "/part-search-results/PS-12345/bill-of-materials/BOM-001"
                exampleSetFlag: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identifier"
                exampleSetFlag: false
        "400":
          $ref: "#/components/responses/BadRequestError"
        "409":
          $ref: "#/components/responses/ConflictError"
    parameters:
    - name: "notificationReferenceKey"
      in: "path"
      description: "The unique identifier for the parent resource."
      required: true
      schema:
        type: "string"
        exampleSetFlag: false
  /notification-references/{notificationReferenceKey}/identifiers/{identifierKey}:
    get:
      tags:
      - "Identifier"
      summary: "Retrieve a specific Identifier record."
      operationId: "getIdentifierById"
      responses:
        "200":
          description: "The requested Identifier record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identifier"
                exampleSetFlag: false
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    put:
      tags:
      - "Identifier"
      summary: "Replace a Identifier record."
      operationId: "replaceIdentifier"
      requestBody:
        description: "Full record data to replace the existing resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Identifier"
              exampleSetFlag: false
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the update..."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identifier"
                exampleSetFlag: false
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    delete:
      tags:
      - "Identifier"
      summary: "Delete a Identifier Record"
      description: "Marks the Identifier record as inactive or remo..."
      operationId: "deleteIdentifierRecord"
      responses:
        "204":
          description: "Record successfully deleted (or deactivated)."
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    patch:
      tags:
      - "Identifier"
      summary: "Partially update a Identifier record."
      operationId: "updateIdentifier"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IdentifierUpdate"
              exampleSetFlag: false
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the update..."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identifier"
                exampleSetFlag: false
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    parameters:
    - name: "notificationReferenceKey"
      in: "path"
      description: "The unique identifier for the parent resource."
      required: true
      schema:
        type: "string"
        exampleSetFlag: false
    - name: "identifierKey"
      in: "path"
      description: "The unique identifier for the specific Identifier."
      required: true
      schema:
        type: "string"
        example: "PR-1234567"
        exampleSetFlag: true
components:
  schemas:
    Codes:
      type: "array"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    ErrorDetail:
      required:
      - "code"
      - "message"
      - "timestamp"
      type: "object"
      properties:
        code:
          type: "string"
          description: "A unique, system-defined error code (e.g., 'AUT..."
          example: "NOT_FOUND_PR"
          exampleSetFlag: true
        message:
          type: "string"
          description: "A human-readable summary providing specific det..."
          example: "Personnel Record with ID PR-1234567 was not found."
          exampleSetFlag: true
        details:
          type: "array"
          description: "Optional array of specific field-level validati..."
          exampleSetFlag: false
          items:
            type: "object"
            properties:
              field:
                type: "string"
                description: "The specific field that failed validation (e.g., 'firstName')."
                example: "payrollId"
                exampleSetFlag: true
              issue:
                type: "string"
                description: "The validation message for the field (e.g., 'must be\
                  \ numeric')."
                example: "must be unique"
                exampleSetFlag: true
            exampleSetFlag: false
        timestamp:
          type: "string"
          description: "The time the error occurred, in ISO 8601 format."
          format: "date-time"
          example: "2025-11-10T10:30:00Z"
          exampleSetFlag: true
      description: "Standard format for all API error responses."
      exampleSetFlag: false
    EventTypes:
      type: "string"
      description: "types of events."
      exampleSetFlag: false
      enum:
      - "INVOICE_RECEIVED"
      - "ITEM_SHIPPED"
    Identifier:
      type: "object"
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+..."
          exampleSetFlag: false
        identifier_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Business key for the identifier Pattern: ^[a-zA..."
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          exampleSetFlag: false
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
      description: "External system identifier"
      exampleSetFlag: false
    IdentifierCreate:
      required:
      - "identifier_key"
      type: "object"
      description: "Identifier Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/Identifier"
        exampleSetFlag: false
    IdentifierUpdate:
      type: "object"
      properties:
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          exampleSetFlag: false
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
      description: "Identifier Update for Patch and Put"
      exampleSetFlag: false
    NotificationReference:
      type: "object"
      properties:
        notification_reference_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value for the referenc... Pat..."
          exampleSetFlag: false
        notification_reference_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique key value for the reference recor... Pat..."
          exampleSetFlag: false
        source_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "The unique key identifying the reference... Pat..."
          exampleSetFlag: false
        source_actor:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "The unique key identifying the reference... Pat..."
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier (e.g..."
          exampleSetFlag: false
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
        identifier:
          $ref: "#/components/schemas/Identifier"
          exampleSetFlag: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the reference was crea..."
          format: "date-time"
          exampleSetFlag: false
        event_type:
          $ref: "#/components/schemas/EventTypes"
          exampleSetFlag: false
      description: "Reference to a PartOrder Aggregate Root, often ..."
      exampleSetFlag: false
    NotificationReferenceCreate:
      required:
      - "notification_reference_key"
      type: "object"
      description: "NotificationReference Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/NotificationReference"
        exampleSetFlag: false
    NotificationReferenceUpdate:
      type: "object"
      properties:
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
        identifier:
          $ref: "#/components/schemas/Identifier"
          exampleSetFlag: false
        event_type:
          $ref: "#/components/schemas/EventTypes"
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier (e.g..."
          exampleSetFlag: false
        source_actor:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "The unique key identifying the reference... Pat..."
          exampleSetFlag: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the reference was crea..."
          format: "date-time"
          exampleSetFlag: false
      description: "NotificationReference Update for Patch and Put"
      exampleSetFlag: false
  responses:
    NotFoundError:
      description: "The requested resource was not found."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
            exampleSetFlag: false
    BadRequestError:
      description: "The request was malformed, failed validation, o..."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
            exampleSetFlag: false
    UnauthorizedError:
      description: "Authentication failed. The access token is miss..."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
            exampleSetFlag: false
    ForbiddenError:
      description: "The authenticated user does not have the necess..."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
            exampleSetFlag: false
    ConflictError:
      description: "The request could not be completed because it c..."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
            exampleSetFlag: false
    ServerError:
      description: "An unexpected error occurred on the server whil..."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
            exampleSetFlag: false
