---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    Codes:
      type: "array"
      items:
        type: "string"
    EventTypes:
      type: "string"
      description: "types of events."
      enum:
      - "INVOICE_RECEIVED"
      - "ITEM_SHIPPED"
    Identifier:
      type: "object"
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
        identifier_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Business key for the identifier Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
        context:
          type: "string"
          description: "Context or domain of the identifier"
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
        system_codes:
          $ref: "#/components/schemas/Codes"
      description: "External system identifier"
    NotificationReference:
      type: "object"
      properties:
        notification_reference_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value for the referenc... Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
        notification_reference_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique key value for the reference recor... Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
        source_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "The unique key identifying the reference... Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
        source_actor:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "The unique key identifying the reference... Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
        context:
          type: "string"
          description: "Context or domain of the identifier (e.g..."
        system_codes:
          $ref: "#/components/schemas/Codes"
        identifier:
          $ref: "#/components/schemas/Identifier"
        occurrence_date_time:
          type: "string"
          description: "The date and time the reference was crea..."
          format: "date-time"
        event_type:
          $ref: "#/components/schemas/EventTypes"
      description: "Reference to a PartOrder Aggregate Root, often used by external\
        \ systems."
