---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    Codes:
      type: "array"
      items:
        type: "string"
    ControlAccountReference:
      type: "object"
      properties:
        control_account_reference_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
        control_account_reference_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
        control_account_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
        context:
          type: "string"
          description: "Context or domain of the identifier"
        system_codes:
          $ref: "#/components/schemas/Codes"
        control_account:
          $ref: "#/components/schemas/Identifier"
        occurrence_date_time:
          type: "string"
          description: "The date and time the event occurred."
          format: "date-time"
      description: "External system identifier"
    DaysOfWeekTypes:
      type: "string"
      description: "types of days of weeks."
      enum:
      - "SUN"
      - "MON"
      - "TUES"
      - "WED"
      - "THURS"
      - "FRI"
      - "SAT"
    DurationUOMTypes:
      type: "string"
      description: "types of duration u o ms."
      enum:
      - "MINUTES"
      - "HOURS"
      - "DAYS"
      - "DAY_OF_MONTH"
      - "WEEKS"
      - "BI_WEEKS"
      - "SEMI_MONTHS"
      - "MONTHS"
      - "QUARTERS"
      - "SEMI_YEARS"
      - "YEARS"
      - "MULTI_YEARS"
      - "CUSTOM"
      - "OCCURRENCE"
      - "UNLIMITED"
      - "NONE"
      - "OTHER"
    EffectivePeriod:
      type: "object"
      properties:
        effective_period_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique key identifying the effective per... Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric characters and underscores only)"
        active_indicator:
          type: "boolean"
          description: "Indicator if the period is currently act..."
        exclusive_indicator:
          type: "boolean"
          description: "Indicator if the period is exclusive"
        start_date_time:
          type: "string"
          description: "Start date and time of the effective per..."
          format: "date-time"
        complete_date_time:
          type: "string"
          description: "Completion date and time of the effectiv..."
          format: "date-time"
        duration_uom_type:
          $ref: "#/components/schemas/DurationUOMTypes"
        duration_value:
          type: "string"
          description: "Value of the duration"
        recur_uom_type:
          $ref: "#/components/schemas/DurationUOMTypes"
        recur_count:
          type: "string"
          description: "Count of recurrence"
        recur_values:
          $ref: "#/components/schemas/Codes"
        recur_criteria:
          type: "string"
          description: "Criteria defining recurrence"
        recur_indicator:
          type: "boolean"
          description: "Indicator if recurrence is enabled"
        timeslot:
          $ref: "#/components/schemas/TimeSlot"
      description: "Effective Period"
    FinancialTransactionTypes:
      type: "string"
      description: "types of financial transactions."
      enum:
      - "ASSETS"
      - "CONTRA_ASSET"
      - "LIABILITY"
      - "EQUITY"
      - "INVENTORY"
      - "INTANGIBLE_ASSET"
      - "PREPAID_EXPENSE"
      - "INCOME"
      - "COGS"
      - "EXPENSE"
      - "DEPRECIATION"
      - "SALES_DISCOUNT"
      - "RETURNS"
      - "CASH_INFLOW"
      - "CASH_OUTFLOW"
      - "BANK_CHARGE"
      - "LOAN_RECEIVABLE"
      - "LOAN_PAYABLE"
      - "INVESTMENT"
      - "DIVIDEND"
      - "INTEREST_INCOME"
      - "INTEREST_EXPENSE"
      - "OBLIGATION_NOTE"
      - "OBLIGATION_CREDIT"
      - "OBLIGATION_TAX"
      - "OBLIGATION_OTHER"
      - "TAX_PAYABLE"
      - "DEFERRED_REVENUE"
      - "ACCRUED_EXPENSE"
      - "PROVISION"
      - "DEBIT"
      - "CREDIT"
      - "CAPITALIZATION"
      - "AMORTIZATION"
      - "VARIANCE"
      - "INVOICE"
      - "RECEIPT"
      - "RECEIVABLE_RECEIPT"
      - "DISBURSEMENT"
      - "TRANSFER"
      - "SERVICE"
      - "FEE"
      - "REBATE"
      - "OTHER"
      - "CUSTOM"
    Identifier:
      type: "object"
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
        identifier_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Business key for the identifier Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
        context:
          type: "string"
          description: "Context or domain of the identifier"
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
        system_codes:
          $ref: "#/components/schemas/Codes"
      description: "External system identifier"
    List:
      type: "array"
      items:
        type: "string"
    Money:
      type: "object"
      properties:
        money_key:
          type: "string"
          description: "The unique key for the monetary value."
        money_id:
          type: "string"
          description: "The unique ID for the monetary value."
        currency_code:
          type: "string"
          description: "ISO currency code, e.g., 'USD'."
        display_value:
          type: "string"
          description: "The locale-specific display format for t..."
        locale:
          type: "string"
          description: "The locale code (e.g., en-US, fr-FR)."
        value:
          type: "string"
          description: "The monetary value."
      description: "Represents a monetary value, including its currency, locale, and\
        \ display format."
    OrganizationTypes:
      type: "string"
      description: "types of organizations."
      enum:
      - "CORPORATION"
      - "DIVISION"
      - "FRANCHISE"
      - "GROUP"
      - "STORE"
      - "DEALERSHIP"
      - "BRANCH"
      - "DEPARTMENT"
      - "SECTION"
      - "TEAM"
      - "OTHER"
    PartyIdentifier:
      type: "object"
      properties:
        party_identifier_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
        party_identifier_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
        party_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
        party_identifier_type:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
        context:
          type: "string"
          description: "Context or domain of the identifier"
        party_relationship_types:
          pattern: "^[a-zA-Z0-9_]+$"
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: "array"
          items:
            $ref: "#/components/schemas/PartyRelationshipTypes"
        system_codes:
          $ref: "#/components/schemas/Codes"
        party:
          $ref: "#/components/schemas/Identifier"
        occurrence_date_time:
          type: "string"
          description: "The date and time the event occurred."
          format: "date-time"
        duration:
          $ref: "#/components/schemas/EffectivePeriod"
      description: "External system identifier"
    PartyIdentifiers:
      type: "array"
      items:
        $ref: "#/components/schemas/PartyIdentifier"
    PartyRelationshipTypes:
      type: "string"
      description: "types of party relationships."
      enum:
      - "CORPORATION"
      - "GROUP"
      - "STORE"
      - "BRANCH"
      - "DEPARTMENT"
      - "SECTION"
      - "TEAM"
      - "DEALERSHIP"
      - "THIRD_PARTY"
      - "VENDOR"
      - "SUPPLIER"
      - "PARTNER_ORGANIZATION"
      - "AFFILIATE"
      - "DISTRIBUTOR"
      - "MANUFACTURER"
      - "SERVICE_PROVIDER"
      - "EMPLOYER"
      - "INTERNAL_ORGANIZATION"
      - "COST_CENTER"
      - "FREIGHT_FORWARDER"
      - "BUYER"
      - "REGULATOR"
      - "GOVERNMENT_AGENCY"
      - "NON_PROFIT"
      - "FRANCHISE"
      - "SUBSIDIARY"
      - "DIVISION"
      - "JOINT_VENTURE"
      - "AUDITOR"
      - "ACTOR"
      - "ACCOUNTABLE"
      - "RESPONSIBLE"
      - "CONSULT"
      - "NOTIFY"
      - "EXECUTE"
      - "PART_OF"
      - "MEMBERSHIP"
      - "COMPOSED_IN"
      - "CUSTOMER"
      - "CO_SIGNER"
      - "SPOUSE"
      - "PARENT"
      - "CHILD"
      - "SIBLING"
      - "LEGAL_GUARDIAN"
      - "DEPENDENT"
      - "EMERGENCY_CONTACT"
      - "FAMILY_MEMBER"
      - "FRIEND"
      - "ACQUAINTANCE"
      - "ASSOCIATE"
      - "EX_SPOUSE"
      - "PROFESSIONAL_CONTACT"
      - "MANAGER"
      - "CO_WORKER"
      - "FINANCIAL_ADVISOR"
      - "SELF"
      - "ROMANTIC_PARTNER"
      - "OTHER_FAMILY"
      - "CAREGIVER"
      - "MENTOR"
      - "MENTEE"
      - "HEIR"
      - "TRUSTEE_PERSON"
      - "REFERENCE_PERSONAL"
      - "REFERENCE_PROFESSIONAL"
      - "AGENT"
      - "BENEFICIARY"
      - "GUARANTOR"
      - "EMPLOYEE"
      - "CONTRACTOR"
      - "OWNER"
      - "BUSINESS_PARTNER"
      - "SERVICE_CONSUMER"
      - "POLITICAL_AFFILIATE"
      - "ADVISOR_CONSULTANT"
      - "PROXY"
      - "SHAREHOLDER"
      - "INVESTOR"
      - "CUSTODIAN"
      - "SOLD_TO"
      - "SHIP_TO"
      - "PAYER"
      - "PAYEE"
      - "GIFT_TO"
      - "LOAN_PROVIDER"
      - "CREDIT_CARD_PROVIDER"
      - "LESSEE"
      - "LESSOR"
      - "INSURED"
      - "INSURER"
      - "UNDERWRITER"
      - "RECIPIENT"
      - "TRANSACTION_FROM"
      - "TRANSACTION_TO"
      - "REMOVE"
      - "OTHER"
    SubsidiaryLedgerTransaction:
      type: "object"
      properties:
        subsidiary_ledger_transaction_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier for the Subsidiary Led... Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
        subsidiary_ledger_transaction_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier for the Subsidiary Led... Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
        control_account_key:
          $ref: "#/components/schemas/ControlAccountReference"
        transaction_date:
          type: "string"
          description: "The date the source transaction occurred..."
          format: "date"
        posting_date:
          type: "string"
          description: "The date the source transaction occurred..."
          format: "date"
        transaction_type:
          $ref: "#/components/schemas/FinancialTransactionTypes"
        org_id:
          type: "string"
          description: "The ID of the organization (cost or prof..."
          example: "1"
        account_key:
          type: "string"
          description: "specific account (e.g., A/R account ID, ..."
          example: "1"
        party_identifiers:
          $ref: "#/components/schemas/PartyIdentifiers"
        org_type:
          $ref: "#/components/schemas/OrganizationTypes"
        total_money:
          $ref: "#/components/schemas/Money"
        description:
          maxLength: 255
          type: "string"
          description: "A description of the transaction."
        subsidiary_ledger_transaction_status_type:
          $ref: "#/components/schemas/SubsidiaryLedgerTransactionStatusTypes"
      description: "nullable"
    SubsidiaryLedgerTransactionStatusTypes:
      type: "string"
      description: "types of subsidiary ledger transaction status."
      enum:
      - "DRAFT"
      - "SUBMITTED"
      - "APPROVED"
      - "POSTED"
      - "RECONCILED"
      - "VOIDED"
    TimeSlot:
      type: "object"
      properties:
        time_slot_key:
          maximum: 100
          minimum: 0
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique business key for the time slot. Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
        end_day:
          $ref: "#/components/schemas/DaysOfWeekTypes"
        end_time:
          pattern: "^([01]\\d|2[0-3]):([0-5]\\d)$"
          type: "string"
          description: "End time in HH:mm format. Pattern: ^([01]\\d|2[0-3]):([0-5]\\\
            d)$ (Must be in HH:mm 24-hour format)"
          format: "date-time"
        recurring_indicator:
          type: "boolean"
          description: "Indicates if the time slot is recurring."
        recurring_period:
          $ref: "#/components/schemas/EffectivePeriod"
        start_day:
          $ref: "#/components/schemas/DaysOfWeekTypes"
        start_time:
          pattern: "^([01]\\d|2[0-3]):([0-5]\\d)$"
          type: "string"
          description: "Start time in HH:mm format. Pattern: ^([01]\\d|2[0-3]):([0-5]\\\
            d)$ (Must be in HH:mm 24-hour format)"
          format: "date-time"
        timeslot_directive_types:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: "array"
          items:
            $ref: "#/components/schemas/TimeslotDirectiveTypes"
        time_slot_id:
          maximum: 100
          minimum: 0
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier for the time slot reco... Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
        week_of_date:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: "array"
          format: "date"
          items:
            type: "string"
      description: "Range of time for the appointment including start/end times, recurring\
        \ patterns, and directives."
    TimeslotDirectiveTypes:
      type: "string"
      description: "types of timeslot directives."
      enum:
      - "AFTER"
      - "ANYTIME"
      - "BEFORE"
      - "BETWEEN"
      - "BLOCK"
      - "UNKNOWN"
