---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    Codes:
      type: "array"
      description: "List of Codes"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    Link:
      type: "array"
      description: "Quick Link"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    Links:
      type: "array"
      description: "List of Links"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    PaymentEvent:
      type: "object"
      properties:
        payment_event_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value for the reference record. Pattern:\
            \ ^[a-zA-Z0-9_]+$ (Alphanumeric and underscores allowed)"
          nullable: false
          exampleSetFlag: false
        payment_event_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique key value for the reference record. Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
          nullable: false
          exampleSetFlag: false
        payment_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "The unique key identifying the referenced PaymentMethod (Party)\
            \ aggregate. Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric and underscores allowed)"
          nullable: false
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the reference."
          nullable: true
          exampleSetFlag: false
        old_payment_status_type:
          description: "Type of payment method used for the transaction (e.g., CREDIT_CARD,\
            \ ACH)."
          $ref: "#/components/schemas/PaymentStatusTypes"
          nullable: false
          example: "CREDIT_CARD"
          exampleSetFlag: true
        new_payment_status_type:
          description: "Type of payment method used for the transaction (e.g., CREDIT_CARD,\
            \ ACH)."
          $ref: "#/components/schemas/PaymentStatusTypes"
          nullable: false
          example: "CREDIT_CARD"
          exampleSetFlag: true
        payment_transaction_id:
          type: "string"
          description: "Optional: The specific transaction ID causing the status change."
          nullable: true
          exampleSetFlag: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the paymentMethod was associated with the\
            \ order."
          format: "date-time"
          nullable: false
          exampleSetFlag: false
      description: "Reference to a PaymentMethod (Party) Aggregate Root for financing\
        \ details."
      exampleSetFlag: false
    PaymentEventCreate:
      required:
      - "payment_event_key"
      type: "object"
      description: "PaymentEvent Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/PaymentEvent"
        exampleSetFlag: false
    PaymentEventUpdate:
      type: "object"
      properties:
        new_payment_status_type:
          description: "Type of payment method used for the transaction (e.g., CREDIT_CARD,\
            \ ACH)."
          $ref: "#/components/schemas/PaymentStatusTypes"
          nullable: false
          example: "CREDIT_CARD"
          exampleSetFlag: true
        context:
          type: "string"
          description: "Context or domain of the reference."
          nullable: true
          exampleSetFlag: false
        old_payment_status_type:
          description: "Type of payment method used for the transaction (e.g., CREDIT_CARD,\
            \ ACH)."
          $ref: "#/components/schemas/PaymentStatusTypes"
          nullable: false
          example: "CREDIT_CARD"
          exampleSetFlag: true
        occurrence_date_time:
          type: "string"
          description: "The date and time the paymentMethod was associated with the\
            \ order."
          format: "date-time"
          nullable: false
          exampleSetFlag: false
      description: "PaymentEvent Update for Patch and Put"
      exampleSetFlag: false
    PaymentStatusTypes:
      type: "string"
      description: "types of payment status."
      exampleSetFlag: false
      enum:
      - "CREATED"
      - "PENDING"
      - "PROCESSING"
      - "PROCESSED"
      - "COMPLETED"
      - "SUCCEEDED"
      - "PAID"
      - "REJECTED"
      - "SCHEDULED"
      - "SUBMITTED"
      - "DEFERRED"
      - "DEFERRED_INTERNAL"
      - "CLEARED"
      - "FRAUD_REVIEW"
      - "APPROVED"
      - "ACCEPTED"
      - "REQUIRES_ACTION"
      - "REQUIRES_PAYMENT_STATUS"
      - "AUTO_SCHEDULED"
      - "AUTO_INITIATED"
      - "MANUAL_INITIATED"
      - "PENDING_PAYER_FUNDS"
      - "FAILED"
      - "DENIED"
      - "EXPIRED"
      - "CANCELLED"
      - "VOIDED"
      - "REVERSED"
      - "REFUNDED"
      - "PAYROLL_PENDING"
      - "PAYROLL_FINALIZED"
      - "ACTIVE"
      - "INACTIVE"
      - "FUNDED"
      - "RETURNED"
