---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths:
  /general-ledger-accounts:
    get:
      tags:
      - "GeneralLedgerAccount"
      summary: "Retrieve a list of all GeneralLedgerAccount records."
      operationId: "listGeneralLedgerAccounts"
      parameters:
      - name: "limit"
        in: "query"
        description: "Maximum number of records to return."
        schema:
          maximum: 100
          minimum: 1
          type: "integer"
          default: 50
      - name: "cursor"
        in: "query"
        description: "starting point for next set of results"
        schema:
          type: "string"
      responses:
        "200":
          description: "A list of GeneralLedgerAccount records."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/GeneralLedgerAccount"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"
    post:
      tags:
      - "GeneralLedgerAccount"
      summary: "Create a new GeneralLedgerAccount record."
      operationId: "createGeneralLedgerAccount"
      requestBody:
        description: "GeneralLedgerAccount data to create the new resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GeneralLedgerAccountCreate"
        required: true
      responses:
        "201":
          description: "GeneralLedgerAccount created successfully."
          headers:
            Location:
              description: "The URI of the newly created resource."
              schema:
                type: "string"
                example: "/general-ledger-accounts/PR-1234567"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralLedgerAccount"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "409":
          $ref: "#/components/responses/ConflictError"
  /general-ledger-accounts/{generalLedgerAccountKey}:
    get:
      tags:
      - "GeneralLedgerAccount"
      summary: "Retrieve a specific GeneralLedgerAccount record."
      operationId: "getGeneralLedgerAccountById"
      responses:
        "200":
          description: "The requested GeneralLedgerAccount record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralLedgerAccount"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    put:
      tags:
      - "GeneralLedgerAccount"
      summary: "Replace a GeneralLedgerAccount record."
      operationId: "replaceGeneralLedgerAccount"
      requestBody:
        description: "Full record data to replace the existing resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GeneralLedgerAccount"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralLedgerAccount"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    delete:
      tags:
      - "GeneralLedgerAccount"
      summary: "Delete a GeneralLedgerAccount Record"
      description: "Marks the GeneralLedgerAccount record as inactive or removes it\
        \ entirely."
      operationId: "deleteGeneralLedgerAccountRecord"
      responses:
        "204":
          description: "Record successfully deleted (or deactivated)."
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    patch:
      tags:
      - "GeneralLedgerAccount"
      summary: "Partially update a GeneralLedgerAccount record."
      operationId: "updateGeneralLedgerAccount"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GeneralLedgerAccountUpdate"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralLedgerAccount"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    parameters:
    - name: "generalLedgerAccountKey"
      in: "path"
      description: "The unique identifier for the specific GeneralLedgerAccount."
      required: true
      schema:
        type: "string"
        example: "PR-1234567"
  /general-ledger-accounts/{generalLedgerAccountKey}/identifiers:
    get:
      tags:
      - "Identifier"
      summary: "Retrieve a list of Identifier records scoped by generalLedgerAccountKey."
      operationId: "listIdentifiersByGeneralLedgerAccountKey"
      parameters:
      - name: "limit"
        in: "query"
        description: "Maximum number of records to return."
        schema:
          maximum: 100
          minimum: 1
          type: "integer"
          default: 50
      - name: "cursor"
        in: "query"
        description: "starting point for next set of results"
        schema:
          type: "string"
      responses:
        "200":
          description: "A list of Identifier records."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Identifier"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"
    post:
      tags:
      - "Identifier"
      summary: "Create a new Identifier record."
      operationId: "createIdentifier"
      requestBody:
        description: "Identifier data to create the new resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IdentifierCreate"
        required: true
      responses:
        "201":
          description: "Identifier created successfully."
          headers:
            Location:
              description: "The URI of the newly created resource."
              schema:
                type: "string"
                example: "/part-search-results/PS-12345/bill-of-materials/BOM-001"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identifier"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "409":
          $ref: "#/components/responses/ConflictError"
    parameters:
    - name: "generalLedgerAccountKey"
      in: "path"
      description: "The unique identifier for the parent resource."
      required: true
      schema:
        type: "string"
  /general-ledger-accounts/{generalLedgerAccountKey}/identifiers/{identifierKey}:
    get:
      tags:
      - "Identifier"
      summary: "Retrieve a specific Identifier record."
      operationId: "getIdentifierById"
      responses:
        "200":
          description: "The requested Identifier record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identifier"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    put:
      tags:
      - "Identifier"
      summary: "Replace a Identifier record."
      operationId: "replaceIdentifier"
      requestBody:
        description: "Full record data to replace the existing resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Identifier"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identifier"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    delete:
      tags:
      - "Identifier"
      summary: "Delete a Identifier Record"
      description: "Marks the Identifier record as inactive or removes it entirely."
      operationId: "deleteIdentifierRecord"
      responses:
        "204":
          description: "Record successfully deleted (or deactivated)."
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    patch:
      tags:
      - "Identifier"
      summary: "Partially update a Identifier record."
      operationId: "updateIdentifier"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IdentifierUpdate"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identifier"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    parameters:
    - name: "generalLedgerAccountKey"
      in: "path"
      description: "The unique identifier for the parent resource."
      required: true
      schema:
        type: "string"
    - name: "identifierKey"
      in: "path"
      description: "The unique identifier for the specific Identifier."
      required: true
      schema:
        type: "string"
        example: "PR-1234567"
components:
  schemas: {}
