---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    Codes:
      type: "array"
      description: "List of Codes"
      items:
        type: "string"
    FinancialCategoryTypes:
      type: "string"
      description: "types of financial categorys."
      enum:
      - "CAPEX"
      - "OPEX"
      - "HARDWARE"
      - "SOFTWARE"
      - "MAINTENANCE"
      - "TRAVEL"
      - "TRAINING"
      - "UTILITIES"
      - "RENT"
      - "SALARY"
      - "REVENUE"
      - "TAX"
      - "OTHER"
    GeneralLedgerAccount:
      type: "object"
      properties:
        identifiers:
          description: "List of identifiers associated with this control account."
          $ref: "#/components/schemas/Identifiers"
          nullable: true
        general_ledger_account_desc:
          maxLength: 255
          type: "string"
          description: "Description of the control account."
          nullable: true
        general_ledger_account_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier for the control account. Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
          nullable: true
        general_ledger_account_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Master record for a General Ledger Account (Chart of Accounts),\
            \ capturing its identity, type, and descriptive fields. Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
          nullable: false
        general_ledger_account_name:
          maxLength: 100
          type: "string"
          description: "Display name of the control account."
          nullable: true
        general_ledger_account_type:
          description: "Type of the control account, defining its classification within\
            \ the ledger."
          $ref: "#/components/schemas/GeneralLedgerAccountTypes"
          nullable: true
        control_type_id:
          type: "string"
          description: "Identifier for the control type of the account."
          nullable: false
        bank_account_id:
          type: "string"
          description: "Associated bank account identifier."
          nullable: false
        is_counted:
          type: "boolean"
          description: "Indicates if the account is a counted account (e.g., for inventory)."
          nullable: false
        prefix:
          type: "string"
          description: "The prefix of the account number."
          nullable: false
        financial_category_type:
          description: "Financial Category Type"
          $ref: "#/components/schemas/FinancialCategoryTypes"
          nullable: true
      description: "Master data record for a General Ledger Account, used to define\
        \ the Chart of Accounts."
    GeneralLedgerAccountTypes:
      type: "string"
      description: "types of general ledger accounts."
      enum:
      - "ASSETS"
      - "BANK_ACCOUNT"
      - "FIXED_ASSETS"
      - "CONTRA_ASSET"
      - "LIABILITY"
      - "CREDIT_CARD_LIABILITY"
      - "LONG_TERM_LIABILITY"
      - "EQUITY"
      - "CLEARING"
      - "CREDIT_CARD_CLEARING"
      - "PROVISION"
      - "ROUNDING"
      - "REVENUE"
      - "OTHER_INCOME"
      - "COGS"
      - "EXPENSE"
      - "DEPRECIATION"
      - "TAX"
      - "DISCOUNT"
      - "REBATE"
      - "FEE"
      - "SERVICE"
      - "CREDIT"
      - "OTHER"
      - "DEALER"
      - "VEHICLE"
      - "ACCESSORIES"
      - "OPTION"
      - "CUSTOMER"
      - "VENDOR"
      - "EMPLOYEE"
      - "PRODUCT"
      - "REPAIR_ORDER"
      - "PARTS_SALES_ORDER"
      - "PACKAGE"
      - "REFERENCE"
    Identifier:
      type: "object"
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          nullable: false
        identifier_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Business key for the identifier Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          nullable: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          nullable: true
        value:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
        detail:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
        system_codes:
          description: "Associated system codes for this identifier"
          $ref: "#/components/schemas/Codes"
          nullable: true
      description: "External system identifier"
    Identifiers:
      type: "array"
      description: "List of Identifier"
      items:
        $ref: "#/components/schemas/Identifier"
    Link:
      type: "array"
      description: "Quick Link"
      items:
        type: "string"
    Links:
      type: "array"
      description: "List of Links"
      items:
        type: "string"
