---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    AccountingPeriod:
      type: "object"
      properties:
        identifiers:
          $ref: "#/components/schemas/Identifiers"
          exampleSetFlag: false
        period_desc:
          maxLength: 255
          type: "string"
          description: "Descriptive name for the accounting peri..."
          exampleSetFlag: false
        accounting_period_id:
          pattern: "^[0-9]{6}$"
          type: "string"
          description: "Business key for the accounting period (... Pattern: ^[0-9]{6}$\
            \ (Must be in YYYYMM format)"
          exampleSetFlag: false
        accounting_period_key:
          pattern: "^[0-9]{6}$"
          type: "string"
          description: "Business key for the accounting period (... Pattern: ^[0-9]{6}$\
            \ (Must be in YYYYMM format)"
          exampleSetFlag: false
        period_name:
          maxLength: 100
          type: "string"
          description: "Display name of the accounting period."
          exampleSetFlag: false
        start_date:
          type: "string"
          description: "The beginning date of the accounting per..."
          format: "date"
          exampleSetFlag: false
        end_date:
          type: "string"
          description: "The ending date of the accounting period..."
          format: "date"
          exampleSetFlag: false
        accounting_period_status_type:
          $ref: "#/components/schemas/AccountingPeriodStatusTypes"
          exampleSetFlag: false
        fiscal_year:
          type: "integer"
          description: "The fiscal year this period belongs to."
          format: "int32"
          exampleSetFlag: false
      description: "Defines a fiscal period, including its unique identifiers, start\
        \ and end dates, and current status."
      exampleSetFlag: false
    AccountingPeriodCreate:
      required:
      - "accounting_period_key"
      type: "object"
      description: "AccountingPeriod Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/AccountingPeriod"
        exampleSetFlag: false
    AccountingPeriodStatusTypes:
      type: "string"
      description: "types of accounting period status."
      exampleSetFlag: false
      enum:
      - "OPEN"
      - "ADJUSTMENT"
      - "CLOSED"
      - "FUTURE"
      - "PENDING_CLOSURE"
      - "LOCKED"
      - "OTHER"
    AccountingPeriodUpdate:
      type: "object"
      properties:
        end_date:
          type: "string"
          description: "The ending date of the accounting period..."
          format: "date"
          exampleSetFlag: false
        period_desc:
          maxLength: 255
          type: "string"
          description: "Descriptive name for the accounting peri..."
          exampleSetFlag: false
        fiscal_year:
          type: "integer"
          description: "The fiscal year this period belongs to."
          format: "int32"
          exampleSetFlag: false
        identifiers:
          $ref: "#/components/schemas/Identifiers"
          exampleSetFlag: false
        accounting_period_status_type:
          $ref: "#/components/schemas/AccountingPeriodStatusTypes"
          exampleSetFlag: false
        period_name:
          maxLength: 100
          type: "string"
          description: "Display name of the accounting period."
          exampleSetFlag: false
        start_date:
          type: "string"
          description: "The beginning date of the accounting per..."
          format: "date"
          exampleSetFlag: false
      description: "AccountingPeriod Update for Patch and Put"
      exampleSetFlag: false
    Budget:
      type: "object"
      properties:
        budget_key:
          type: "string"
          description: "The unique key for the Budget."
          exampleSetFlag: false
        budget_id:
          type: "string"
          description: "The unique ID for the Budget."
          exampleSetFlag: false
        name:
          type: "string"
          description: "The name given to the budget (e.g., \"202..."
          exampleSetFlag: false
        accounting_period:
          $ref: "#/components/schemas/AccountingPeriod"
          exampleSetFlag: false
        status:
          $ref: "#/components/schemas/BudgetStatusTypes"
          exampleSetFlag: false
        approval_date:
          type: "string"
          description: "The date the budget was approved."
          format: "date"
          exampleSetFlag: false
        budget_items:
          $ref: "#/components/schemas/BudgetItems"
          exampleSetFlag: false
      description: "Represents an approved financial budget for a specific accounting\
        \ period."
      exampleSetFlag: false
    BudgetCreate:
      required:
      - "budget_key"
      type: "object"
      description: "Budget Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/Budget"
        exampleSetFlag: false
    BudgetItem:
      type: "object"
      properties:
        budget_item_key:
          type: "string"
          description: "The unique key for the BudgetItem."
          exampleSetFlag: false
        budget_item_id:
          type: "string"
          description: "The unique ID for the BudgetItem."
          exampleSetFlag: false
        general_ledger_account:
          $ref: "#/components/schemas/GeneralLedgerReference"
          exampleSetFlag: false
        control_account:
          $ref: "#/components/schemas/ControlAccountReference"
          exampleSetFlag: false
        financial_category:
          $ref: "#/components/schemas/FinancialCategoryTypes"
          exampleSetFlag: false
        budgeted_amount:
          $ref: "#/components/schemas/Money"
          exampleSetFlag: false
      description: "Represents a single line item within a financial budget, detailing\
        \ the forecasted expenditure or revenue."
      exampleSetFlag: false
    BudgetItemCreate:
      required:
      - "budget_item_key"
      type: "object"
      description: "BudgetItem Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/BudgetItem"
        exampleSetFlag: false
    BudgetItemUpdate:
      type: "object"
      properties:
        budgeted_amount:
          $ref: "#/components/schemas/Money"
          exampleSetFlag: false
        financial_category:
          $ref: "#/components/schemas/FinancialCategoryTypes"
          exampleSetFlag: false
        general_ledger_account:
          $ref: "#/components/schemas/GeneralLedgerReference"
          exampleSetFlag: false
        control_account:
          $ref: "#/components/schemas/ControlAccountReference"
          exampleSetFlag: false
      description: "BudgetItem Update for Patch and Put"
      exampleSetFlag: false
    BudgetItems:
      type: "array"
      exampleSetFlag: false
      items:
        $ref: "#/components/schemas/BudgetItem"
        exampleSetFlag: false
    BudgetStatusTypes:
      type: "string"
      description: "types of budget status."
      exampleSetFlag: false
      enum:
      - "DRAFT"
      - "SUBMITTED"
      - "PENDING_APPROVAL"
      - "APPROVED"
      - "ACTIVE"
      - "REJECTED"
      - "REVISED"
      - "CLOSED"
      - "VOIDED"
      - "EXPIRED"
      - "OTHER"
    BudgetUpdate:
      type: "object"
      properties:
        approval_date:
          type: "string"
          description: "The date the budget was approved."
          format: "date"
          exampleSetFlag: false
        budget_items:
          $ref: "#/components/schemas/BudgetItems"
          exampleSetFlag: false
        name:
          type: "string"
          description: "The name given to the budget (e.g., \"202..."
          exampleSetFlag: false
        accounting_period:
          $ref: "#/components/schemas/AccountingPeriod"
          exampleSetFlag: false
        status:
          $ref: "#/components/schemas/BudgetStatusTypes"
          exampleSetFlag: false
      description: "Budget Update for Patch and Put"
      exampleSetFlag: false
    Codes:
      type: "array"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    ControlAccountReference:
      type: "object"
      properties:
        control_account_reference_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        control_account_reference_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        control_account_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          exampleSetFlag: false
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
        control_account:
          $ref: "#/components/schemas/Identifier"
          exampleSetFlag: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the event occurred."
          format: "date-time"
          exampleSetFlag: false
      description: "External system identifier"
      exampleSetFlag: false
    ControlAccountReferenceCreate:
      required:
      - "control_account_reference_key"
      type: "object"
      description: "ControlAccountReference Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/ControlAccountReference"
        exampleSetFlag: false
    ControlAccountReferenceUpdate:
      type: "object"
      properties:
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          exampleSetFlag: false
        control_account:
          $ref: "#/components/schemas/Identifier"
          exampleSetFlag: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the event occurred."
          format: "date-time"
          exampleSetFlag: false
      description: "ControlAccountReference Update for Patch and Put"
      exampleSetFlag: false
    FinancialCategoryTypes:
      type: "string"
      description: "types of financial categorys."
      exampleSetFlag: false
      enum:
      - "CAPEX"
      - "OPEX"
      - "HARDWARE"
      - "SOFTWARE"
      - "MAINTENANCE"
      - "TRAVEL"
      - "TRAINING"
      - "UTILITIES"
      - "RENT"
      - "SALARY"
      - "REVENUE"
      - "TAX"
      - "OTHER"
    GeneralLedgerReference:
      type: "object"
      properties:
        general_ledger_reference_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique reference value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        general_ledger_reference_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique reference value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        general_ledger_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique reference value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the reference"
          exampleSetFlag: false
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
        general_ledger_identifier:
          $ref: "#/components/schemas/Identifier"
          exampleSetFlag: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the event occurred."
          format: "date-time"
          exampleSetFlag: false
      description: "External system reference"
      exampleSetFlag: false
    GeneralLedgerReferenceCreate:
      required:
      - "general_ledger_reference_key"
      type: "object"
      description: "GeneralLedgerReference Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/GeneralLedgerReference"
        exampleSetFlag: false
    GeneralLedgerReferenceUpdate:
      type: "object"
      properties:
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
        general_ledger_identifier:
          $ref: "#/components/schemas/Identifier"
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the reference"
          exampleSetFlag: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the event occurred."
          format: "date-time"
          exampleSetFlag: false
      description: "GeneralLedgerReference Update for Patch and Put"
      exampleSetFlag: false
    Identifier:
      type: "object"
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        identifier_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Business key for the identifier Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          exampleSetFlag: false
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
      description: "External system identifier"
      exampleSetFlag: false
    IdentifierCreate:
      required:
      - "identifier_key"
      type: "object"
      description: "Identifier Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/Identifier"
        exampleSetFlag: false
    IdentifierUpdate:
      type: "object"
      properties:
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          exampleSetFlag: false
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
      description: "Identifier Update for Patch and Put"
      exampleSetFlag: false
    Identifiers:
      type: "array"
      exampleSetFlag: false
      items:
        $ref: "#/components/schemas/Identifier"
        exampleSetFlag: false
    Money:
      type: "object"
      properties:
        money_key:
          type: "string"
          description: "The unique key for the monetary value."
          exampleSetFlag: false
        money_id:
          type: "string"
          description: "The unique ID for the monetary value."
          exampleSetFlag: false
        currency_code:
          type: "string"
          description: "ISO currency code, e.g., 'USD'."
          exampleSetFlag: false
        display_value:
          type: "string"
          description: "The locale-specific display format for t..."
          exampleSetFlag: false
        locale:
          type: "string"
          description: "The locale code (e.g., en-US, fr-FR)."
          exampleSetFlag: false
        value:
          type: "string"
          description: "The monetary value."
          exampleSetFlag: false
      description: "Represents a monetary value, including its currency, locale, and\
        \ display format."
      exampleSetFlag: false
