---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths:
  /geographic-boundaries:
    get:
      tags:
      - "GeographicBoundary"
      summary: "Retrieve a list of all GeographicBoundary records."
      operationId: "listGeographicBoundarys"
      parameters:
      - name: "limit"
        in: "query"
        description: "Maximum number of records to return."
        schema:
          maximum: 100
          minimum: 1
          type: "integer"
          default: 50
      - name: "cursor"
        in: "query"
        description: "starting point for next set of results"
        schema:
          type: "string"
      responses:
        "200":
          description: "A list of GeographicBoundary records."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/GeographicBoundary"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"
    post:
      tags:
      - "GeographicBoundary"
      summary: "Create a new GeographicBoundary record."
      operationId: "createGeographicBoundary"
      requestBody:
        description: "GeographicBoundary data to create the new resou..."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GeographicBoundaryCreate"
        required: true
      responses:
        "201":
          description: "GeographicBoundary created successfully."
          headers:
            Location:
              description: "The URI of the newly created resource."
              schema:
                type: "string"
                example: "/geographic-boundaries/PR-1234567"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeographicBoundary"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "409":
          $ref: "#/components/responses/ConflictError"
  /geographic-boundaries/{geographicBoundaryKey}:
    get:
      tags:
      - "GeographicBoundary"
      summary: "Retrieve a specific GeographicBoundary record."
      operationId: "getGeographicBoundaryById"
      responses:
        "200":
          description: "The requested GeographicBoundary record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeographicBoundary"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    put:
      tags:
      - "GeographicBoundary"
      summary: "Replace a GeographicBoundary record."
      operationId: "replaceGeographicBoundary"
      requestBody:
        description: "Full record data to replace the existing resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GeographicBoundary"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the update..."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeographicBoundary"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    delete:
      tags:
      - "GeographicBoundary"
      summary: "Delete a GeographicBoundary Record"
      description: "Marks the GeographicBoundary record as inactive..."
      operationId: "deleteGeographicBoundaryRecord"
      responses:
        "204":
          description: "Record successfully deleted (or deactivated)."
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    patch:
      tags:
      - "GeographicBoundary"
      summary: "Partially update a GeographicBoundary record."
      operationId: "updateGeographicBoundary"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GeographicBoundaryUpdate"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the update..."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeographicBoundary"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    parameters:
    - name: "geographicBoundaryKey"
      in: "path"
      description: "The unique identifier for the specific GeographicBoundary."
      required: true
      schema:
        type: "string"
        example: "PR-1234567"
components:
  schemas:
    Codes:
      type: "array"
      items:
        type: "string"
    ErrorDetail:
      required:
      - "code"
      - "message"
      - "timestamp"
      type: "object"
      properties:
        code:
          type: "string"
          description: "A unique, system-defined error code (e.g., 'AUT..."
          example: "NOT_FOUND_PR"
        message:
          type: "string"
          description: "A human-readable summary providing specific det..."
          example: "Personnel Record with ID PR-1234567 was not found."
        details:
          type: "array"
          description: "Optional array of specific field-level validati..."
          items:
            type: "object"
            properties:
              field:
                type: "string"
                description: "The specific field that failed validation (e.g., 'firstName')."
                example: "payrollId"
              issue:
                type: "string"
                description: "The validation message for the field (e.g., 'must be\
                  \ numeric')."
                example: "must be unique"
        timestamp:
          type: "string"
          description: "The time the error occurred, in ISO 8601 format."
          format: "date-time"
          example: "2025-11-10T10:30:00Z"
      description: "Standard format for all API error responses."
    GeographicBoundary:
      type: "object"
      properties:
        geographic_boundary_id:
          maximum: 100
          minimum: 0
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier for the geographic bou... Pat..."
        geographic_boundary_key:
          maximum: 100
          minimum: 0
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique business key for the geographic b... Pat..."
        geographic_codes:
          $ref: "#/components/schemas/Codes"
        locales:
          $ref: "#/components/schemas/Codes"
        geographic_type:
          $ref: "#/components/schemas/LocationTypes"
        geographic_values:
          $ref: "#/components/schemas/Codes"
        distance_max:
          maxLength: 20
          pattern: "^[0-9.]+$"
          type: "string"
          description: "Maximum distance constraint applied in s... Pat..."
        distance_min:
          maxLength: 20
          pattern: "^[0-9.]+$"
          type: "string"
          description: "Minimum distance constraint applied in s... Pat..."
        distance_type:
          $ref: "#/components/schemas/UnitOfMeasureTypes"
        name:
          maxLength: 100
          minLength: 1
          type: "string"
          description: "Human-readable name of the geographic bo..."
        vertices:
          maxLength: 2000
          type: "string"
          description: "Serialized coordinates defining polygon ..."
        description:
          maxLength: 255
          type: "string"
          description: "Detailed description of the geographic b..."
        center_latitude:
          pattern: "^-?\\d{1,2}\\.\\d{1,8}$"
          type: "string"
          description: "Central latitude coordinate of the bound... Pat..."
        center_longitude:
          pattern: "^-?\\d{1,3}\\.\\d{1,8}$"
          type: "string"
          description: "Central longitude coordinate of the boun... Pat..."
      description: "nullable"
    GeographicBoundaryCreate:
      required:
      - "geographic_boundary_key"
      type: "object"
      description: "GeographicBoundary Create for Post"
      allOf:
      - $ref: "#/components/schemas/GeographicBoundary"
    GeographicBoundaryUpdate:
      type: "object"
      properties:
        center_latitude:
          pattern: "^-?\\d{1,2}\\.\\d{1,8}$"
          type: "string"
          description: "Central latitude coordinate of the bound... Pat..."
        center_longitude:
          pattern: "^-?\\d{1,3}\\.\\d{1,8}$"
          type: "string"
          description: "Central longitude coordinate of the boun... Pat..."
        geographic_codes:
          $ref: "#/components/schemas/Codes"
        locales:
          $ref: "#/components/schemas/Codes"
        geographic_type:
          $ref: "#/components/schemas/LocationTypes"
        distance_min:
          maxLength: 20
          pattern: "^[0-9.]+$"
          type: "string"
          description: "Minimum distance constraint applied in s... Pat..."
        distance_type:
          $ref: "#/components/schemas/UnitOfMeasureTypes"
        vertices:
          maxLength: 2000
          type: "string"
          description: "Serialized coordinates defining polygon ..."
        geographic_values:
          $ref: "#/components/schemas/Codes"
        distance_max:
          maxLength: 20
          pattern: "^[0-9.]+$"
          type: "string"
          description: "Maximum distance constraint applied in s... Pat..."
        name:
          maxLength: 100
          minLength: 1
          type: "string"
          description: "Human-readable name of the geographic bo..."
        description:
          maxLength: 255
          type: "string"
          description: "Detailed description of the geographic b..."
      description: "GeographicBoundary Update for Patch and Put"
    LocationTypes:
      type: "string"
      description: "types of locations."
      enum:
      - "BOROUGH"
      - "PARISH"
      - "REGION"
      - "BOUNDARY"
      - "PROVINCE"
      - "VILLAGE"
      - "STATE"
      - "CITY"
      - "COUNTRY"
      - "LOCALITY"
      - "POSTAL"
      - "STREET"
      - "SUB_ADMIN_AREA"
      - "SUB_LOCALITY"
      - "FEDERAL"
      - "COUNTY"
      - "TELEMATICS"
      - "ADDRESS"
      - "NO_PREFERENCE"
      - "GPS"
      - "WAREHOUSE"
      - "DISTRICT"
    UnitOfMeasureTypes:
      type: "string"
      description: "types of unit of measures."
      enum:
      - "MILES"
      - "KM"
      - "GALLON"
      - "LITER"
      - "METER"
      - "QUARTER"
      - "OZ"
      - "LB"
      - "DATE_TIME"
      - "DATE"
      - "KG"
      - "DURATION"
      - "CURRENCY"
      - "POINTS"
      - "MINUTES"
      - "HOURS"
      - "DAYS"
      - "WEEKS"
      - "DAY_OF_MONTH"
      - "BI_WEEKS"
      - "SEMI_MONTHS"
      - "MONTHS"
      - "QUARTERS"
      - "SEMI_YEARS"
      - "YEARS"
      - "MULTI_YEARS"
      - "OCCURRENCE"
      - "CELSIUS"
      - "FAHRENHEIT"
      - "KELVIN"
      - "RANKINE"
      - "INCH"
      - "FEET"
      - "YARD"
      - "FATHOM"
      - "NAUTICAL"
      - "BYTES"
      - "CUSTOM"
      - "UNLIMITED"
      - "NONE"
      - "PERCENT"
      - "STATE"
      - "CITY"
      - "COUNTRY"
      - "LOCALITY"
      - "POSTAL"
      - "STREET"
      - "SUB_ADMIN_AREA"
      - "SUB_LOCALITY"
      - "FEDERAL"
      - "COUNTY"
      - "DISTRICT"
      - "NA"
      - "UNIT"
      - "WATT"
      - "ITEM"
      - "NET"
      - "GROSS"
      - "MINIMUM"
      - "MAXIMUM"
      - "OTHER"
  responses:
    NotFoundError:
      description: "The requested resource was not found."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
    BadRequestError:
      description: "The request was malformed, failed validation, o..."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
    UnauthorizedError:
      description: "Authentication failed. The access token is miss..."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
    ForbiddenError:
      description: "The authenticated user does not have the necess..."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
    ConflictError:
      description: "The request could not be completed because it c..."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
    ServerError:
      description: "An unexpected error occurred on the server whil..."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
