---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    Codes:
      type: "array"
      items:
        type: "string"
    GeographicBoundary:
      type: "object"
      properties:
        geographic_boundary_id:
          maximum: 100
          minimum: 0
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier for the geographic bou... Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
        geographic_boundary_key:
          maximum: 100
          minimum: 0
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique business key for the geographic b... Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
        geographic_codes:
          $ref: "#/components/schemas/Codes"
        locales:
          $ref: "#/components/schemas/Codes"
        geographic_type:
          $ref: "#/components/schemas/LocationTypes"
        geographic_values:
          $ref: "#/components/schemas/Codes"
        distance_max:
          maxLength: 20
          pattern: "^[0-9.]+$"
          type: "string"
          description: "Maximum distance constraint applied in s... Pattern: ^[0-9.]+$\
            \ (Must be a numeric value.)"
        distance_min:
          maxLength: 20
          pattern: "^[0-9.]+$"
          type: "string"
          description: "Minimum distance constraint applied in s... Pattern: ^[0-9.]+$\
            \ (Must be a numeric value.)"
        distance_type:
          $ref: "#/components/schemas/UnitOfMeasureTypes"
        name:
          maxLength: 100
          minLength: 1
          type: "string"
          description: "Human-readable name of the geographic bo..."
        vertices:
          maxLength: 2000
          type: "string"
          description: "Serialized coordinates defining polygon ..."
        description:
          maxLength: 255
          type: "string"
          description: "Detailed description of the geographic b..."
        center_latitude:
          pattern: "^-?\\d{1,2}\\.\\d{1,8}$"
          type: "string"
          description: "Central latitude coordinate of the bound... Pattern: ^-?\\\
            d{1,2}\\.\\d{1,8}$ (Must be a valid latitude value.)"
        center_longitude:
          pattern: "^-?\\d{1,3}\\.\\d{1,8}$"
          type: "string"
          description: "Central longitude coordinate of the boun... Pattern: ^-?\\\
            d{1,3}\\.\\d{1,8}$ (Must be a valid longitude value.)"
      description: "nullable"
    LocationTypes:
      type: "string"
      description: "types of locations."
      enum:
      - "BOROUGH"
      - "PARISH"
      - "REGION"
      - "BOUNDARY"
      - "PROVINCE"
      - "VILLAGE"
      - "STATE"
      - "CITY"
      - "COUNTRY"
      - "LOCALITY"
      - "POSTAL"
      - "STREET"
      - "SUB_ADMIN_AREA"
      - "SUB_LOCALITY"
      - "FEDERAL"
      - "COUNTY"
      - "TELEMATICS"
      - "ADDRESS"
      - "NO_PREFERENCE"
      - "GPS"
      - "WAREHOUSE"
      - "DISTRICT"
    UnitOfMeasureTypes:
      type: "string"
      description: "types of unit of measures."
      enum:
      - "MILES"
      - "KM"
      - "GALLON"
      - "LITER"
      - "METER"
      - "QUARTER"
      - "OZ"
      - "LB"
      - "DATE_TIME"
      - "DATE"
      - "KG"
      - "DURATION"
      - "CURRENCY"
      - "POINTS"
      - "MINUTES"
      - "HOURS"
      - "DAYS"
      - "WEEKS"
      - "DAY_OF_MONTH"
      - "BI_WEEKS"
      - "SEMI_MONTHS"
      - "MONTHS"
      - "QUARTERS"
      - "SEMI_YEARS"
      - "YEARS"
      - "MULTI_YEARS"
      - "OCCURRENCE"
      - "CELSIUS"
      - "FAHRENHEIT"
      - "KELVIN"
      - "RANKINE"
      - "INCH"
      - "FEET"
      - "YARD"
      - "FATHOM"
      - "NAUTICAL"
      - "BYTES"
      - "CUSTOM"
      - "UNLIMITED"
      - "NONE"
      - "PERCENT"
      - "STATE"
      - "CITY"
      - "COUNTRY"
      - "LOCALITY"
      - "POSTAL"
      - "STREET"
      - "SUB_ADMIN_AREA"
      - "SUB_LOCALITY"
      - "FEDERAL"
      - "COUNTY"
      - "DISTRICT"
      - "NA"
      - "UNIT"
      - "WATT"
      - "ITEM"
      - "NET"
      - "GROSS"
      - "MINIMUM"
      - "MAXIMUM"
      - "OTHER"
