---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    Codes:
      type: "array"
      description: "List of Codes"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    GeographicBoundary:
      type: "object"
      properties:
        geographic_boundary_id:
          maximum: 100
          minimum: 0
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier for the geographic boundary. Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
          nullable: false
          exampleSetFlag: false
        geographic_boundary_key:
          maximum: 100
          minimum: 0
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique business key for the geographic boundary. Pattern:\
            \ ^[a-zA-Z0-9_]+$ (Alphanumeric and underscores allowed)"
          nullable: false
          exampleSetFlag: false
        geographic_codes:
          description: "Codes representing geographic regions associated with the\
            \ boundary."
          $ref: "#/components/schemas/Codes"
          nullable: true
          exampleSetFlag: false
        locales:
          description: "Locale-specific information relevant to the geographic boundary."
          $ref: "#/components/schemas/Codes"
          nullable: true
          exampleSetFlag: false
        geographic_type:
          description: "Classification type of the geographic boundary (e.g., city,\
            \ region, polygon)."
          $ref: "#/components/schemas/LocationTypes"
          nullable: true
          exampleSetFlag: false
        geographic_values:
          description: "Specific values associated with the geographic boundary."
          $ref: "#/components/schemas/Codes"
          nullable: true
          exampleSetFlag: false
        distance_max:
          maxLength: 20
          pattern: "^[0-9.]+$"
          type: "string"
          description: "Maximum distance constraint applied in searches (as a string\
            \ value). Pattern: ^[0-9.]+$ (Must be a numeric value.)"
          nullable: true
          exampleSetFlag: false
        distance_min:
          maxLength: 20
          pattern: "^[0-9.]+$"
          type: "string"
          description: "Minimum distance constraint applied in searches (as a string\
            \ value). Pattern: ^[0-9.]+$ (Must be a numeric value.)"
          nullable: true
          exampleSetFlag: false
        distance_type:
          description: "Unit of measurement for distance constraints (e.g., miles,\
            \ kilometers)."
          $ref: "#/components/schemas/UnitOfMeasureTypes"
          nullable: true
          exampleSetFlag: false
        name:
          maxLength: 100
          minLength: 1
          type: "string"
          description: "Human-readable name of the geographic boundary."
          nullable: true
          exampleSetFlag: false
        vertices:
          maxLength: 2000
          type: "string"
          description: "Serialized coordinates defining polygon vertices (e.g., for\
            \ geo-fencing)."
          nullable: true
          exampleSetFlag: false
        description:
          maxLength: 255
          type: "string"
          description: "Detailed description of the geographic boundary."
          nullable: true
          exampleSetFlag: false
        center_latitude:
          pattern: "^-?\\d{1,2}\\.\\d{1,8}$"
          type: "string"
          description: "Central latitude coordinate of the boundary. Pattern: ^-?\\\
            d{1,2}\\.\\d{1,8}$ (Must be a valid latitude value.)"
          nullable: true
          exampleSetFlag: false
        center_longitude:
          pattern: "^-?\\d{1,3}\\.\\d{1,8}$"
          type: "string"
          description: "Central longitude coordinate of the boundary. Pattern: ^-?\\\
            d{1,3}\\.\\d{1,8}$ (Must be a valid longitude value.)"
          nullable: true
          exampleSetFlag: false
      description: "nullable"
      exampleSetFlag: false
    GeographicBoundaryCreate:
      required:
      - "geographic_boundary_key"
      type: "object"
      description: "GeographicBoundary Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/GeographicBoundary"
        exampleSetFlag: false
    GeographicBoundaryUpdate:
      type: "object"
      properties:
        center_latitude:
          pattern: "^-?\\d{1,2}\\.\\d{1,8}$"
          type: "string"
          description: "Central latitude coordinate of the boundary. Pattern: ^-?\\\
            d{1,2}\\.\\d{1,8}$ (Must be a valid latitude value.)"
          nullable: true
          exampleSetFlag: false
        center_longitude:
          pattern: "^-?\\d{1,3}\\.\\d{1,8}$"
          type: "string"
          description: "Central longitude coordinate of the boundary. Pattern: ^-?\\\
            d{1,3}\\.\\d{1,8}$ (Must be a valid longitude value.)"
          nullable: true
          exampleSetFlag: false
        geographic_codes:
          description: "Codes representing geographic regions associated with the\
            \ boundary."
          $ref: "#/components/schemas/Codes"
          nullable: true
          exampleSetFlag: false
        locales:
          description: "Locale-specific information relevant to the geographic boundary."
          $ref: "#/components/schemas/Codes"
          nullable: true
          exampleSetFlag: false
        geographic_type:
          description: "Classification type of the geographic boundary (e.g., city,\
            \ region, polygon)."
          $ref: "#/components/schemas/LocationTypes"
          nullable: true
          exampleSetFlag: false
        distance_min:
          maxLength: 20
          pattern: "^[0-9.]+$"
          type: "string"
          description: "Minimum distance constraint applied in searches (as a string\
            \ value). Pattern: ^[0-9.]+$ (Must be a numeric value.)"
          nullable: true
          exampleSetFlag: false
        distance_type:
          description: "Unit of measurement for distance constraints (e.g., miles,\
            \ kilometers)."
          $ref: "#/components/schemas/UnitOfMeasureTypes"
          nullable: true
          exampleSetFlag: false
        vertices:
          maxLength: 2000
          type: "string"
          description: "Serialized coordinates defining polygon vertices (e.g., for\
            \ geo-fencing)."
          nullable: true
          exampleSetFlag: false
        geographic_values:
          description: "Specific values associated with the geographic boundary."
          $ref: "#/components/schemas/Codes"
          nullable: true
          exampleSetFlag: false
        distance_max:
          maxLength: 20
          pattern: "^[0-9.]+$"
          type: "string"
          description: "Maximum distance constraint applied in searches (as a string\
            \ value). Pattern: ^[0-9.]+$ (Must be a numeric value.)"
          nullable: true
          exampleSetFlag: false
        name:
          maxLength: 100
          minLength: 1
          type: "string"
          description: "Human-readable name of the geographic boundary."
          nullable: true
          exampleSetFlag: false
        description:
          maxLength: 255
          type: "string"
          description: "Detailed description of the geographic boundary."
          nullable: true
          exampleSetFlag: false
      description: "GeographicBoundary Update for Patch and Put"
      exampleSetFlag: false
    Link:
      type: "array"
      description: "Quick Link"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    Links:
      type: "array"
      description: "List of Links"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    LocationTypes:
      type: "string"
      description: "types of locations."
      exampleSetFlag: false
      enum:
      - "BOROUGH"
      - "PARISH"
      - "REGION"
      - "BOUNDARY"
      - "PROVINCE"
      - "VILLAGE"
      - "STATE"
      - "CITY"
      - "COUNTRY"
      - "LOCALITY"
      - "POSTAL"
      - "STREET"
      - "SUB_ADMIN_AREA"
      - "SUB_LOCALITY"
      - "FEDERAL"
      - "COUNTY"
      - "TELEMATICS"
      - "ADDRESS"
      - "NO_PREFERENCE"
      - "GPS"
      - "WAREHOUSE"
      - "DISTRICT"
    UnitOfMeasureTypes:
      type: "string"
      description: "types of unit of measures."
      exampleSetFlag: false
      enum:
      - "MILES"
      - "KM"
      - "GALLON"
      - "LITER"
      - "METER"
      - "QUARTER"
      - "OZ"
      - "LB"
      - "DATE_TIME"
      - "DATE"
      - "KG"
      - "DURATION"
      - "CURRENCY"
      - "POINTS"
      - "MINUTES"
      - "HOURS"
      - "DAYS"
      - "WEEKS"
      - "DAY_OF_MONTH"
      - "BI_WEEKS"
      - "SEMI_MONTHS"
      - "MONTHS"
      - "QUARTERS"
      - "SEMI_YEARS"
      - "YEARS"
      - "MULTI_YEARS"
      - "OCCURRENCE"
      - "CELSIUS"
      - "FAHRENHEIT"
      - "KELVIN"
      - "RANKINE"
      - "INCH"
      - "FEET"
      - "YARD"
      - "FATHOM"
      - "NAUTICAL"
      - "BYTES"
      - "CUSTOM"
      - "UNLIMITED"
      - "NONE"
      - "PERCENT"
      - "STATE"
      - "CITY"
      - "COUNTRY"
      - "LOCALITY"
      - "POSTAL"
      - "STREET"
      - "SUB_ADMIN_AREA"
      - "SUB_LOCALITY"
      - "FEDERAL"
      - "COUNTY"
      - "DISTRICT"
      - "NA"
      - "UNIT"
      - "WATT"
      - "ITEM"
      - "NET"
      - "GROSS"
      - "MINIMUM"
      - "MAXIMUM"
      - "OTHER"
