---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths:
  /geographic-boundaries:
    get:
      tags:
      - "GeographicBoundary"
      summary: "Retrieve a list of all GeographicBoundary records."
      operationId: "listGeographicBoundarys"
      parameters:
      - name: "limit"
        in: "query"
        description: "Maximum number of records to return."
        schema:
          maximum: 100
          minimum: 1
          type: "integer"
          exampleSetFlag: false
          default: 50
      - name: "cursor"
        in: "query"
        description: "starting point for next set of results"
        schema:
          type: "string"
          exampleSetFlag: false
      responses:
        "200":
          description: "A list of GeographicBoundary records."
          content:
            application/json:
              schema:
                type: "array"
                exampleSetFlag: false
                items:
                  $ref: "#/components/schemas/GeographicBoundary"
                  exampleSetFlag: false
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"
    post:
      tags:
      - "GeographicBoundary"
      summary: "Create a new GeographicBoundary record."
      operationId: "createGeographicBoundary"
      requestBody:
        description: "GeographicBoundary data to create the new resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GeographicBoundary_Create"
              exampleSetFlag: false
        required: true
      responses:
        "201":
          description: "GeographicBoundary created successfully."
          headers:
            Location:
              description: "The URI of the newly created resource."
              schema:
                type: "string"
                example: "//geographic-boundaries/PR-1234567"
                exampleSetFlag: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeographicBoundary"
                exampleSetFlag: false
        "400":
          $ref: "#/components/responses/BadRequestError"
        "409":
          $ref: "#/components/responses/ConflictError"
  /geographic-boundaries/{geographicBoundaryKey}:
    get:
      tags:
      - "GeographicBoundary"
      summary: "Retrieve a specific GeographicBoundary record."
      operationId: "getGeographicBoundaryById"
      responses:
        "200":
          description: "The requested GeographicBoundary record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeographicBoundary"
                exampleSetFlag: false
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    put:
      tags:
      - "GeographicBoundary"
      summary: "replace a GeographicBoundary record."
      operationId: "replaceGeographicBoundary"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GeographicBoundary"
              exampleSetFlag: false
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeographicBoundary"
                exampleSetFlag: false
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    delete:
      tags:
      - "GeographicBoundary"
      summary: "Delete a GeographicBoundary Record"
      description: "Marks the GeographicBoundary record as inactive or removes it\
        \ entirely."
      operationId: "deleteGeographicBoundaryRecord"
      responses:
        "204":
          description: "Record successfully deleted (or deactivated)."
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    patch:
      tags:
      - "GeographicBoundary"
      summary: "Partially update a GeographicBoundary record."
      operationId: "updateGeographicBoundary"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GeographicBoundary_Update"
              exampleSetFlag: false
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeographicBoundary"
                exampleSetFlag: false
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    parameters:
    - name: "geographicBoundaryKey"
      in: "path"
      description: "The unique identifier for the specific GeographicBoundary."
      required: true
      schema:
        type: "string"
        example: "PR-1234567"
        exampleSetFlag: true
components:
  schemas: {}
