---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    BudgetVarianceLineItem:
      type: "object"
      properties:
        budget_variance_line_item_id:
          type: "string"
          description: "The unique ID for the report line item."
          exampleSetFlag: false
        budget_variance_line_item_key:
          type: "string"
          description: "The unique ID for the report line item."
          exampleSetFlag: false
        general_ledger_account:
          $ref: "#/components/schemas/GeneralLedgerReference"
          exampleSetFlag: false
        control_account:
          $ref: "#/components/schemas/ControlAccountReference"
          exampleSetFlag: false
        financial_category_type:
          $ref: "#/components/schemas/FinancialCategoryTypes"
          exampleSetFlag: false
        budgeted_amount:
          $ref: "#/components/schemas/Money"
          exampleSetFlag: false
        actual_amount:
          $ref: "#/components/schemas/Money"
          exampleSetFlag: false
        variance_details:
          $ref: "#/components/schemas/VarianceDetails"
          exampleSetFlag: false
      description: "A line item within a Budget Variance Report, comparing budgeted\
        \ versus actual amounts for a specific account/category."
      exampleSetFlag: false
    BudgetVarianceLineItemCreate:
      required:
      - "budget_variance_line_item_key"
      type: "object"
      description: "BudgetVarianceLineItem Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/BudgetVarianceLineItem"
        exampleSetFlag: false
    BudgetVarianceLineItemUpdate:
      type: "object"
      properties:
        variance_details:
          $ref: "#/components/schemas/VarianceDetails"
          exampleSetFlag: false
        budgeted_amount:
          $ref: "#/components/schemas/Money"
          exampleSetFlag: false
        actual_amount:
          $ref: "#/components/schemas/Money"
          exampleSetFlag: false
        general_ledger_account:
          $ref: "#/components/schemas/GeneralLedgerReference"
          exampleSetFlag: false
        control_account:
          $ref: "#/components/schemas/ControlAccountReference"
          exampleSetFlag: false
        financial_category_type:
          $ref: "#/components/schemas/FinancialCategoryTypes"
          exampleSetFlag: false
      description: "BudgetVarianceLineItem Update for Patch and Put"
      exampleSetFlag: false
    Codes:
      type: "array"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    ControlAccountReference:
      type: "object"
      properties:
        control_account_reference_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        control_account_reference_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        control_account_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          exampleSetFlag: false
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
        control_account:
          $ref: "#/components/schemas/Identifier"
          exampleSetFlag: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the event occurred."
          format: "date-time"
          exampleSetFlag: false
      description: "External system identifier"
      exampleSetFlag: false
    ControlAccountReferenceCreate:
      required:
      - "control_account_reference_key"
      type: "object"
      description: "ControlAccountReference Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/ControlAccountReference"
        exampleSetFlag: false
    ControlAccountReferenceUpdate:
      type: "object"
      properties:
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          exampleSetFlag: false
        control_account:
          $ref: "#/components/schemas/Identifier"
          exampleSetFlag: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the event occurred."
          format: "date-time"
          exampleSetFlag: false
      description: "ControlAccountReference Update for Patch and Put"
      exampleSetFlag: false
    FinancialCategoryTypes:
      type: "string"
      description: "types of financial categorys."
      exampleSetFlag: false
      enum:
      - "CAPEX"
      - "OPEX"
      - "HARDWARE"
      - "SOFTWARE"
      - "MAINTENANCE"
      - "TRAVEL"
      - "TRAINING"
      - "UTILITIES"
      - "RENT"
      - "SALARY"
      - "REVENUE"
      - "TAX"
      - "OTHER"
    GeneralLedgerReference:
      type: "object"
      properties:
        general_ledger_reference_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique reference value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        general_ledger_reference_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique reference value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        general_ledger_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique reference value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the reference"
          exampleSetFlag: false
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
        general_ledger_identifier:
          $ref: "#/components/schemas/Identifier"
          exampleSetFlag: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the event occurred."
          format: "date-time"
          exampleSetFlag: false
      description: "External system reference"
      exampleSetFlag: false
    GeneralLedgerReferenceCreate:
      required:
      - "general_ledger_reference_key"
      type: "object"
      description: "GeneralLedgerReference Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/GeneralLedgerReference"
        exampleSetFlag: false
    GeneralLedgerReferenceUpdate:
      type: "object"
      properties:
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
        general_ledger_identifier:
          $ref: "#/components/schemas/Identifier"
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the reference"
          exampleSetFlag: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the event occurred."
          format: "date-time"
          exampleSetFlag: false
      description: "GeneralLedgerReference Update for Patch and Put"
      exampleSetFlag: false
    Identifier:
      type: "object"
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        identifier_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Business key for the identifier Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          exampleSetFlag: false
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
      description: "External system identifier"
      exampleSetFlag: false
    IdentifierCreate:
      required:
      - "identifier_key"
      type: "object"
      description: "Identifier Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/Identifier"
        exampleSetFlag: false
    IdentifierUpdate:
      type: "object"
      properties:
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          exampleSetFlag: false
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
      description: "Identifier Update for Patch and Put"
      exampleSetFlag: false
    Money:
      type: "object"
      properties:
        money_key:
          type: "string"
          description: "The unique key for the monetary value."
          exampleSetFlag: false
        money_id:
          type: "string"
          description: "The unique ID for the monetary value."
          exampleSetFlag: false
        currency_code:
          type: "string"
          description: "ISO currency code, e.g., 'USD'."
          exampleSetFlag: false
        display_value:
          type: "string"
          description: "The locale-specific display format for t..."
          exampleSetFlag: false
        locale:
          type: "string"
          description: "The locale code (e.g., en-US, fr-FR)."
          exampleSetFlag: false
        value:
          type: "string"
          description: "The monetary value."
          exampleSetFlag: false
      description: "Represents a monetary value, including its currency, locale, and\
        \ display format."
      exampleSetFlag: false
    VarianceDetails:
      type: "object"
      properties:
        variance_amount:
          $ref: "#/components/schemas/Money"
          exampleSetFlag: false
        variance_percentage:
          type: "string"
          description: "The variance expressed as a percentage o..."
          exampleSetFlag: false
        is_favorable:
          type: "boolean"
          description: "Indicator if the variance is favorable (..."
          exampleSetFlag: false
      description: "Details the calculated variance between an actual amount and a\
        \ budgeted amount."
      exampleSetFlag: false
    VarianceDetailsCreate:
      required:
      - "variance_details_key"
      type: "object"
      description: "VarianceDetails Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/VarianceDetails"
        exampleSetFlag: false
    VarianceDetailsUpdate:
      type: "object"
      properties:
        variance_amount:
          $ref: "#/components/schemas/Money"
          exampleSetFlag: false
        variance_percentage:
          type: "string"
          description: "The variance expressed as a percentage o..."
          exampleSetFlag: false
        is_favorable:
          type: "boolean"
          description: "Indicator if the variance is favorable (..."
          exampleSetFlag: false
      description: "VarianceDetails Update for Patch and Put"
      exampleSetFlag: false
