---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths:
  /payments:
    get:
      tags:
      - "Payment"
      summary: "Retrieve a list of all Payment records."
      operationId: "listPayments"
      parameters:
      - name: "limit"
        in: "query"
        description: "Maximum number of records to return."
        schema:
          maximum: 100
          minimum: 1
          type: "integer"
          exampleSetFlag: false
          default: 50
      - name: "cursor"
        in: "query"
        description: "starting point for next set of results"
        schema:
          type: "string"
          exampleSetFlag: false
      responses:
        "200":
          description: "A list of Payment records."
          content:
            application/json:
              schema:
                type: "array"
                exampleSetFlag: false
                items:
                  $ref: "#/components/schemas/Payment"
                  exampleSetFlag: false
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"
    post:
      tags:
      - "Payment"
      summary: "Create a new Payment record."
      operationId: "createPayment"
      requestBody:
        description: "Payment data to create the new resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Payment_Create"
              exampleSetFlag: false
        required: true
      responses:
        "201":
          description: "Payment created successfully."
          headers:
            Location:
              description: "The URI of the newly created resource."
              schema:
                type: "string"
                example: "//payments/PR-1234567"
                exampleSetFlag: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Payment"
                exampleSetFlag: false
        "400":
          $ref: "#/components/responses/BadRequestError"
        "409":
          $ref: "#/components/responses/ConflictError"
  /payments/{paymentKey}:
    get:
      tags:
      - "Payment"
      summary: "Retrieve a specific Payment record."
      operationId: "getPaymentById"
      responses:
        "200":
          description: "The requested Payment record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Payment"
                exampleSetFlag: false
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    put:
      tags:
      - "Payment"
      summary: "replace a Payment record."
      operationId: "replacePayment"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Payment"
              exampleSetFlag: false
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Payment"
                exampleSetFlag: false
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    delete:
      tags:
      - "Payment"
      summary: "Delete a Payment Record"
      description: "Marks the Payment record as inactive or removes it entirely."
      operationId: "deletePaymentRecord"
      responses:
        "204":
          description: "Record successfully deleted (or deactivated)."
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    patch:
      tags:
      - "Payment"
      summary: "Partially update a Payment record."
      operationId: "updatePayment"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Payment_Update"
              exampleSetFlag: false
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Payment"
                exampleSetFlag: false
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    parameters:
    - name: "paymentKey"
      in: "path"
      description: "The unique identifier for the specific Payment."
      required: true
      schema:
        type: "string"
        example: "PR-1234567"
        exampleSetFlag: true
  /payments/{paymentKey}/payment-transactions:
    get:
      tags:
      - "PaymentTransaction"
      summary: "Retrieve a list of all PaymentTransaction records."
      operationId: "listPaymentTransactions"
      parameters:
      - name: "limit"
        in: "query"
        description: "Maximum number of records to return."
        schema:
          maximum: 100
          minimum: 1
          type: "integer"
          exampleSetFlag: false
          default: 50
      - name: "cursor"
        in: "query"
        description: "starting point for next set of results"
        schema:
          type: "string"
          exampleSetFlag: false
      responses:
        "200":
          description: "A list of PaymentTransaction records."
          content:
            application/json:
              schema:
                type: "array"
                exampleSetFlag: false
                items:
                  $ref: "#/components/schemas/PaymentTransaction"
                  exampleSetFlag: false
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"
    post:
      tags:
      - "PaymentTransaction"
      summary: "Create a new PaymentTransaction record."
      operationId: "createPaymentTransaction"
      requestBody:
        description: "PaymentTransaction data to create the new resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentTransaction_Create"
              exampleSetFlag: false
        required: true
      responses:
        "201":
          description: "PaymentTransaction created successfully."
          headers:
            Location:
              description: "The URI of the newly created resource."
              schema:
                type: "string"
                example: "//payments/{paymentKey}/payment-transactions/PR-1234567"
                exampleSetFlag: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentTransaction"
                exampleSetFlag: false
        "400":
          $ref: "#/components/responses/BadRequestError"
        "409":
          $ref: "#/components/responses/ConflictError"
  /payments/{paymentKey}/payment-transactions/{paymentTransactionKey}:
    get:
      tags:
      - "PaymentTransaction"
      summary: "Retrieve a specific PaymentTransaction record."
      operationId: "getPaymentTransactionById"
      responses:
        "200":
          description: "The requested PaymentTransaction record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentTransaction"
                exampleSetFlag: false
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    put:
      tags:
      - "PaymentTransaction"
      summary: "replace a PaymentTransaction record."
      operationId: "replacePaymentTransaction"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentTransaction"
              exampleSetFlag: false
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentTransaction"
                exampleSetFlag: false
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    delete:
      tags:
      - "PaymentTransaction"
      summary: "Delete a PaymentTransaction Record"
      description: "Marks the PaymentTransaction record as inactive or removes it\
        \ entirely."
      operationId: "deletePaymentTransactionRecord"
      responses:
        "204":
          description: "Record successfully deleted (or deactivated)."
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    patch:
      tags:
      - "PaymentTransaction"
      summary: "Partially update a PaymentTransaction record."
      operationId: "updatePaymentTransaction"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentTransaction_Update"
              exampleSetFlag: false
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentTransaction"
                exampleSetFlag: false
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    parameters:
    - name: "paymentTransactionKey"
      in: "path"
      description: "The unique identifier for the specific PaymentTransaction."
      required: true
      schema:
        type: "string"
        example: "PR-1234567"
        exampleSetFlag: true
  /payments/{paymentKey}/moneys:
    get:
      tags:
      - "Money"
      summary: "Retrieve a list of all Money records."
      operationId: "listMoneys"
      parameters:
      - name: "limit"
        in: "query"
        description: "Maximum number of records to return."
        schema:
          maximum: 100
          minimum: 1
          type: "integer"
          exampleSetFlag: false
          default: 50
      - name: "cursor"
        in: "query"
        description: "starting point for next set of results"
        schema:
          type: "string"
          exampleSetFlag: false
      responses:
        "200":
          description: "A list of Money records."
          content:
            application/json:
              schema:
                type: "array"
                exampleSetFlag: false
                items:
                  $ref: "#/components/schemas/Money"
                  exampleSetFlag: false
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"
  /payments/{paymentKey}/moneys/{moneyKey}:
    get:
      tags:
      - "Money"
      summary: "Retrieve a specific Money record."
      operationId: "getMoneyById"
      responses:
        "200":
          description: "The requested Money record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Money"
                exampleSetFlag: false
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    put:
      tags:
      - "Money"
      summary: "replace a Money record."
      operationId: "replaceMoney"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Money"
              exampleSetFlag: false
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Money"
                exampleSetFlag: false
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    parameters:
    - name: "moneyKey"
      in: "path"
      description: "The unique identifier for the specific Money."
      required: true
      schema:
        type: "string"
        example: "PR-1234567"
        exampleSetFlag: true
  /payments/{paymentKey}/payment-method-references:
    get:
      tags:
      - "PaymentMethodReference"
      summary: "Retrieve a list of all PaymentMethodReference records."
      operationId: "listPaymentMethodReferences"
      parameters:
      - name: "limit"
        in: "query"
        description: "Maximum number of records to return."
        schema:
          maximum: 100
          minimum: 1
          type: "integer"
          exampleSetFlag: false
          default: 50
      - name: "cursor"
        in: "query"
        description: "starting point for next set of results"
        schema:
          type: "string"
          exampleSetFlag: false
      responses:
        "200":
          description: "A list of PaymentMethodReference records."
          content:
            application/json:
              schema:
                type: "array"
                exampleSetFlag: false
                items:
                  $ref: "#/components/schemas/PaymentMethodReference"
                  exampleSetFlag: false
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"
    post:
      tags:
      - "PaymentMethodReference"
      summary: "Create a new PaymentMethodReference record."
      operationId: "createPaymentMethodReference"
      requestBody:
        description: "PaymentMethodReference data to create the new resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentMethodReference_Create"
              exampleSetFlag: false
        required: true
      responses:
        "201":
          description: "PaymentMethodReference created successfully."
          headers:
            Location:
              description: "The URI of the newly created resource."
              schema:
                type: "string"
                example: "//payments/{paymentKey}/payment-method-references/PR-1234567"
                exampleSetFlag: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentMethodReference"
                exampleSetFlag: false
        "400":
          $ref: "#/components/responses/BadRequestError"
        "409":
          $ref: "#/components/responses/ConflictError"
  /payments/{paymentKey}/payment-method-references/{paymentMethodReferenceKey}:
    get:
      tags:
      - "PaymentMethodReference"
      summary: "Retrieve a specific PaymentMethodReference record."
      operationId: "getPaymentMethodReferenceById"
      responses:
        "200":
          description: "The requested PaymentMethodReference record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentMethodReference"
                exampleSetFlag: false
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    put:
      tags:
      - "PaymentMethodReference"
      summary: "replace a PaymentMethodReference record."
      operationId: "replacePaymentMethodReference"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentMethodReference"
              exampleSetFlag: false
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentMethodReference"
                exampleSetFlag: false
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    delete:
      tags:
      - "PaymentMethodReference"
      summary: "Delete a PaymentMethodReference Record"
      description: "Marks the PaymentMethodReference record as inactive or removes\
        \ it entirely."
      operationId: "deletePaymentMethodReferenceRecord"
      responses:
        "204":
          description: "Record successfully deleted (or deactivated)."
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    patch:
      tags:
      - "PaymentMethodReference"
      summary: "Partially update a PaymentMethodReference record."
      operationId: "updatePaymentMethodReference"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentMethodReference_Update"
              exampleSetFlag: false
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentMethodReference"
                exampleSetFlag: false
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    parameters:
    - name: "paymentMethodReferenceKey"
      in: "path"
      description: "The unique identifier for the specific PaymentMethodReference."
      required: true
      schema:
        type: "string"
        example: "PR-1234567"
        exampleSetFlag: true
components:
  schemas: {}
