---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    Codes:
      type: "array"
      description: "List of Codes"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    Identifier:
      type: "object"
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          nullable: false
          exampleSetFlag: false
        identifier_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Business key for the identifier Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          nullable: false
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          nullable: true
          exampleSetFlag: false
        value:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
          exampleSetFlag: false
        detail:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
          exampleSetFlag: false
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
          exampleSetFlag: false
        system_codes:
          description: "Associated system codes for this identifier"
          $ref: "#/components/schemas/Codes"
          nullable: true
          exampleSetFlag: false
      description: "External system identifier"
      exampleSetFlag: false
    IdentifierCreate:
      required:
      - "identifier_key"
      type: "object"
      description: "Identifier Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/Identifier"
        exampleSetFlag: false
    IdentifierUpdate:
      type: "object"
      properties:
        system_codes:
          description: "Associated system codes for this identifier"
          $ref: "#/components/schemas/Codes"
          nullable: true
          exampleSetFlag: false
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          nullable: true
          exampleSetFlag: false
        detail:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
          exampleSetFlag: false
        value:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
          exampleSetFlag: false
      description: "Identifier Update for Patch and Put"
      exampleSetFlag: false
    Link:
      type: "array"
      description: "Quick Link"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    Links:
      type: "array"
      description: "List of Links"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    Money:
      type: "object"
      properties:
        money_key:
          type: "string"
          description: "The unique key for the monetary value."
          nullable: false
          exampleSetFlag: false
        money_id:
          type: "string"
          description: "The unique ID for the monetary value."
          nullable: false
          exampleSetFlag: false
        currency_code:
          type: "string"
          description: "ISO currency code, e.g., 'USD'."
          nullable: false
          exampleSetFlag: false
        display_value:
          type: "string"
          description: "The locale-specific display format for the value (e.g., $1,234.56)."
          nullable: false
          exampleSetFlag: false
        locale:
          type: "string"
          description: "The locale code (e.g., en-US, fr-FR)."
          nullable: false
          exampleSetFlag: false
        value:
          type: "string"
          description: "The monetary value."
          nullable: false
          exampleSetFlag: false
      description: "Represents a monetary value, including its currency, locale, and\
        \ display format."
      exampleSetFlag: false
    Payment:
      type: "object"
      properties:
        payment_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value for the reference record. Pattern:\
            \ ^[a-zA-Z0-9_]+$ (Alphanumeric and underscores allowed)"
          nullable: false
          exampleSetFlag: false
        payment_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique key value for the reference record. Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
          nullable: false
          exampleSetFlag: false
        payment_transactions:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          description: "The unique key identifying the referenced PaymentMethod (Party)\
            \ aggregate. Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric and underscores allowed)"
          $ref: "#/components/schemas/PaymentTransactions"
          nullable: false
          exampleSetFlag: false
        target_amount:
          description: "The monetary or hours-based amount of the event."
          $ref: "#/components/schemas/Money"
          nullable: false
          exampleSetFlag: false
        payment_status_type:
          description: "The status of the payment."
          $ref: "#/components/schemas/PaymentStatusTypes"
          nullable: false
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the reference."
          nullable: true
          exampleSetFlag: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the payment was associated with the order."
          format: "date-time"
          nullable: false
          exampleSetFlag: false
      description: "Reference to a PaymentMethod (Party) Aggregate Root for financing\
        \ details."
      exampleSetFlag: false
    PaymentAmountTypes:
      type: "string"
      description: "types of payment amounts."
      exampleSetFlag: false
      enum:
      - "PARTIAL_REFUND"
      - "TOTAL_REFUND"
      - "TOTAL_INTEREST"
      - "TOTAL_PAYMENT"
      - "TOTAL_PRINCIPAL"
      - "TOTAL_FINANCED"
      - "DOWN_PAYMENT"
      - "TRADE_IN_ALLOWANCE"
      - "CREDIT_CARD_PAYMENT"
      - "CASH_PAYMENT"
      - "CHECK_PAYMENT"
      - "EFT_PAYMENT"
      - "PAYMENT_EVENT"
      - "SCHEDULED_PAYMENT_EVENT"
      - "BASE_PAYMENT_EVENT"
      - "DESIRED_PAYMENT"
      - "ADMIN_FEE"
      - "GOVERNMENT_FEE"
      - "SERVICE_FEE"
      - "LATE_FEE"
      - "PAYROLL"
      - "OTHER"
    PaymentCreate:
      required:
      - "payment_key"
      type: "object"
      description: "Payment Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/Payment"
        exampleSetFlag: false
    PaymentMethodReference:
      type: "object"
      properties:
        payment_method_reference_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value for the reference record. Pattern:\
            \ ^[a-zA-Z0-9_]+$ (Alphanumeric and underscores allowed)"
          nullable: false
          exampleSetFlag: false
        payment_method_reference_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique key value for the reference record. Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
          nullable: false
          exampleSetFlag: false
        payment_method_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "The unique key identifying the referenced PaymentMethod (Party)\
            \ aggregate. Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric and underscores allowed)"
          nullable: false
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the reference."
          nullable: true
          exampleSetFlag: false
        payment_method_type:
          description: "Type of payment method used for the transaction (e.g., CREDIT_CARD,\
            \ ACH)."
          $ref: "#/components/schemas/PaymentMethodTypes"
          nullable: false
          example: "CREDIT_CARD"
          exampleSetFlag: true
        processor_options:
          description: "Details of the PaymentMethod reference."
          $ref: "#/components/schemas/Identifier"
          nullable: false
          exampleSetFlag: false
        snapshot_details:
          description: "Details of the PaymentMethod reference."
          $ref: "#/components/schemas/Identifier"
          nullable: false
          exampleSetFlag: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the paymentMethod was associated with the\
            \ order."
          format: "date-time"
          nullable: false
          exampleSetFlag: false
      description: "Reference to a PaymentMethod (Party) Aggregate Root for financing\
        \ details."
      exampleSetFlag: false
    PaymentMethodReferenceCreate:
      required:
      - "payment_method_reference_key"
      type: "object"
      description: "PaymentMethodReference Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/PaymentMethodReference"
        exampleSetFlag: false
    PaymentMethodReferenceUpdate:
      type: "object"
      properties:
        payment_method_type:
          description: "Type of payment method used for the transaction (e.g., CREDIT_CARD,\
            \ ACH)."
          $ref: "#/components/schemas/PaymentMethodTypes"
          nullable: false
          example: "CREDIT_CARD"
          exampleSetFlag: true
        processor_options:
          description: "Details of the PaymentMethod reference."
          $ref: "#/components/schemas/Identifier"
          nullable: false
          exampleSetFlag: false
        snapshot_details:
          description: "Details of the PaymentMethod reference."
          $ref: "#/components/schemas/Identifier"
          nullable: false
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the reference."
          nullable: true
          exampleSetFlag: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the paymentMethod was associated with the\
            \ order."
          format: "date-time"
          nullable: false
          exampleSetFlag: false
      description: "PaymentMethodReference Update for Patch and Put"
      exampleSetFlag: false
    PaymentMethodTypes:
      type: "string"
      description: "types of payment methods."
      exampleSetFlag: false
      enum:
      - "CASH"
      - "CHECK"
      - "MONEY_ORDER"
      - "CASH_ON_DELIVERY"
      - "CREDIT_CARD"
      - "DEBIT_CARD"
      - "GIFT_CARD"
      - "EFT"
      - "ONLINE_BANK_TRANSFER"
      - "MOBILE_WALLET"
      - "CRYPTOCURRENCY"
      - "ONLINE_PAYMENT_PLATFORM"
      - "PAYROLL_DEDUCTION"
      - "FINANCE"
      - "LEASE"
      - "RENTAL"
      - "TERMS"
      - "DUE_ON_RECEIPT"
      - "TRADE_IN"
      - "REWARD_POINTS"
      - "STORE_CREDIT"
      - "EXCHANGE"
      - "OTHER"
      - "NOT_APPLICABLE"
    PaymentStatusTypes:
      type: "string"
      description: "types of payment status."
      exampleSetFlag: false
      enum:
      - "CREATED"
      - "PENDING"
      - "PROCESSING"
      - "PROCESSED"
      - "COMPLETED"
      - "SUCCEEDED"
      - "PAID"
      - "REJECTED"
      - "SCHEDULED"
      - "SUBMITTED"
      - "DEFERRED"
      - "DEFERRED_INTERNAL"
      - "CLEARED"
      - "FRAUD_REVIEW"
      - "APPROVED"
      - "ACCEPTED"
      - "REQUIRES_ACTION"
      - "REQUIRES_PAYMENT_STATUS"
      - "AUTO_SCHEDULED"
      - "AUTO_INITIATED"
      - "MANUAL_INITIATED"
      - "PENDING_PAYER_FUNDS"
      - "FAILED"
      - "DENIED"
      - "EXPIRED"
      - "CANCELLED"
      - "VOIDED"
      - "REVERSED"
      - "REFUNDED"
      - "PAYROLL_PENDING"
      - "PAYROLL_FINALIZED"
      - "ACTIVE"
      - "INACTIVE"
      - "FUNDED"
      - "RETURNED"
    PaymentTransaction:
      type: "object"
      properties:
        payment_amount_key:
          type: "string"
          description: "A unique key for the payment amount."
          nullable: false
          exampleSetFlag: false
        payment_amount_id:
          type: "string"
          description: "A unique key for the payment amount."
          nullable: false
          exampleSetFlag: false
        payment_amount_type:
          description: "The type of payment amount (e.g., fee, premium, tax)."
          $ref: "#/components/schemas/PaymentAmountTypes"
          nullable: true
          exampleSetFlag: false
        payment_method_reference:
          description: "Details on the accepted methods of payment for this schedule."
          $ref: "#/components/schemas/PaymentMethodReference"
          nullable: true
          exampleSetFlag: false
        amount:
          description: "The monetary or hours-based amount of the event."
          $ref: "#/components/schemas/Money"
          nullable: false
          exampleSetFlag: false
        payment_transaction_status_type:
          description: "The status of the payment."
          $ref: "#/components/schemas/PaymentTransactionStatusTypes"
          nullable: false
          exampleSetFlag: false
      description: "Represents the type and value of a payment amount."
      exampleSetFlag: false
    PaymentTransactionCreate:
      required:
      - "payment_transaction_key"
      type: "object"
      description: "PaymentTransaction Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/PaymentTransaction"
        exampleSetFlag: false
    PaymentTransactionStatusTypes:
      type: "string"
      description: "types of payment transaction status."
      exampleSetFlag: false
      enum:
      - "NONE"
      - "EXPIRED"
      - "CAPTURED"
      - "CONFIRMATION"
      - "VOID"
      - "APPROVE"
      - "REFUNDED"
      - "PARTIALLY_REFUNDED"
      - "AUTHORIZE"
      - "PENDING_MERCHANT"
      - "SUSPENDED"
      - "OPEN"
      - "PEND"
      - "PROCESS"
      - "DECLINE"
      - "DUE"
      - "INCURRED"
      - "CUSTOM_CODE"
      - "USER_HOLD"
      - "ADMIN_HOLD"
      - "ACTIVATED"
      - "DEACTIVATE"
      - "CANCEL"
      - "CONFIRM"
      - "CLOSE"
      - "TRIAL"
      - "SUBSCRIPTION"
      - "OVERRIDE"
      - "UPGRADE"
      - "HOLD_ON_RENEWAL"
      - "HOLD_ON_DATE"
      - "PAYMENT"
      - "DOWNGRADE"
    PaymentTransactionUpdate:
      type: "object"
      properties:
        amount:
          description: "The monetary or hours-based amount of the event."
          $ref: "#/components/schemas/Money"
          nullable: false
          exampleSetFlag: false
        payment_transaction_status_type:
          description: "The status of the payment."
          $ref: "#/components/schemas/PaymentTransactionStatusTypes"
          nullable: false
          exampleSetFlag: false
        payment_method_reference:
          description: "Details on the accepted methods of payment for this schedule."
          $ref: "#/components/schemas/PaymentMethodReference"
          nullable: true
          exampleSetFlag: false
        payment_amount_type:
          description: "The type of payment amount (e.g., fee, premium, tax)."
          $ref: "#/components/schemas/PaymentAmountTypes"
          nullable: true
          exampleSetFlag: false
      description: "PaymentTransaction Update for Patch and Put"
      exampleSetFlag: false
    PaymentTransactions:
      type: "array"
      description: "List of PaymentTransaction"
      exampleSetFlag: false
      items:
        $ref: "#/components/schemas/PaymentTransaction"
        exampleSetFlag: false
    PaymentTransactionsCreate:
      type: "array"
      description: "PaymentTransactions Create for Post"
      exampleSetFlag: false
      items:
        $ref: "#/components/schemas/PaymentTransactions"
        exampleSetFlag: false
    PaymentTransactionsUpdate:
      type: "array"
      description: "PaymentTransactions Update for Patch and Put"
      exampleSetFlag: false
      items:
        $ref: "#/components/schemas/PaymentTransactions"
        exampleSetFlag: false
    PaymentUpdate:
      type: "object"
      properties:
        target_amount:
          description: "The monetary or hours-based amount of the event."
          $ref: "#/components/schemas/Money"
          nullable: false
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the reference."
          nullable: true
          exampleSetFlag: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the payment was associated with the order."
          format: "date-time"
          nullable: false
          exampleSetFlag: false
        payment_transactions:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          description: "The unique key identifying the referenced PaymentMethod (Party)\
            \ aggregate. Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric and underscores allowed)"
          $ref: "#/components/schemas/PaymentTransactions"
          nullable: false
          exampleSetFlag: false
        payment_status_type:
          description: "The status of the payment."
          $ref: "#/components/schemas/PaymentStatusTypes"
          nullable: false
          exampleSetFlag: false
      description: "Payment Update for Patch and Put"
      exampleSetFlag: false
