openapi: "3.0.1"
info:
  title: Repair Order API
  description: Repair Oder API to manage submission and status of a Repair Order
  version: "1.0"
paths:
  /repairorders:
    get:
      summary: Retrieve a list of repair orders
      operationId: getRepairOrders
      responses:
        "200":
          description: A list of repair orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RepairOrder"
    post:
      summary: Create a new repair order
      operationId: createRepairOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RepairOrder"
        required: true
      responses:
        "201":
          description: Repair order created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RepairOrder"
