---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    AccountingPeriod:
      type: "object"
      properties:
        identifiers:
          $ref: "#/components/schemas/Identifiers"
          exampleSetFlag: false
        period_desc:
          maxLength: 255
          type: "string"
          description: "Descriptive name for the accounting peri..."
          exampleSetFlag: false
        accounting_period_id:
          pattern: "^[0-9]{6}$"
          type: "string"
          description: "Business key for the accounting period (... Pattern: ^[0-9]{6}$\
            \ (Must be in YYYYMM format)"
          exampleSetFlag: false
        accounting_period_key:
          pattern: "^[0-9]{6}$"
          type: "string"
          description: "Business key for the accounting period (... Pattern: ^[0-9]{6}$\
            \ (Must be in YYYYMM format)"
          exampleSetFlag: false
        period_name:
          maxLength: 100
          type: "string"
          description: "Display name of the accounting period."
          exampleSetFlag: false
        start_date:
          type: "string"
          description: "The beginning date of the accounting per..."
          format: "date"
          exampleSetFlag: false
        end_date:
          type: "string"
          description: "The ending date of the accounting period..."
          format: "date"
          exampleSetFlag: false
        accounting_period_status_type:
          $ref: "#/components/schemas/AccountingPeriodStatusTypes"
          exampleSetFlag: false
        fiscal_year:
          type: "integer"
          description: "The fiscal year this period belongs to."
          format: "int32"
          exampleSetFlag: false
      description: "Defines a fiscal period, including its unique identifiers, start\
        \ and end dates, and current status."
      exampleSetFlag: false
    AccountingPeriodCreate:
      required:
      - "accounting_period_key"
      type: "object"
      description: "AccountingPeriod Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/AccountingPeriod"
        exampleSetFlag: false
    AccountingPeriodStatusTypes:
      type: "string"
      description: "types of accounting period status."
      exampleSetFlag: false
      enum:
      - "OPEN"
      - "ADJUSTMENT"
      - "CLOSED"
      - "FUTURE"
      - "PENDING_CLOSURE"
      - "LOCKED"
      - "OTHER"
    AccountingPeriodUpdate:
      type: "object"
      properties:
        end_date:
          type: "string"
          description: "The ending date of the accounting period..."
          format: "date"
          exampleSetFlag: false
        period_desc:
          maxLength: 255
          type: "string"
          description: "Descriptive name for the accounting peri..."
          exampleSetFlag: false
        fiscal_year:
          type: "integer"
          description: "The fiscal year this period belongs to."
          format: "int32"
          exampleSetFlag: false
        identifiers:
          $ref: "#/components/schemas/Identifiers"
          exampleSetFlag: false
        accounting_period_status_type:
          $ref: "#/components/schemas/AccountingPeriodStatusTypes"
          exampleSetFlag: false
        period_name:
          maxLength: 100
          type: "string"
          description: "Display name of the accounting period."
          exampleSetFlag: false
        start_date:
          type: "string"
          description: "The beginning date of the accounting per..."
          format: "date"
          exampleSetFlag: false
      description: "AccountingPeriod Update for Patch and Put"
      exampleSetFlag: false
    CashFlowLineItem:
      type: "object"
      properties:
        cash_flow_line_item_id:
          type: "string"
          description: "The unique key for the Cash Flow LineIte..."
          exampleSetFlag: false
        cash_flow_line_item_key:
          type: "string"
          description: "The unique key for the Cash Flow LineIte..."
          exampleSetFlag: false
        period_start_date:
          type: "string"
          description: "The start date of the reporting period f..."
          format: "date"
          exampleSetFlag: false
        period_end_date:
          type: "string"
          description: "The end date of the reporting period for..."
          format: "date"
          exampleSetFlag: false
        cash_inflow_total:
          $ref: "#/components/schemas/Money"
          exampleSetFlag: false
        cash_outflow_total:
          $ref: "#/components/schemas/Money"
          exampleSetFlag: false
        net_cash_flow:
          $ref: "#/components/schemas/Money"
          exampleSetFlag: false
        cash_balance_closing:
          $ref: "#/components/schemas/Money"
          exampleSetFlag: false
        source_category:
          type: "string"
          description: "The source type or category for this flo..."
          exampleSetFlag: false
      description: "Represents the aggregated expected cash flow for a single time\
        \ period (e.g., one week) within a projection."
      exampleSetFlag: false
    CashFlowLineItemCreate:
      required:
      - "cash_flow_line_item_key"
      type: "object"
      description: "CashFlowLineItem Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/CashFlowLineItem"
        exampleSetFlag: false
    CashFlowLineItemUpdate:
      type: "object"
      properties:
        net_cash_flow:
          $ref: "#/components/schemas/Money"
          exampleSetFlag: false
        period_end_date:
          type: "string"
          description: "The end date of the reporting period for..."
          format: "date"
          exampleSetFlag: false
        cash_balance_closing:
          $ref: "#/components/schemas/Money"
          exampleSetFlag: false
        period_start_date:
          type: "string"
          description: "The start date of the reporting period f..."
          format: "date"
          exampleSetFlag: false
        cash_outflow_total:
          $ref: "#/components/schemas/Money"
          exampleSetFlag: false
        source_category:
          type: "string"
          description: "The source type or category for this flo..."
          exampleSetFlag: false
        cash_inflow_total:
          $ref: "#/components/schemas/Money"
          exampleSetFlag: false
      description: "CashFlowLineItem Update for Patch and Put"
      exampleSetFlag: false
    CashFlowLineItems:
      type: "array"
      exampleSetFlag: false
      items:
        $ref: "#/components/schemas/CashFlowLineItem"
        exampleSetFlag: false
    CashFlowProjection:
      type: "object"
      properties:
        cash_flow_projection_key:
          type: "string"
          description: "The unique key for the Cash Flow Project..."
          exampleSetFlag: false
        cash_flow_projection_id:
          type: "string"
          description: "The unique key for the Cash Flow Project..."
          exampleSetFlag: false
        cash_flow_projection_criteria:
          $ref: "#/components/schemas/CashFlowProjectionCriteria"
          exampleSetFlag: false
        projection_date:
          type: "string"
          description: "The date the projection was generated."
          format: "date"
          exampleSetFlag: false
        cash_balance_opening:
          $ref: "#/components/schemas/Money"
          exampleSetFlag: false
        scenario:
          $ref: "#/components/schemas/CashFlowScenario"
          exampleSetFlag: false
        accounting_period:
          $ref: "#/components/schemas/AccountingPeriod"
          exampleSetFlag: false
        line_items:
          $ref: "#/components/schemas/CashFlowLineItems"
          exampleSetFlag: false
      description: "The final generated report representing the projected future cash\
        \ position based on a specific scenario and time horizon."
      exampleSetFlag: false
    CashFlowProjectionCreate:
      required:
      - "cash_flow_projection_key"
      type: "object"
      description: "CashFlowProjection Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/CashFlowProjection"
        exampleSetFlag: false
    CashFlowProjectionCriteria:
      type: "object"
      properties:
        budget_variance_report_request_id:
          type: "string"
          description: "The Accounting Period Key for which the ..."
          exampleSetFlag: false
        budget_variance_report_request_key:
          type: "string"
          description: "The Accounting Period Key for which the ..."
          exampleSetFlag: false
        period_granularity_type:
          $ref: "#/components/schemas/UOMTimeTypes"
          exampleSetFlag: false
        scenario_key:
          type: "string"
          description: "Optional key of a pre-defined CashFlowSc..."
          exampleSetFlag: false
        accounting_period_key:
          type: "string"
          description: "The Accounting Period Key for which the ..."
          exampleSetFlag: false
        gl_account_keys:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: "array"
          exampleSetFlag: false
          items:
            type: "string"
            exampleSetFlag: false
        control_account_keys:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: "array"
          exampleSetFlag: false
          items:
            type: "string"
            exampleSetFlag: false
        organization_id:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: "array"
          exampleSetFlag: false
          items:
            type: "string"
            exampleSetFlag: false
        start_date:
          type: "string"
          description: "The start date for the forecast period (..."
          format: "date"
          exampleSetFlag: false
        end_date:
          type: "string"
          description: "The end date for the forecast period (in..."
          format: "date"
          exampleSetFlag: false
        opening_cash_balance:
          $ref: "#/components/schemas/Money"
          exampleSetFlag: false
      description: "Defines the criteria and scope for generating a Budget Variance\
        \ Report."
      exampleSetFlag: false
    CashFlowProjectionCriteriaCreate:
      required:
      - "cash_flow_projection_criteria_key"
      type: "object"
      description: "CashFlowProjectionCriteria Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/CashFlowProjectionCriteria"
        exampleSetFlag: false
    CashFlowProjectionCriteriaUpdate:
      type: "object"
      properties:
        period_granularity_type:
          $ref: "#/components/schemas/UOMTimeTypes"
          exampleSetFlag: false
        end_date:
          type: "string"
          description: "The end date for the forecast period (in..."
          format: "date"
          exampleSetFlag: false
        opening_cash_balance:
          $ref: "#/components/schemas/Money"
          exampleSetFlag: false
        gl_account_keys:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: "array"
          exampleSetFlag: false
          items:
            type: "string"
            exampleSetFlag: false
        control_account_keys:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: "array"
          exampleSetFlag: false
          items:
            type: "string"
            exampleSetFlag: false
        start_date:
          type: "string"
          description: "The start date for the forecast period (..."
          format: "date"
          exampleSetFlag: false
      description: "CashFlowProjectionCriteria Update for Patch and Put"
      exampleSetFlag: false
    CashFlowProjectionUpdate:
      type: "object"
      properties:
        scenario:
          $ref: "#/components/schemas/CashFlowScenario"
          exampleSetFlag: false
        cash_balance_opening:
          $ref: "#/components/schemas/Money"
          exampleSetFlag: false
        cash_flow_projection_criteria:
          $ref: "#/components/schemas/CashFlowProjectionCriteria"
          exampleSetFlag: false
        line_items:
          $ref: "#/components/schemas/CashFlowLineItems"
          exampleSetFlag: false
        accounting_period:
          $ref: "#/components/schemas/AccountingPeriod"
          exampleSetFlag: false
        projection_date:
          type: "string"
          description: "The date the projection was generated."
          format: "date"
          exampleSetFlag: false
      description: "CashFlowProjection Update for Patch and Put"
      exampleSetFlag: false
    CashFlowScenario:
      type: "object"
      properties:
        scenario_key:
          type: "string"
          description: "The unique key for the Cash Flow Scenari..."
          exampleSetFlag: false
        name:
          type: "string"
          description: "A user-friendly name for the scenario (e..."
          exampleSetFlag: false
        ar_collection_delay_days:
          type: "integer"
          description: "The average number of days past due date..."
          format: "int32"
          exampleSetFlag: false
        ap_payment_hold_days:
          type: "integer"
          description: "The average number of days the business ..."
          format: "int32"
          exampleSetFlag: false
        description:
          type: "string"
          description: "A description of the assumptions used in..."
          exampleSetFlag: false
      description: "not nullable"
      exampleSetFlag: false
    CashFlowScenarioCreate:
      required:
      - "cash_flow_scenario_key"
      type: "object"
      description: "CashFlowScenario Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/CashFlowScenario"
        exampleSetFlag: false
    CashFlowScenarioUpdate:
      type: "object"
      properties:
        ar_collection_delay_days:
          type: "integer"
          description: "The average number of days past due date..."
          format: "int32"
          exampleSetFlag: false
        name:
          type: "string"
          description: "A user-friendly name for the scenario (e..."
          exampleSetFlag: false
        description:
          type: "string"
          description: "A description of the assumptions used in..."
          exampleSetFlag: false
        ap_payment_hold_days:
          type: "integer"
          description: "The average number of days the business ..."
          format: "int32"
          exampleSetFlag: false
      description: "CashFlowScenario Update for Patch and Put"
      exampleSetFlag: false
    Codes:
      type: "array"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    Identifier:
      type: "object"
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        identifier_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Business key for the identifier Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          exampleSetFlag: false
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
      description: "External system identifier"
      exampleSetFlag: false
    IdentifierCreate:
      required:
      - "identifier_key"
      type: "object"
      description: "Identifier Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/Identifier"
        exampleSetFlag: false
    IdentifierUpdate:
      type: "object"
      properties:
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          exampleSetFlag: false
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
      description: "Identifier Update for Patch and Put"
      exampleSetFlag: false
    Identifiers:
      type: "array"
      exampleSetFlag: false
      items:
        $ref: "#/components/schemas/Identifier"
        exampleSetFlag: false
    Money:
      type: "object"
      properties:
        money_key:
          type: "string"
          description: "The unique key for the monetary value."
          exampleSetFlag: false
        money_id:
          type: "string"
          description: "The unique ID for the monetary value."
          exampleSetFlag: false
        currency_code:
          type: "string"
          description: "ISO currency code, e.g., 'USD'."
          exampleSetFlag: false
        display_value:
          type: "string"
          description: "The locale-specific display format for t..."
          exampleSetFlag: false
        locale:
          type: "string"
          description: "The locale code (e.g., en-US, fr-FR)."
          exampleSetFlag: false
        value:
          type: "string"
          description: "The monetary value."
          exampleSetFlag: false
      description: "Represents a monetary value, including its currency, locale, and\
        \ display format."
      exampleSetFlag: false
    UOMTimeTypes:
      type: "string"
      description: "types of u o m times."
      exampleSetFlag: false
      enum:
      - "NANOSECOND"
      - "MICROSECOND"
      - "MILLISECOND"
      - "SECOND"
      - "MINUTE"
      - "HOUR"
      - "DAY"
      - "WEEK"
      - "MONTH"
      - "YEAR"
      - "DECADE"
      - "CENTURY"
      - "MILLENNIUM"
      - "PERCENTAGE_OF_HOUR"
      - "DURATION"
      - "MINUTES"
      - "HOURS"
      - "DAYS"
      - "WEEKS"
      - "DAY_OF_MONTH"
      - "BI_WEEKS"
      - "SEMI_MONTHS"
      - "MONTHS"
      - "QUARTERS"
      - "SEMI_YEARS"
      - "YEARS"
      - "MULTI_YEARS"
      - "OCCURRENCE"
      - "UNLIMITED"
      - "NONE"
      - "CUSTOM"
      - "OTHER"
