---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    Codes:
      type: "array"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    DaysOfWeekTypes:
      type: "string"
      description: "types of days of weeks."
      exampleSetFlag: false
      enum:
      - "SUN"
      - "MON"
      - "TUES"
      - "WED"
      - "THURS"
      - "FRI"
      - "SAT"
    DurationUOMTypes:
      type: "string"
      description: "types of duration u o ms."
      exampleSetFlag: false
      enum:
      - "MINUTES"
      - "HOURS"
      - "DAYS"
      - "DAY_OF_MONTH"
      - "WEEKS"
      - "BI_WEEKS"
      - "SEMI_MONTHS"
      - "MONTHS"
      - "QUARTERS"
      - "SEMI_YEARS"
      - "YEARS"
      - "MULTI_YEARS"
      - "CUSTOM"
      - "OCCURRENCE"
      - "UNLIMITED"
      - "NONE"
      - "OTHER"
    EffectivePeriod:
      type: "object"
      properties:
        effective_period_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique key identifying the effective per... Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric characters and underscores only)"
          exampleSetFlag: false
        active_indicator:
          type: "boolean"
          description: "Indicator if the period is currently act..."
          exampleSetFlag: false
        exclusive_indicator:
          type: "boolean"
          description: "Indicator if the period is exclusive"
          exampleSetFlag: false
        start_date_time:
          type: "string"
          description: "Start date and time of the effective per..."
          format: "date-time"
          exampleSetFlag: false
        complete_date_time:
          type: "string"
          description: "Completion date and time of the effectiv..."
          format: "date-time"
          exampleSetFlag: false
        duration_uom_type:
          $ref: "#/components/schemas/DurationUOMTypes"
          exampleSetFlag: false
        duration_value:
          type: "string"
          description: "Value of the duration"
          exampleSetFlag: false
        recur_uom_type:
          $ref: "#/components/schemas/DurationUOMTypes"
          exampleSetFlag: false
        recur_count:
          type: "string"
          description: "Count of recurrence"
          exampleSetFlag: false
        recur_values:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
        recur_criteria:
          type: "string"
          description: "Criteria defining recurrence"
          exampleSetFlag: false
        recur_indicator:
          type: "boolean"
          description: "Indicator if recurrence is enabled"
          exampleSetFlag: false
        timeslot:
          $ref: "#/components/schemas/TimeSlot"
          exampleSetFlag: false
      description: "Effective Period"
      exampleSetFlag: false
    Identifier:
      type: "object"
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        identifier_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Business key for the identifier Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          exampleSetFlag: false
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
      description: "External system identifier"
      exampleSetFlag: false
    IdentifierCreate:
      required:
      - "identifier_key"
      type: "object"
      description: "Identifier Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/Identifier"
        exampleSetFlag: false
    IdentifierUpdate:
      type: "object"
      properties:
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          exampleSetFlag: false
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
      description: "Identifier Update for Patch and Put"
      exampleSetFlag: false
    Identifiers:
      type: "array"
      exampleSetFlag: false
      items:
        $ref: "#/components/schemas/Identifier"
        exampleSetFlag: false
    PartyIdentifier:
      type: "object"
      properties:
        party_identifier_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        party_identifier_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        party_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        party_identifier_type:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          exampleSetFlag: false
        party_relationship_types:
          pattern: "^[a-zA-Z0-9_]+$"
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: "array"
          exampleSetFlag: false
          items:
            $ref: "#/components/schemas/PartyRelationshipTypes"
            exampleSetFlag: false
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
        party:
          $ref: "#/components/schemas/Identifier"
          exampleSetFlag: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the event occurred."
          format: "date-time"
          exampleSetFlag: false
        duration:
          $ref: "#/components/schemas/EffectivePeriod"
          exampleSetFlag: false
      description: "External system identifier"
      exampleSetFlag: false
    PartyIdentifierCreate:
      required:
      - "party_identifier_key"
      type: "object"
      description: "PartyIdentifier Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/PartyIdentifier"
        exampleSetFlag: false
    PartyIdentifierUpdate:
      type: "object"
      properties:
        duration:
          $ref: "#/components/schemas/EffectivePeriod"
          exampleSetFlag: false
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          exampleSetFlag: false
        party_relationship_types:
          pattern: "^[a-zA-Z0-9_]+$"
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: "array"
          exampleSetFlag: false
          items:
            $ref: "#/components/schemas/PartyRelationshipTypes"
            exampleSetFlag: false
        party_identifier_type:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the event occurred."
          format: "date-time"
          exampleSetFlag: false
        party:
          $ref: "#/components/schemas/Identifier"
          exampleSetFlag: false
      description: "PartyIdentifier Update for Patch and Put"
      exampleSetFlag: false
    PartyIdentifiers:
      type: "array"
      exampleSetFlag: false
      items:
        $ref: "#/components/schemas/PartyIdentifier"
        exampleSetFlag: false
    PartyRelationshipTypes:
      type: "string"
      description: "types of party relationships."
      exampleSetFlag: false
      enum:
      - "CORPORATION"
      - "GROUP"
      - "STORE"
      - "BRANCH"
      - "DEPARTMENT"
      - "SECTION"
      - "TEAM"
      - "DEALERSHIP"
      - "THIRD_PARTY"
      - "VENDOR"
      - "SUPPLIER"
      - "PARTNER_ORGANIZATION"
      - "AFFILIATE"
      - "DISTRIBUTOR"
      - "MANUFACTURER"
      - "SERVICE_PROVIDER"
      - "EMPLOYER"
      - "INTERNAL_ORGANIZATION"
      - "COST_CENTER"
      - "FREIGHT_FORWARDER"
      - "BUYER"
      - "REGULATOR"
      - "GOVERNMENT_AGENCY"
      - "NON_PROFIT"
      - "FRANCHISE"
      - "SUBSIDIARY"
      - "DIVISION"
      - "JOINT_VENTURE"
      - "AUDITOR"
      - "ACTOR"
      - "ACCOUNTABLE"
      - "RESPONSIBLE"
      - "CONSULT"
      - "NOTIFY"
      - "EXECUTE"
      - "PART_OF"
      - "MEMBERSHIP"
      - "COMPOSED_IN"
      - "CUSTOMER"
      - "CO_SIGNER"
      - "SPOUSE"
      - "PARENT"
      - "CHILD"
      - "SIBLING"
      - "LEGAL_GUARDIAN"
      - "DEPENDENT"
      - "EMERGENCY_CONTACT"
      - "FAMILY_MEMBER"
      - "FRIEND"
      - "ACQUAINTANCE"
      - "ASSOCIATE"
      - "EX_SPOUSE"
      - "PROFESSIONAL_CONTACT"
      - "MANAGER"
      - "CO_WORKER"
      - "FINANCIAL_ADVISOR"
      - "SELF"
      - "ROMANTIC_PARTNER"
      - "OTHER_FAMILY"
      - "CAREGIVER"
      - "MENTOR"
      - "MENTEE"
      - "HEIR"
      - "TRUSTEE_PERSON"
      - "REFERENCE_PERSONAL"
      - "REFERENCE_PROFESSIONAL"
      - "AGENT"
      - "BENEFICIARY"
      - "GUARANTOR"
      - "EMPLOYEE"
      - "CONTRACTOR"
      - "OWNER"
      - "BUSINESS_PARTNER"
      - "SERVICE_CONSUMER"
      - "POLITICAL_AFFILIATE"
      - "ADVISOR_CONSULTANT"
      - "PROXY"
      - "SHAREHOLDER"
      - "INVESTOR"
      - "CUSTODIAN"
      - "SOLD_TO"
      - "SHIP_TO"
      - "PAYER"
      - "PAYEE"
      - "GIFT_TO"
      - "LOAN_PROVIDER"
      - "CREDIT_CARD_PROVIDER"
      - "LESSEE"
      - "LESSOR"
      - "INSURED"
      - "INSURER"
      - "UNDERWRITER"
      - "RECIPIENT"
      - "TRANSACTION_FROM"
      - "TRANSACTION_TO"
      - "REMOVE"
      - "OTHER"
    PayrollCycle:
      type: "object"
      properties:
        payroll_cycle_id:
          type: "string"
          description: "A unique identifier for the payroll cycl..."
          exampleSetFlag: false
        payroll_cycle_key:
          type: "string"
          description: "A unique identifier for the payroll cycl..."
          exampleSetFlag: false
        payroll_run_refs:
          $ref: "#/components/schemas/Identifiers"
          exampleSetFlag: false
        primary_entity_id:
          type: "string"
          description: "Primary Entity Id."
          example: "WH001"
          exampleSetFlag: true
        party_identifiers:
          $ref: "#/components/schemas/PartyIdentifiers"
          exampleSetFlag: false
        pay_date_time:
          type: "string"
          description: "The date and time the payment was issued..."
          format: "date-time"
          exampleSetFlag: false
        effective_period:
          $ref: "#/components/schemas/EffectivePeriod"
          exampleSetFlag: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the cycle occurred."
          format: "date-time"
          exampleSetFlag: false
        identifiers:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: "array"
          exampleSetFlag: false
          items:
            $ref: "#/components/schemas/Identifier"
            exampleSetFlag: false
        payroll_cycle_frequency_type:
          $ref: "#/components/schemas/PayrollCycleFrequencyTypes"
          exampleSetFlag: false
      description: "Represents a single cycle that affects a staff member's payroll,\
        \ such as hours worked or a bonus."
      exampleSetFlag: false
    PayrollCycleCreate:
      required:
      - "payroll_cycle_key"
      type: "object"
      description: "PayrollCycle Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/PayrollCycle"
        exampleSetFlag: false
    PayrollCycleFrequencyTypes:
      type: "string"
      description: "types of payroll cycle frequencys."
      exampleSetFlag: false
      enum:
      - "ANNUAL"
      - "SEMI_ANNUAL"
      - "QUARTERLY"
      - "BI_MONTHLY"
      - "MONTHLY"
      - "SEMI_MONTHLY"
      - "BI_WEEKLY"
      - "WEEKLY"
      - "DAILY"
      - "OFF_CYCLE"
      - "ON_DEMAND"
    PayrollCycleUpdate:
      type: "object"
      properties:
        pay_date_time:
          type: "string"
          description: "The date and time the payment was issued..."
          format: "date-time"
          exampleSetFlag: false
        party_identifiers:
          $ref: "#/components/schemas/PartyIdentifiers"
          exampleSetFlag: false
        payroll_run_refs:
          $ref: "#/components/schemas/Identifiers"
          exampleSetFlag: false
        identifiers:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: "array"
          exampleSetFlag: false
          items:
            $ref: "#/components/schemas/Identifier"
            exampleSetFlag: false
        effective_period:
          $ref: "#/components/schemas/EffectivePeriod"
          exampleSetFlag: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the cycle occurred."
          format: "date-time"
          exampleSetFlag: false
        payroll_cycle_frequency_type:
          $ref: "#/components/schemas/PayrollCycleFrequencyTypes"
          exampleSetFlag: false
      description: "PayrollCycle Update for Patch and Put"
      exampleSetFlag: false
    TimeSlot:
      type: "object"
      properties:
        time_slot_key:
          maximum: 100
          minimum: 0
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique business key for the time slot. Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
          exampleSetFlag: false
        end_day:
          $ref: "#/components/schemas/DaysOfWeekTypes"
          exampleSetFlag: false
        end_time:
          pattern: "^([01]\\d|2[0-3]):([0-5]\\d)$"
          type: "string"
          description: "End time in HH:mm format. Pattern: ^([01]\\d|2[0-3]):([0-5]\\\
            d)$ (Must be in HH:mm 24-hour format)"
          format: "date-time"
          exampleSetFlag: false
        recurring_indicator:
          type: "boolean"
          description: "Indicates if the time slot is recurring."
          exampleSetFlag: false
        recurring_period:
          $ref: "#/components/schemas/EffectivePeriod"
          exampleSetFlag: false
        start_day:
          $ref: "#/components/schemas/DaysOfWeekTypes"
          exampleSetFlag: false
        start_time:
          pattern: "^([01]\\d|2[0-3]):([0-5]\\d)$"
          type: "string"
          description: "Start time in HH:mm format. Pattern: ^([01]\\d|2[0-3]):([0-5]\\\
            d)$ (Must be in HH:mm 24-hour format)"
          format: "date-time"
          exampleSetFlag: false
        timeslot_directive_types:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: "array"
          exampleSetFlag: false
          items:
            $ref: "#/components/schemas/TimeslotDirectiveTypes"
            exampleSetFlag: false
        time_slot_id:
          maximum: 100
          minimum: 0
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier for the time slot reco... Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
          exampleSetFlag: false
        week_of_date:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: "array"
          format: "date"
          exampleSetFlag: false
          items:
            type: "string"
            exampleSetFlag: false
      description: "Range of time for the appointment including start/end times, recurring\
        \ patterns, and directives."
      exampleSetFlag: false
    TimeslotDirectiveTypes:
      type: "string"
      description: "types of timeslot directives."
      exampleSetFlag: false
      enum:
      - "AFTER"
      - "ANYTIME"
      - "BEFORE"
      - "BETWEEN"
      - "BLOCK"
      - "UNKNOWN"
