---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    Codes:
      type: "array"
      description: "List of Codes"
      items:
        type: "string"
    DaysOfWeekTypes:
      type: "string"
      description: "types of days of weeks."
      enum:
      - "SUN"
      - "MON"
      - "TUES"
      - "WED"
      - "THURS"
      - "FRI"
      - "SAT"
    DurationUOMTypes:
      type: "string"
      description: "types of duration u o ms."
      enum:
      - "MINUTES"
      - "HOURS"
      - "DAYS"
      - "DAY_OF_MONTH"
      - "WEEKS"
      - "BI_WEEKS"
      - "SEMI_MONTHS"
      - "MONTHS"
      - "QUARTERS"
      - "SEMI_YEARS"
      - "YEARS"
      - "MULTI_YEARS"
      - "CUSTOM"
      - "OCCURRENCE"
      - "UNLIMITED"
      - "NONE"
      - "OTHER"
    EffectivePeriod:
      type: "object"
      properties:
        effective_period_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique key identifying the effective period Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric characters and underscores only)"
          nullable: false
        active_indicator:
          type: "boolean"
          description: "Indicator if the period is currently active"
          nullable: true
        exclusive_indicator:
          type: "boolean"
          description: "Indicator if the period is exclusive"
          nullable: true
        start_date_time:
          type: "string"
          description: "Start date and time of the effective period"
          format: "date-time"
          nullable: true
        complete_date_time:
          type: "string"
          description: "Completion date and time of the effective period"
          format: "date-time"
          nullable: true
        duration_uom_type:
          description: "Unit of measure type for the duration"
          $ref: "#/components/schemas/DurationUOMTypes"
          nullable: true
        duration_value:
          type: "string"
          description: "Value of the duration"
          nullable: true
        recur_uom_type:
          description: "Unit of measure type for recurrence"
          $ref: "#/components/schemas/DurationUOMTypes"
          nullable: true
        recur_count:
          type: "string"
          description: "Count of recurrence"
          nullable: true
        recur_values:
          description: "Values defining recurrence criteria"
          $ref: "#/components/schemas/Codes"
          nullable: true
        recur_criteria:
          type: "string"
          description: "Criteria defining recurrence"
          nullable: true
        recur_indicator:
          type: "boolean"
          description: "Indicator if recurrence is enabled"
          nullable: true
        timeslot:
          description: "Associated time slot for the effective period"
          $ref: "#/components/schemas/TimeSlot"
          nullable: true
      description: "Effective Period"
    Identifier:
      type: "object"
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          nullable: false
        identifier_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Business key for the identifier Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          nullable: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          nullable: true
        value:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
        detail:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
        system_codes:
          description: "Associated system codes for this identifier"
          $ref: "#/components/schemas/Codes"
          nullable: true
      description: "External system identifier"
    Identifiers:
      type: "array"
      description: "List of Identifier"
      items:
        $ref: "#/components/schemas/Identifier"
    Link:
      type: "array"
      description: "Quick Link"
      items:
        type: "string"
    Links:
      type: "array"
      description: "List of Links"
      items:
        type: "string"
    List:
      type: "array"
      description: "List of String"
      items:
        type: "string"
    PartyIdentifier:
      type: "object"
      properties:
        party_identifier_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          nullable: false
        party_identifier_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          nullable: false
        party_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          nullable: false
        party_identifier_type:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          nullable: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          nullable: true
        party_relationship_types:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: "array"
          description: "Party Relationship Type Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          nullable: false
          example: ""
          items:
            $ref: "#/components/schemas/PartyRelationshipTypes"
        system_codes:
          description: "Associated system codes for this identifier"
          $ref: "#/components/schemas/Codes"
          nullable: true
        party:
          description: "Details of the supplier from whom parts are being purchased."
          $ref: "#/components/schemas/Identifier"
          nullable: false
        occurrence_date_time:
          type: "string"
          description: "The date and time the event occurred."
          format: "date-time"
          nullable: false
        duration:
          description: "The duration over which the trend was measured."
          $ref: "#/components/schemas/EffectivePeriod"
          nullable: false
      description: "External system identifier"
    PartyIdentifiers:
      type: "array"
      description: "List of PartyIdentifier"
      items:
        $ref: "#/components/schemas/PartyIdentifier"
    PartyRelationshipTypes:
      type: "string"
      description: "types of party relationships."
      enum:
      - "CORPORATION"
      - "GROUP"
      - "STORE"
      - "BRANCH"
      - "DEPARTMENT"
      - "SECTION"
      - "TEAM"
      - "DEALERSHIP"
      - "THIRD_PARTY"
      - "VENDOR"
      - "SUPPLIER"
      - "PARTNER_ORGANIZATION"
      - "AFFILIATE"
      - "DISTRIBUTOR"
      - "MANUFACTURER"
      - "SERVICE_PROVIDER"
      - "EMPLOYER"
      - "INTERNAL_ORGANIZATION"
      - "COST_CENTER"
      - "FREIGHT_FORWARDER"
      - "BUYER"
      - "REGULATOR"
      - "GOVERNMENT_AGENCY"
      - "NON_PROFIT"
      - "FRANCHISE"
      - "SUBSIDIARY"
      - "DIVISION"
      - "JOINT_VENTURE"
      - "AUDITOR"
      - "ACTOR"
      - "ACCOUNTABLE"
      - "RESPONSIBLE"
      - "CONSULT"
      - "NOTIFY"
      - "EXECUTE"
      - "PART_OF"
      - "MEMBERSHIP"
      - "COMPOSED_IN"
      - "CUSTOMER"
      - "CO_SIGNER"
      - "SPOUSE"
      - "PARENT"
      - "CHILD"
      - "SIBLING"
      - "LEGAL_GUARDIAN"
      - "DEPENDENT"
      - "EMERGENCY_CONTACT"
      - "FAMILY_MEMBER"
      - "FRIEND"
      - "ACQUAINTANCE"
      - "ASSOCIATE"
      - "EX_SPOUSE"
      - "PROFESSIONAL_CONTACT"
      - "MANAGER"
      - "CO_WORKER"
      - "FINANCIAL_ADVISOR"
      - "SELF"
      - "ROMANTIC_PARTNER"
      - "OTHER_FAMILY"
      - "CAREGIVER"
      - "MENTOR"
      - "MENTEE"
      - "HEIR"
      - "TRUSTEE_PERSON"
      - "REFERENCE_PERSONAL"
      - "REFERENCE_PROFESSIONAL"
      - "AGENT"
      - "BENEFICIARY"
      - "GUARANTOR"
      - "EMPLOYEE"
      - "CONTRACTOR"
      - "OWNER"
      - "BUSINESS_PARTNER"
      - "SERVICE_CONSUMER"
      - "POLITICAL_AFFILIATE"
      - "ADVISOR_CONSULTANT"
      - "PROXY"
      - "SHAREHOLDER"
      - "INVESTOR"
      - "CUSTODIAN"
      - "SOLD_TO"
      - "SHIP_TO"
      - "PAYER"
      - "PAYEE"
      - "GIFT_TO"
      - "LOAN_PROVIDER"
      - "CREDIT_CARD_PROVIDER"
      - "LESSEE"
      - "LESSOR"
      - "INSURED"
      - "INSURER"
      - "UNDERWRITER"
      - "RECIPIENT"
      - "TRANSACTION_FROM"
      - "TRANSACTION_TO"
      - "REMOVE"
      - "OTHER"
    PayrollCycle:
      type: "object"
      properties:
        payroll_cycle_id:
          type: "string"
          description: "A unique identifier for the payroll cycle."
          nullable: false
        payroll_cycle_key:
          type: "string"
          description: "A unique identifier for the payroll cycle."
          nullable: false
        payroll_run_refs:
          description: "A unique identifier payroll run."
          $ref: "#/components/schemas/Identifiers"
          nullable: false
        primary_entity_id:
          type: "string"
          description: "Primary Entity Id."
          nullable: true
          example: "WH001"
        party_identifiers:
          description: "Customer, Payer, ShipTo, SoldTo, or Vendor depending on invoice\
            \ type"
          $ref: "#/components/schemas/PartyIdentifiers"
          nullable: true
        pay_date_time:
          type: "string"
          description: "The date and time the payment was issued."
          format: "date-time"
          nullable: false
        effective_period:
          description: "Cycle Reference for this cycle"
          $ref: "#/components/schemas/EffectivePeriod"
          nullable: true
        occurrence_date_time:
          type: "string"
          description: "The date and time the cycle occurred."
          format: "date-time"
          nullable: false
        identifiers:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: "array"
          description: "A list of additional identifiers relevant to this specific\
            \ line item."
          nullable: true
          example: ""
          items:
            $ref: "#/components/schemas/Identifier"
        payroll_cycle_frequency_type:
          description: "A unique identifier for the payroll event."
          $ref: "#/components/schemas/PayrollCycleFrequencyTypes"
          nullable: false
      description: "Represents a single cycle that affects a staff member's payroll,\
        \ such as hours worked or a bonus."
    PayrollCycleFrequencyTypes:
      type: "string"
      description: "types of payroll cycle frequencys."
      enum:
      - "ANNUAL"
      - "SEMI_ANNUAL"
      - "QUARTERLY"
      - "BI_MONTHLY"
      - "MONTHLY"
      - "SEMI_MONTHLY"
      - "BI_WEEKLY"
      - "WEEKLY"
      - "DAILY"
      - "OFF_CYCLE"
      - "ON_DEMAND"
    TimeSlot:
      type: "object"
      properties:
        time_slot_key:
          maximum: 100
          minimum: 0
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique business key for the time slot. Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
          nullable: false
        end_day:
          description: "Day of the week when the time slot ends."
          $ref: "#/components/schemas/DaysOfWeekTypes"
          nullable: true
        end_time:
          pattern: "^([01]\\d|2[0-3]):([0-5]\\d)$"
          type: "string"
          description: "End time in HH:mm format. Pattern: ^([01]\\d|2[0-3]):([0-5]\\\
            d)$ (Must be in HH:mm 24-hour format)"
          format: "date-time"
          nullable: true
        recurring_indicator:
          type: "boolean"
          description: "Indicates if the time slot is recurring."
          nullable: true
        recurring_period:
          description: "Defines the recurrence period for the time slot."
          $ref: "#/components/schemas/EffectivePeriod"
          nullable: true
        start_day:
          description: "Day of the week when the time slot starts."
          $ref: "#/components/schemas/DaysOfWeekTypes"
          nullable: true
        start_time:
          pattern: "^([01]\\d|2[0-3]):([0-5]\\d)$"
          type: "string"
          description: "Start time in HH:mm format. Pattern: ^([01]\\d|2[0-3]):([0-5]\\\
            d)$ (Must be in HH:mm 24-hour format)"
          format: "date-time"
          nullable: true
        timeslot_directive_types:
          maxLength: 10
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: "array"
          description: "Directives associated with the time slot (e.g., cutoff times,\
            \ restrictions)."
          nullable: true
          example: ""
          items:
            $ref: "#/components/schemas/TimeslotDirectiveTypes"
        time_slot_id:
          maximum: 100
          minimum: 0
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier for the time slot record. Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
          nullable: false
        week_of_date:
          maxLength: 10
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: "array"
          description: "Dates representing the specific week(s) of the time slot."
          format: "date"
          nullable: true
          example: ""
          items:
            type: "string"
      description: "Range of time for the appointment including start/end times, recurring\
        \ patterns, and directives."
    TimeslotDirectiveTypes:
      type: "string"
      description: "types of timeslot directives."
      enum:
      - "AFTER"
      - "ANYTIME"
      - "BEFORE"
      - "BETWEEN"
      - "BLOCK"
      - "UNKNOWN"
