---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths:
  /financial-snapshots:
    get:
      tags:
      - "FinancialSnapshot"
      summary: "Retrieve a list of all FinancialSnapshot records."
      operationId: "listFinancialSnapshots"
      parameters:
      - name: "limit"
        in: "query"
        description: "Maximum number of records to return."
        schema:
          maximum: 100
          minimum: 1
          type: "integer"
          default: 50
      - name: "cursor"
        in: "query"
        description: "starting point for next set of results"
        schema:
          type: "string"
      responses:
        "200":
          description: "A list of FinancialSnapshot records."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/FinancialSnapshot"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"
    post:
      tags:
      - "FinancialSnapshot"
      summary: "Create a new FinancialSnapshot record."
      operationId: "createFinancialSnapshot"
      requestBody:
        description: "FinancialSnapshot data to create the new resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FinancialSnapshotCreate"
        required: true
      responses:
        "201":
          description: "FinancialSnapshot created successfully."
          headers:
            Location:
              description: "The URI of the newly created resource."
              schema:
                type: "string"
                example: "/financial-snapshots/PR-1234567"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FinancialSnapshot"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "409":
          $ref: "#/components/responses/ConflictError"
  /financial-snapshots/{financialSnapshotKey}:
    get:
      tags:
      - "FinancialSnapshot"
      summary: "Retrieve a specific FinancialSnapshot record."
      operationId: "getFinancialSnapshotById"
      responses:
        "200":
          description: "The requested FinancialSnapshot record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FinancialSnapshot"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    put:
      tags:
      - "FinancialSnapshot"
      summary: "Replace a FinancialSnapshot record."
      operationId: "replaceFinancialSnapshot"
      requestBody:
        description: "Full record data to replace the existing resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FinancialSnapshot"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FinancialSnapshot"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    delete:
      tags:
      - "FinancialSnapshot"
      summary: "Delete a FinancialSnapshot Record"
      description: "Marks the FinancialSnapshot record as inactive or removes it entirely."
      operationId: "deleteFinancialSnapshotRecord"
      responses:
        "204":
          description: "Record successfully deleted (or deactivated)."
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    patch:
      tags:
      - "FinancialSnapshot"
      summary: "Partially update a FinancialSnapshot record."
      operationId: "updateFinancialSnapshot"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FinancialSnapshotUpdate"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FinancialSnapshot"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    parameters:
    - name: "financialSnapshotKey"
      in: "path"
      description: "The unique identifier for the specific FinancialSnapshot."
      required: true
      schema:
        type: "string"
        example: "PR-1234567"
  /financial-snapshots/{financialSnapshotKey}/financial-snapshot-line-items:
    get:
      tags:
      - "FinancialSnapshotLineItem"
      summary: "Retrieve a list of FinancialSnapshotLineItem records scoped by financialSnapshotKey."
      operationId: "listFinancialSnapshotLineItemsByFinancialSnapshotKey"
      parameters:
      - name: "limit"
        in: "query"
        description: "Maximum number of records to return."
        schema:
          maximum: 100
          minimum: 1
          type: "integer"
          default: 50
      - name: "cursor"
        in: "query"
        description: "starting point for next set of results"
        schema:
          type: "string"
      responses:
        "200":
          description: "A list of FinancialSnapshotLineItem records."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/FinancialSnapshotLineItem"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"
    post:
      tags:
      - "FinancialSnapshotLineItem"
      summary: "Create a new FinancialSnapshotLineItem record."
      operationId: "createFinancialSnapshotLineItem"
      requestBody:
        description: "FinancialSnapshotLineItem data to create the new resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FinancialSnapshotLineItemCreate"
        required: true
      responses:
        "201":
          description: "FinancialSnapshotLineItem created successfully."
          headers:
            Location:
              description: "The URI of the newly created resource."
              schema:
                type: "string"
                example: "/part-search-results/PS-12345/bill-of-materials/BOM-001"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FinancialSnapshotLineItem"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "409":
          $ref: "#/components/responses/ConflictError"
    parameters:
    - name: "financialSnapshotKey"
      in: "path"
      description: "The unique identifier for the parent resource."
      required: true
      schema:
        type: "string"
  /financial-snapshots/{financialSnapshotKey}/financial-snapshot-line-items/{financialSnapshotLineItemKey}:
    get:
      tags:
      - "FinancialSnapshotLineItem"
      summary: "Retrieve a specific FinancialSnapshotLineItem record."
      operationId: "getFinancialSnapshotLineItemById"
      responses:
        "200":
          description: "The requested FinancialSnapshotLineItem record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FinancialSnapshotLineItem"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    put:
      tags:
      - "FinancialSnapshotLineItem"
      summary: "Replace a FinancialSnapshotLineItem record."
      operationId: "replaceFinancialSnapshotLineItem"
      requestBody:
        description: "Full record data to replace the existing resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FinancialSnapshotLineItem"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FinancialSnapshotLineItem"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    delete:
      tags:
      - "FinancialSnapshotLineItem"
      summary: "Delete a FinancialSnapshotLineItem Record"
      description: "Marks the FinancialSnapshotLineItem record as inactive or removes\
        \ it entirely."
      operationId: "deleteFinancialSnapshotLineItemRecord"
      responses:
        "204":
          description: "Record successfully deleted (or deactivated)."
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    patch:
      tags:
      - "FinancialSnapshotLineItem"
      summary: "Partially update a FinancialSnapshotLineItem record."
      operationId: "updateFinancialSnapshotLineItem"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FinancialSnapshotLineItemUpdate"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FinancialSnapshotLineItem"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    parameters:
    - name: "financialSnapshotKey"
      in: "path"
      description: "The unique identifier for the parent resource."
      required: true
      schema:
        type: "string"
    - name: "financialSnapshotLineItemKey"
      in: "path"
      description: "The unique identifier for the specific FinancialSnapshotLineItem."
      required: true
      schema:
        type: "string"
        example: "PR-1234567"
  /financial-snapshots/{financialSnapshotKey}/moneys:
    get:
      tags:
      - "Money"
      summary: "Retrieve a list of Money records scoped by financialSnapshotKey."
      operationId: "listMoneysByFinancialSnapshotKey"
      parameters:
      - name: "limit"
        in: "query"
        description: "Maximum number of records to return."
        schema:
          maximum: 100
          minimum: 1
          type: "integer"
          default: 50
      - name: "cursor"
        in: "query"
        description: "starting point for next set of results"
        schema:
          type: "string"
      responses:
        "200":
          description: "A list of Money records."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Money"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"
    parameters:
    - name: "financialSnapshotKey"
      in: "path"
      description: "The unique identifier for the parent resource."
      required: true
      schema:
        type: "string"
  /financial-snapshots/{financialSnapshotKey}/moneys/{moneyKey}:
    get:
      tags:
      - "Money"
      summary: "Retrieve a specific Money record."
      operationId: "getMoneyById"
      responses:
        "200":
          description: "The requested Money record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Money"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    put:
      tags:
      - "Money"
      summary: "Replace a Money record."
      operationId: "replaceMoney"
      requestBody:
        description: "Full record data to replace the existing resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Money"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Money"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    parameters:
    - name: "financialSnapshotKey"
      in: "path"
      description: "The unique identifier for the parent resource."
      required: true
      schema:
        type: "string"
    - name: "moneyKey"
      in: "path"
      description: "The unique identifier for the specific Money."
      required: true
      schema:
        type: "string"
        example: "PR-1234567"
  /financial-snapshots/{financialSnapshotKey}/financial-snapshot-criterias:
    get:
      tags:
      - "FinancialSnapshotCriteria"
      summary: "Retrieve a list of FinancialSnapshotCriteria records scoped by financialSnapshotKey."
      operationId: "listFinancialSnapshotCriteriasByFinancialSnapshotKey"
      parameters:
      - name: "limit"
        in: "query"
        description: "Maximum number of records to return."
        schema:
          maximum: 100
          minimum: 1
          type: "integer"
          default: 50
      - name: "cursor"
        in: "query"
        description: "starting point for next set of results"
        schema:
          type: "string"
      responses:
        "200":
          description: "A list of FinancialSnapshotCriteria records."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/FinancialSnapshotCriteria"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"
    post:
      tags:
      - "FinancialSnapshotCriteria"
      summary: "Create a new FinancialSnapshotCriteria record."
      operationId: "createFinancialSnapshotCriteria"
      requestBody:
        description: "FinancialSnapshotCriteria data to create the new resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FinancialSnapshotCriteriaCreate"
        required: true
      responses:
        "201":
          description: "FinancialSnapshotCriteria created successfully."
          headers:
            Location:
              description: "The URI of the newly created resource."
              schema:
                type: "string"
                example: "/part-search-results/PS-12345/bill-of-materials/BOM-001"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FinancialSnapshotCriteria"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "409":
          $ref: "#/components/responses/ConflictError"
    parameters:
    - name: "financialSnapshotKey"
      in: "path"
      description: "The unique identifier for the parent resource."
      required: true
      schema:
        type: "string"
  /financial-snapshots/{financialSnapshotKey}/financial-snapshot-criterias/{financialSnapshotCriteriaKey}:
    get:
      tags:
      - "FinancialSnapshotCriteria"
      summary: "Retrieve a specific FinancialSnapshotCriteria record."
      operationId: "getFinancialSnapshotCriteriaById"
      responses:
        "200":
          description: "The requested FinancialSnapshotCriteria record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FinancialSnapshotCriteria"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    put:
      tags:
      - "FinancialSnapshotCriteria"
      summary: "Replace a FinancialSnapshotCriteria record."
      operationId: "replaceFinancialSnapshotCriteria"
      requestBody:
        description: "Full record data to replace the existing resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FinancialSnapshotCriteria"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FinancialSnapshotCriteria"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    delete:
      tags:
      - "FinancialSnapshotCriteria"
      summary: "Delete a FinancialSnapshotCriteria Record"
      description: "Marks the FinancialSnapshotCriteria record as inactive or removes\
        \ it entirely."
      operationId: "deleteFinancialSnapshotCriteriaRecord"
      responses:
        "204":
          description: "Record successfully deleted (or deactivated)."
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    patch:
      tags:
      - "FinancialSnapshotCriteria"
      summary: "Partially update a FinancialSnapshotCriteria record."
      operationId: "updateFinancialSnapshotCriteria"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FinancialSnapshotCriteriaUpdate"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FinancialSnapshotCriteria"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    parameters:
    - name: "financialSnapshotKey"
      in: "path"
      description: "The unique identifier for the parent resource."
      required: true
      schema:
        type: "string"
    - name: "financialSnapshotCriteriaKey"
      in: "path"
      description: "The unique identifier for the specific FinancialSnapshotCriteria."
      required: true
      schema:
        type: "string"
        example: "PR-1234567"
components:
  schemas: {}
