---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    FinancialCategoryTypes:
      type: "string"
      description: "types of financial categorys."
      exampleSetFlag: false
      enum:
      - "CAPEX"
      - "OPEX"
      - "HARDWARE"
      - "SOFTWARE"
      - "MAINTENANCE"
      - "TRAVEL"
      - "TRAINING"
      - "UTILITIES"
      - "RENT"
      - "SALARY"
      - "REVENUE"
      - "TAX"
      - "OTHER"
    FinancialReportTypes:
      type: "string"
      description: "types of financial reports."
      exampleSetFlag: false
      enum:
      - "TRIAL_BALANCE"
      - "BALANCE_SHEET"
      - "P_AND_L"
      - "CASH_FLOW_STATEMENT"
      - "BUDGET_VARIANCE"
      - "CASH_FLOW_PROJECTION"
      - "GENERAL_LEDGER_DETAIL"
    FinancialSnapshot:
      type: "object"
      properties:
        financial_snapshot_id:
          type: "string"
          description: "The unique ID for this generated snapsho..."
          exampleSetFlag: false
        financial_snapshot_key:
          type: "string"
          description: "The unique ID for this generated snapsho..."
          exampleSetFlag: false
        as_of_date:
          type: "string"
          description: "The date and time the snapshot was proce..."
          format: "date"
          exampleSetFlag: false
        criteria:
          $ref: "#/components/schemas/FinancialSnapshotCriteria"
          exampleSetFlag: false
        lines:
          $ref: "#/components/schemas/FinancialSnapshotLineItems"
          exampleSetFlag: false
      description: "A real-time aggregated financial report (P&L, Balance Sheet, or\
        \ Trial Balance) generated as a view model for dashboards."
      exampleSetFlag: false
    FinancialSnapshotCreate:
      required:
      - "financial_snapshot_key"
      type: "object"
      description: "FinancialSnapshot Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/FinancialSnapshot"
        exampleSetFlag: false
    FinancialSnapshotCriteria:
      type: "object"
      properties:
        financial_snapshot_criteria_id:
          type: "string"
          description: "The unique ID for this generated snapsho..."
          exampleSetFlag: false
        financial_snapshot_criteria_key:
          type: "string"
          description: "The unique ID for this generated snapsho..."
          exampleSetFlag: false
        organization_id:
          type: "string"
          description: "The unique identifier for the organizati..."
          exampleSetFlag: false
        financial_report_type:
          $ref: "#/components/schemas/FinancialReportTypes"
          exampleSetFlag: false
        as_of_date:
          type: "string"
          description: "The exact date for which the financial d..."
          format: "date"
          exampleSetFlag: false
        comparison_date:
          type: "string"
          description: "Optional date defining a previous period..."
          format: "date"
          exampleSetFlag: false
        gl_account_filter_key:
          type: "string"
          description: "Optional key for filtering the report to..."
          exampleSetFlag: false
      description: "Defines the criteria for requesting a real-time financial snapshot\
        \ (P&L, Balance Sheet, Trial Balance)."
      exampleSetFlag: false
    FinancialSnapshotCriteriaCreate:
      required:
      - "financial_snapshot_criteria_key"
      type: "object"
      description: "FinancialSnapshotCriteria Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/FinancialSnapshotCriteria"
        exampleSetFlag: false
    FinancialSnapshotCriteriaUpdate:
      type: "object"
      properties:
        financial_report_type:
          $ref: "#/components/schemas/FinancialReportTypes"
          exampleSetFlag: false
        as_of_date:
          type: "string"
          description: "The exact date for which the financial d..."
          format: "date"
          exampleSetFlag: false
        comparison_date:
          type: "string"
          description: "Optional date defining a previous period..."
          format: "date"
          exampleSetFlag: false
      description: "FinancialSnapshotCriteria Update for Patch and Put"
      exampleSetFlag: false
    FinancialSnapshotLineItem:
      type: "object"
      properties:
        financial_snapshot_line_item_id:
          type: "string"
          description: "The unique ID for this generated snapsho..."
          exampleSetFlag: false
        financial_snapshot_line_item_key:
          type: "string"
          description: "The unique ID for this generated snapsho..."
          exampleSetFlag: false
        account_name:
          type: "string"
          description: "The descriptive name of the account line..."
          exampleSetFlag: false
        financial_category_type:
          $ref: "#/components/schemas/FinancialCategoryTypes"
          exampleSetFlag: false
        current_balance:
          $ref: "#/components/schemas/Money"
          exampleSetFlag: false
        comparison_balance:
          $ref: "#/components/schemas/Money"
          exampleSetFlag: false
      description: "A generic line item representing an aggregated balance for a specific\
        \ GL account or category within a financial snapshot."
      exampleSetFlag: false
    FinancialSnapshotLineItemCreate:
      required:
      - "financial_snapshot_line_item_key"
      type: "object"
      description: "FinancialSnapshotLineItem Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/FinancialSnapshotLineItem"
        exampleSetFlag: false
    FinancialSnapshotLineItemUpdate:
      type: "object"
      properties:
        account_name:
          type: "string"
          description: "The descriptive name of the account line..."
          exampleSetFlag: false
        comparison_balance:
          $ref: "#/components/schemas/Money"
          exampleSetFlag: false
        current_balance:
          $ref: "#/components/schemas/Money"
          exampleSetFlag: false
        financial_category_type:
          $ref: "#/components/schemas/FinancialCategoryTypes"
          exampleSetFlag: false
      description: "FinancialSnapshotLineItem Update for Patch and Put"
      exampleSetFlag: false
    FinancialSnapshotLineItems:
      type: "array"
      exampleSetFlag: false
      items:
        $ref: "#/components/schemas/FinancialSnapshotLineItem"
        exampleSetFlag: false
    FinancialSnapshotUpdate:
      type: "object"
      properties:
        as_of_date:
          type: "string"
          description: "The date and time the snapshot was proce..."
          format: "date"
          exampleSetFlag: false
        criteria:
          $ref: "#/components/schemas/FinancialSnapshotCriteria"
          exampleSetFlag: false
        lines:
          $ref: "#/components/schemas/FinancialSnapshotLineItems"
          exampleSetFlag: false
      description: "FinancialSnapshot Update for Patch and Put"
      exampleSetFlag: false
    Money:
      type: "object"
      properties:
        money_key:
          type: "string"
          description: "The unique key for the monetary value."
          exampleSetFlag: false
        money_id:
          type: "string"
          description: "The unique ID for the monetary value."
          exampleSetFlag: false
        currency_code:
          type: "string"
          description: "ISO currency code, e.g., 'USD'."
          exampleSetFlag: false
        display_value:
          type: "string"
          description: "The locale-specific display format for t..."
          exampleSetFlag: false
        locale:
          type: "string"
          description: "The locale code (e.g., en-US, fr-FR)."
          exampleSetFlag: false
        value:
          type: "string"
          description: "The monetary value."
          exampleSetFlag: false
      description: "Represents a monetary value, including its currency, locale, and\
        \ display format."
      exampleSetFlag: false
