---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    Codes:
      type: "array"
      description: "List of Codes"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    LifecycleEvent:
      type: "object"
      properties:
        lifecycle_event_id:
          type: "string"
          description: "The unique ID for the lifecycle event."
          nullable: false
          example: "EVT-99887766"
          exampleSetFlag: true
        lifecycle_event_key:
          type: "string"
          description: "The unique external key or business identifier used in integrations."
          nullable: false
          example: "LIFECYCLE-879234"
          exampleSetFlag: true
        actor_href:
          type: "string"
          description: "The href of the actor who initiated the event."
          format: "href"
          nullable: false
          exampleSetFlag: false
        actor_id:
          type: "string"
          description: "The unique identifier of the actor who initiated the event."
          nullable: false
          example: "USR-24681357"
          exampleSetFlag: true
        actor_name:
          type: "string"
          description: "The name of the actor who initiated the event."
          nullable: false
          example: "John Doe"
          exampleSetFlag: true
        lifecycle_event_type:
          description: "The type of lifecycle event."
          $ref: "#/components/schemas/LifecycleEventTypes"
          nullable: false
          exampleSetFlag: false
        occurrence_date:
          type: "string"
          description: "The date and time the event occurred."
          format: "date"
          nullable: false
          exampleSetFlag: false
        resource_href:
          type: "string"
          description: "The href of the resource associated with the event."
          format: "href"
          nullable: false
          exampleSetFlag: false
        resource_identifier:
          type: "string"
          description: "The unique identifier of the resource associated with the\
            \ event."
          nullable: false
          example: "RSC-88776655"
          exampleSetFlag: true
        detail_name:
          type: "string"
          description: "The name of the event detail."
          nullable: false
          example: "Order ID"
          exampleSetFlag: true
        detail_desc:
          type: "string"
          description: "A description of the event detail."
          nullable: false
          example: "The unique ID of the order being processed."
          exampleSetFlag: true
        detail_value:
          type: "string"
          description: "The value of the event detail."
          nullable: false
          example: "ORD-44556677"
          exampleSetFlag: true
        detail_key:
          type: "string"
          description: "The unique key for the event detail."
          nullable: false
          example: "ORDER_ID"
          exampleSetFlag: true
        detail_code:
          type: "string"
          description: "The code for the event detail."
          nullable: false
          example: "ORDER_STATUS_CHANGED"
          exampleSetFlag: true
        resource_types:
          description: "The types of resources associated with the trend."
          $ref: "#/components/schemas/ResourceTypes"
          nullable: false
          exampleSetFlag: false
      description: "Lifecycle Event"
      exampleSetFlag: false
    LifecycleEventTypes:
      type: "string"
      description: "types of lifecycle events."
      exampleSetFlag: false
      enum:
      - "CREATED"
      - "UPDATED"
      - "DELETE_HARD"
      - "DELETE_SOFT"
      - "ACCESS_ALLOWED"
      - "ACCESS_DENIED"
      - "SUBMITTED"
      - "CLOSED"
      - "CANCELLED"
      - "DEAD"
      - "INITIALIZED"
      - "INITIALIZING"
      - "PROCESSING"
      - "PROCESSED"
      - "FAILED"
      - "VALIDATED"
      - "QUALIFIED"
    LifecycleEvent_Create:
      required:
      - "lifecycle_event_key"
      type: "object"
      description: "LifecycleEvent Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/LifecycleEvent"
        exampleSetFlag: false
    LifecycleEvent_Update:
      type: "object"
      properties:
        occurrence_date:
          type: "string"
          description: "The date and time the event occurred."
          format: "date"
          nullable: false
          exampleSetFlag: false
        resource_href:
          type: "string"
          description: "The href of the resource associated with the event."
          format: "href"
          nullable: false
          exampleSetFlag: false
        detail_name:
          type: "string"
          description: "The name of the event detail."
          nullable: false
          example: "Order ID"
          exampleSetFlag: true
        lifecycle_event_type:
          description: "The type of lifecycle event."
          $ref: "#/components/schemas/LifecycleEventTypes"
          nullable: false
          exampleSetFlag: false
        resource_identifier:
          type: "string"
          description: "The unique identifier of the resource associated with the\
            \ event."
          nullable: false
          example: "RSC-88776655"
          exampleSetFlag: true
        actor_name:
          type: "string"
          description: "The name of the actor who initiated the event."
          nullable: false
          example: "John Doe"
          exampleSetFlag: true
        detail_desc:
          type: "string"
          description: "A description of the event detail."
          nullable: false
          example: "The unique ID of the order being processed."
          exampleSetFlag: true
        detail_value:
          type: "string"
          description: "The value of the event detail."
          nullable: false
          example: "ORD-44556677"
          exampleSetFlag: true
        detail_code:
          type: "string"
          description: "The code for the event detail."
          nullable: false
          example: "ORDER_STATUS_CHANGED"
          exampleSetFlag: true
        actor_href:
          type: "string"
          description: "The href of the actor who initiated the event."
          format: "href"
          nullable: false
          exampleSetFlag: false
        resource_types:
          description: "The types of resources associated with the trend."
          $ref: "#/components/schemas/ResourceTypes"
          nullable: false
          exampleSetFlag: false
      description: "LifecycleEvent Update for Patch and Put"
      exampleSetFlag: false
    Link:
      type: "array"
      description: "Quick Link"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    Links:
      type: "array"
      description: "List of Links"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    ResourceTypes:
      type: "string"
      description: "types of resources."
      exampleSetFlag: false
      enum:
      - "SYSTEM"
      - "WORKFLOW"
      - "ACTIVITY"
      - "FUNCTION"
      - "PROCESS"
      - "INCIDENT"
      - "PARTY"
      - "CUSTOMER"
      - "APPLICANT"
      - "VENDOR"
      - "DEALER_STAFF"
      - "DRIVER"
      - "ADDRESS"
      - "BILL_ADDRESS"
      - "BILL_CONTACT"
      - "COMM_CHANNEL"
      - "ACCOUNT"
      - "VEHICLE"
      - "TRADE_IN"
      - "PRODUCT"
      - "MANUFACTURER"
      - "LEAD"
      - "OPPORTUNITY"
      - "DEAL"
      - "FINANCE"
      - "INVOICE"
      - "LINEITEM"
      - "EXPENSE"
      - "DISCOUNT"
      - "TAX"
      - "FEE"
      - "INCENTIVE"
      - "DEALERSHIP"
      - "APPOINTMENT"
      - "OTHER"
