---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    Codes:
      type: "array"
      description: "List of Codes"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    LifecycleEvent:
      type: "object"
      properties:
        lifecycle_event_id:
          type: "string"
          description: "The unique ID for the lifecycle event."
          nullable: false
          example: "EVT-99887766"
          exampleSetFlag: true
        lifecycle_event_key:
          type: "string"
          description: "The unique external key or business identifier used in integrations."
          nullable: false
          example: "LIFECYCLE-879234"
          exampleSetFlag: true
        actor_href:
          type: "string"
          description: "The href of the actor who initiated the event."
          format: "href"
          nullable: false
          exampleSetFlag: false
        actor_id:
          type: "string"
          description: "The unique identifier of the actor who initiated the event."
          nullable: false
          example: "USR-24681357"
          exampleSetFlag: true
        actor_name:
          type: "string"
          description: "The name of the actor who initiated the event."
          nullable: false
          example: "John Doe"
          exampleSetFlag: true
        lifecycle_event_type:
          description: "The type of lifecycle event."
          $ref: "#/components/schemas/LifecycleEventTypes"
          nullable: false
          exampleSetFlag: false
        occurrence_date:
          type: "string"
          description: "The date and time the event occurred."
          format: "date"
          nullable: false
          exampleSetFlag: false
        resource_href:
          type: "string"
          description: "The href of the resource associated with the event."
          format: "href"
          nullable: false
          exampleSetFlag: false
        resource_identifier:
          type: "string"
          description: "The unique identifier of the resource associated with the\
            \ event."
          nullable: false
          example: "RSC-88776655"
          exampleSetFlag: true
        detail_name:
          type: "string"
          description: "The name of the event detail."
          nullable: false
          example: "Order ID"
          exampleSetFlag: true
        detail_desc:
          type: "string"
          description: "A description of the event detail."
          nullable: false
          example: "The unique ID of the order being processed."
          exampleSetFlag: true
        detail_value:
          type: "string"
          description: "The value of the event detail."
          nullable: false
          example: "ORD-44556677"
          exampleSetFlag: true
        detail_key:
          type: "string"
          description: "The unique key for the event detail."
          nullable: false
          example: "ORDER_ID"
          exampleSetFlag: true
        detail_code:
          type: "string"
          description: "The code for the event detail."
          nullable: false
          example: "ORDER_STATUS_CHANGED"
          exampleSetFlag: true
        resource_types:
          description: "The types of resources associated with the trend."
          $ref: "#/components/schemas/ResourceTypes"
          nullable: false
          exampleSetFlag: false
      description: "Lifecycle Event"
      exampleSetFlag: false
    LifecycleEventTypes:
      type: "string"
      description: "types of lifecycle events."
      extensions:
        x-governance:
          CLOSED:
            sortIndex: 0
            description: "The event of an item or case being closed."
            is_unique: true
            depreciated: false
            published: false
            id: 7
          DELETE_SOFT:
            sortIndex: 0
            description: "The event of an item being logically deleted (m..."
            is_unique: true
            depreciated: false
            published: false
            id: 3
          PROCESSING:
            sortIndex: 0
            description: "The event of an item being in the process of be..."
            is_unique: true
            depreciated: false
            published: false
            id: 12
          UPDATED:
            sortIndex: 0
            description: "The event of an existing item being updated."
            is_unique: true
            depreciated: false
            published: false
            id: 1
          QUALIFIED:
            sortIndex: 0
            description: "The event of an item having been qualified."
            is_unique: true
            depreciated: false
            published: false
            id: 16
          ACCESS_ALLOWED:
            sortIndex: 0
            description: "The event of a user being granted access to a r..."
            is_unique: true
            depreciated: false
            published: false
            id: 4
          INITIALIZING:
            sortIndex: 0
            description: "The event of a new item being in the process of..."
            is_unique: true
            depreciated: false
            published: false
            id: 11
          DELETE_HARD:
            sortIndex: 0
            description: "The event of an item being permanently deleted."
            is_unique: true
            depreciated: false
            published: false
            id: 2
          CANCELLED:
            sortIndex: 0
            description: "The event of an item being cancelled."
            is_unique: true
            depreciated: false
            published: false
            id: 8
          CREATED:
            sortIndex: 0
            description: "The event of a new item being created."
            is_unique: true
            depreciated: false
            published: false
            id: 0
          ACCESS_DENIED:
            sortIndex: 0
            description: "The event of a user being denied access to a re..."
            is_unique: true
            depreciated: false
            published: false
            id: 5
          FAILED:
            sortIndex: 0
            description: "The event of an item failing to be processed."
            is_unique: true
            depreciated: false
            published: false
            id: 14
          INITIALIZED:
            sortIndex: 0
            description: "The event of a new item being initialized."
            is_unique: true
            depreciated: false
            published: false
            id: 10
          PROCESSED:
            sortIndex: 0
            description: "The event of an item having successfully comple..."
            is_unique: true
            depreciated: false
            published: false
            id: 13
          SUBMITTED:
            sortIndex: 0
            description: "The event of an item being submitted for proces..."
            is_unique: true
            depreciated: false
            published: false
            id: 6
          DEAD:
            sortIndex: 0
            description: "The event of an item becoming inactive or obsol..."
            is_unique: true
            depreciated: false
            published: false
            id: 9
          VALIDATED:
            sortIndex: 0
            description: "The event of an item having been validated."
            is_unique: true
            depreciated: false
            published: false
            id: 15
      exampleSetFlag: false
      enum:
      - "CREATED"
      - "UPDATED"
      - "DELETE_HARD"
      - "DELETE_SOFT"
      - "ACCESS_ALLOWED"
      - "ACCESS_DENIED"
      - "SUBMITTED"
      - "CLOSED"
      - "CANCELLED"
      - "DEAD"
      - "INITIALIZED"
      - "INITIALIZING"
      - "PROCESSING"
      - "PROCESSED"
      - "FAILED"
      - "VALIDATED"
      - "QUALIFIED"
    Link:
      type: "array"
      description: "Quick Link"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    Links:
      type: "array"
      description: "List of Links"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    ResourceTypes:
      type: "string"
      description: "types of resources."
      extensions:
        x-governance:
          SYSTEM:
            sortIndex: 0
            description: "Resource type: System."
            is_unique: true
            depreciated: false
            published: false
            id: 0
          PARTY:
            sortIndex: 0
            description: "Resource type: Party."
            is_unique: true
            depreciated: false
            published: false
            id: 6
          INCIDENT:
            sortIndex: 0
            description: "Resource type: Incident."
            is_unique: true
            depreciated: false
            published: false
            id: 5
          DRIVER:
            sortIndex: 0
            description: "Resource type: Driver."
            is_unique: true
            depreciated: false
            published: false
            id: 11
          BILL_ADDRESS:
            sortIndex: 0
            description: "Resource type: Billing address."
            is_unique: true
            depreciated: false
            published: false
            id: 13
          DEALER_STAFF:
            sortIndex: 0
            description: "Resource type: Dealer staff."
            is_unique: true
            depreciated: false
            published: false
            id: 10
          TAX:
            sortIndex: 0
            description: "Resource type: Tax."
            is_unique: true
            depreciated: false
            published: false
            id: 29
          LINEITEM:
            sortIndex: 0
            description: "Resource type: Line item."
            is_unique: true
            depreciated: false
            published: false
            id: 26
          ACCOUNT:
            sortIndex: 0
            description: "Resource type: Account."
            is_unique: true
            depreciated: false
            published: false
            id: 16
          COMM_CHANNEL:
            sortIndex: 0
            description: "Resource type: Communication channel."
            is_unique: true
            depreciated: false
            published: false
            id: 15
          FINANCE:
            sortIndex: 0
            description: "Resource type: Finance."
            is_unique: true
            depreciated: false
            published: false
            id: 24
          PRODUCT:
            sortIndex: 0
            description: "Resource type: Product."
            is_unique: true
            depreciated: false
            published: false
            id: 19
          PROCESS:
            sortIndex: 0
            description: "Resource type: Process."
            is_unique: true
            depreciated: false
            published: false
            id: 4
          APPOINTMENT:
            sortIndex: 0
            description: "Resource type: Appointment."
            is_unique: true
            depreciated: false
            published: false
            id: 33
          CUSTOMER:
            sortIndex: 0
            description: "Resource type: Customer."
            is_unique: true
            depreciated: false
            published: false
            id: 7
          INCENTIVE:
            sortIndex: 0
            description: "Resource type: Incentive."
            is_unique: true
            depreciated: false
            published: false
            id: 31
          VEHICLE:
            sortIndex: 0
            description: "Resource type: Vehicle."
            is_unique: true
            depreciated: false
            published: false
            id: 17
          APPLICANT:
            sortIndex: 0
            description: "Resource type: Applicant."
            is_unique: true
            depreciated: false
            published: false
            id: 8
          FEE:
            sortIndex: 0
            description: "Resource type: Fee."
            is_unique: true
            depreciated: false
            published: false
            id: 30
          TRADE_IN:
            sortIndex: 0
            description: "Resource type: Trade-in."
            is_unique: true
            depreciated: false
            published: false
            id: 18
          MANUFACTURER:
            sortIndex: 0
            description: "Resource type: Manufacturer."
            is_unique: true
            depreciated: false
            published: false
            id: 20
          INVOICE:
            sortIndex: 0
            description: "Resource type: Invoice."
            is_unique: true
            depreciated: false
            published: false
            id: 25
          FUNCTION:
            sortIndex: 0
            description: "Resource type: Function."
            is_unique: true
            depreciated: false
            published: false
            id: 3
          DISCOUNT:
            sortIndex: 0
            description: "Resource type: Discount."
            is_unique: true
            depreciated: false
            published: false
            id: 28
          OTHER:
            sortIndex: 0
            description: "Resource type: Other."
            is_unique: true
            depreciated: false
            published: false
            id: 34
          DEAL:
            sortIndex: 0
            description: "Resource type: Deal."
            is_unique: true
            depreciated: false
            published: false
            id: 23
          ADDRESS:
            sortIndex: 0
            description: "Resource type: Address."
            is_unique: true
            depreciated: false
            published: false
            id: 12
          DEALERSHIP:
            sortIndex: 0
            description: "Resource type: Dealership."
            is_unique: true
            depreciated: false
            published: false
            id: 32
          EXPENSE:
            sortIndex: 0
            description: "Resource type: Expense."
            is_unique: true
            depreciated: false
            published: false
            id: 27
          VENDOR:
            sortIndex: 0
            description: "Resource type: Vendor."
            is_unique: true
            depreciated: false
            published: false
            id: 9
          BILL_CONTACT:
            sortIndex: 0
            description: "Resource type: Billing contact."
            is_unique: true
            depreciated: false
            published: false
            id: 14
          OPPORTUNITY:
            sortIndex: 0
            description: "Resource type: Opportunity."
            is_unique: true
            depreciated: false
            published: false
            id: 22
          WORKFLOW:
            sortIndex: 0
            description: "Resource type: Workflow."
            is_unique: true
            depreciated: false
            published: false
            id: 1
          ACTIVITY:
            sortIndex: 0
            description: "Resource type: Activity."
            is_unique: true
            depreciated: false
            published: false
            id: 2
          LEAD:
            sortIndex: 0
            description: "Resource type: Lead."
            is_unique: true
            depreciated: false
            published: false
            id: 21
      exampleSetFlag: false
      enum:
      - "SYSTEM"
      - "WORKFLOW"
      - "ACTIVITY"
      - "FUNCTION"
      - "PROCESS"
      - "INCIDENT"
      - "PARTY"
      - "CUSTOMER"
      - "APPLICANT"
      - "VENDOR"
      - "DEALER_STAFF"
      - "DRIVER"
      - "ADDRESS"
      - "BILL_ADDRESS"
      - "BILL_CONTACT"
      - "COMM_CHANNEL"
      - "ACCOUNT"
      - "VEHICLE"
      - "TRADE_IN"
      - "PRODUCT"
      - "MANUFACTURER"
      - "LEAD"
      - "OPPORTUNITY"
      - "DEAL"
      - "FINANCE"
      - "INVOICE"
      - "LINEITEM"
      - "EXPENSE"
      - "DISCOUNT"
      - "TAX"
      - "FEE"
      - "INCENTIVE"
      - "DEALERSHIP"
      - "APPOINTMENT"
      - "OTHER"
