---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    Codes:
      type: "array"
      items:
        type: "string"
    ControlAccount:
      type: "object"
      properties:
        identifiers:
          $ref: "#/components/schemas/Identifiers"
        control_account_desc:
          maxLength: 255
          type: "string"
          description: "Description of the control account."
        control_account_id:
          maximum: 100
          minimum: 0
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier for the control accoun... Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
        control_account_key:
          maximum: 100
          minimum: 0
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Business key for the control account. Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
        control_account_name:
          maxLength: 100
          type: "string"
          description: "Display name of the control account."
        control_account_type:
          $ref: "#/components/schemas/ControlAccountTypes"
        control_type_id:
          type: "string"
          description: "Identifier for the control type of the a..."
        bank_account_id:
          type: "string"
          description: "Associated bank account identifier."
        is_counted:
          type: "boolean"
          description: "Indicates if the account is a counted ac..."
        prefix:
          type: "string"
          description: "The prefix of the account number."
        control_account_role_type:
          $ref: "#/components/schemas/ControlAccountRoleTypes"
        control_account_status_types:
          $ref: "#/components/schemas/ControlAccountStatusTypes"
        financial_category_type:
          $ref: "#/components/schemas/FinancialCategoryTypes"
      description: "Journal entry for general ledger, capturing control account details\
        \ including identifiers, type, and descriptive fields."
    ControlAccountRoleTypes:
      type: "string"
      description: "types of control account roles."
      enum:
      - "MASTER"
      - "SUB"
      - "SPLIT"
      - "STANDARD"
      - "OTHER"
    ControlAccountStatusTypes:
      type: "string"
      description: "types of control account status."
      enum:
      - "INITIALIZE"
      - "CREATED"
      - "ACTIVATE"
      - "ACTIVE"
      - "SUSPEND_FOR_REVIEW"
      - "REACTIVATE"
      - "SUSPENDED"
      - "PERMANENTLY_CLOSED"
      - "RETIRE"
      - "TERMINATED"
    ControlAccountTypes:
      type: "string"
      description: "types of control accounts."
      enum:
      - "ASSETS"
      - "FIXED_ASSETS"
      - "CONTRA_ASSET"
      - "LIABILITY"
      - "LONG_TERM_LIABILITY"
      - "EQUITY"
      - "CLEARING"
      - "PROVISION"
      - "ROUNDING"
      - "REVENUE"
      - "OTHER_INCOME"
      - "COGS"
      - "EXPENSE"
      - "DEPRECIATION"
      - "TAX"
      - "DISCOUNT"
      - "REBATE"
      - "FEE"
      - "SERVICE"
      - "CREDIT"
      - "OTHER"
      - "DEALER"
      - "VEHICLE"
      - "ACCESSORIES"
      - "OPTION"
      - "CUSTOMER"
      - "VENDOR"
      - "EMPLOYEE"
      - "PRODUCT"
      - "REPAIR_ORDER"
      - "PARTS_SALES_ORDER"
      - "PACKAGE"
      - "REFERENCE"
    FinancialCategoryTypes:
      type: "string"
      description: "types of financial categorys."
      enum:
      - "CAPEX"
      - "OPEX"
      - "HARDWARE"
      - "SOFTWARE"
      - "MAINTENANCE"
      - "TRAVEL"
      - "TRAINING"
      - "UTILITIES"
      - "RENT"
      - "SALARY"
      - "REVENUE"
      - "TAX"
      - "OTHER"
    Identifier:
      type: "object"
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
        identifier_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Business key for the identifier Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
        context:
          type: "string"
          description: "Context or domain of the identifier"
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
        system_codes:
          $ref: "#/components/schemas/Codes"
      description: "External system identifier"
    Identifiers:
      type: "array"
      items:
        $ref: "#/components/schemas/Identifier"
