---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    Codes:
      type: "array"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    ControlAccount:
      type: "object"
      properties:
        identifiers:
          $ref: "#/components/schemas/Identifiers"
          exampleSetFlag: false
        control_account_desc:
          maxLength: 255
          type: "string"
          description: "Description of the control account."
          exampleSetFlag: false
        control_account_id:
          maximum: 100
          minimum: 0
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier for the control accoun... Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
          exampleSetFlag: false
        control_account_key:
          maximum: 100
          minimum: 0
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Business key for the control account. Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
          exampleSetFlag: false
        control_account_name:
          maxLength: 100
          type: "string"
          description: "Display name of the control account."
          exampleSetFlag: false
        control_account_type:
          $ref: "#/components/schemas/ControlAccountTypes"
          exampleSetFlag: false
        control_type_id:
          type: "string"
          description: "Identifier for the control type of the a..."
          exampleSetFlag: false
        bank_account_id:
          type: "string"
          description: "Associated bank account identifier."
          exampleSetFlag: false
        is_counted:
          type: "boolean"
          description: "Indicates if the account is a counted ac..."
          exampleSetFlag: false
        prefix:
          type: "string"
          description: "The prefix of the account number."
          exampleSetFlag: false
        control_account_role_type:
          $ref: "#/components/schemas/ControlAccountRoleTypes"
          exampleSetFlag: false
        control_account_status_types:
          $ref: "#/components/schemas/ControlAccountStatusTypes"
          exampleSetFlag: false
        financial_category_type:
          $ref: "#/components/schemas/FinancialCategoryTypes"
          exampleSetFlag: false
      description: "Journal entry for general ledger, capturing control account details\
        \ including identifiers, type, and descriptive fields."
      exampleSetFlag: false
    ControlAccountCreate:
      required:
      - "control_account_key"
      type: "object"
      description: "ControlAccount Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/ControlAccount"
        exampleSetFlag: false
    ControlAccountRoleTypes:
      type: "string"
      description: "types of control account roles."
      exampleSetFlag: false
      enum:
      - "MASTER"
      - "SUB"
      - "SPLIT"
      - "STANDARD"
      - "OTHER"
    ControlAccountStatusTypes:
      type: "string"
      description: "types of control account status."
      exampleSetFlag: false
      enum:
      - "INITIALIZE"
      - "CREATED"
      - "ACTIVATE"
      - "ACTIVE"
      - "SUSPEND_FOR_REVIEW"
      - "REACTIVATE"
      - "SUSPENDED"
      - "PERMANENTLY_CLOSED"
      - "RETIRE"
      - "TERMINATED"
    ControlAccountTypes:
      type: "string"
      description: "types of control accounts."
      exampleSetFlag: false
      enum:
      - "ASSETS"
      - "FIXED_ASSETS"
      - "CONTRA_ASSET"
      - "LIABILITY"
      - "LONG_TERM_LIABILITY"
      - "EQUITY"
      - "CLEARING"
      - "PROVISION"
      - "ROUNDING"
      - "REVENUE"
      - "OTHER_INCOME"
      - "COGS"
      - "EXPENSE"
      - "DEPRECIATION"
      - "TAX"
      - "DISCOUNT"
      - "REBATE"
      - "FEE"
      - "SERVICE"
      - "CREDIT"
      - "OTHER"
      - "DEALER"
      - "VEHICLE"
      - "ACCESSORIES"
      - "OPTION"
      - "CUSTOMER"
      - "VENDOR"
      - "EMPLOYEE"
      - "PRODUCT"
      - "REPAIR_ORDER"
      - "PARTS_SALES_ORDER"
      - "PACKAGE"
      - "REFERENCE"
    ControlAccountUpdate:
      type: "object"
      properties:
        control_account_role_type:
          $ref: "#/components/schemas/ControlAccountRoleTypes"
          exampleSetFlag: false
        identifiers:
          $ref: "#/components/schemas/Identifiers"
          exampleSetFlag: false
        prefix:
          type: "string"
          description: "The prefix of the account number."
          exampleSetFlag: false
        control_account_desc:
          maxLength: 255
          type: "string"
          description: "Description of the control account."
          exampleSetFlag: false
        control_account_type:
          $ref: "#/components/schemas/ControlAccountTypes"
          exampleSetFlag: false
        control_account_status_types:
          $ref: "#/components/schemas/ControlAccountStatusTypes"
          exampleSetFlag: false
        is_counted:
          type: "boolean"
          description: "Indicates if the account is a counted ac..."
          exampleSetFlag: false
        control_account_name:
          maxLength: 100
          type: "string"
          description: "Display name of the control account."
          exampleSetFlag: false
        financial_category_type:
          $ref: "#/components/schemas/FinancialCategoryTypes"
          exampleSetFlag: false
      description: "ControlAccount Update for Patch and Put"
      exampleSetFlag: false
    FinancialCategoryTypes:
      type: "string"
      description: "types of financial categorys."
      exampleSetFlag: false
      enum:
      - "CAPEX"
      - "OPEX"
      - "HARDWARE"
      - "SOFTWARE"
      - "MAINTENANCE"
      - "TRAVEL"
      - "TRAINING"
      - "UTILITIES"
      - "RENT"
      - "SALARY"
      - "REVENUE"
      - "TAX"
      - "OTHER"
    Identifier:
      type: "object"
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        identifier_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Business key for the identifier Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          exampleSetFlag: false
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
      description: "External system identifier"
      exampleSetFlag: false
    IdentifierCreate:
      required:
      - "identifier_key"
      type: "object"
      description: "Identifier Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/Identifier"
        exampleSetFlag: false
    IdentifierUpdate:
      type: "object"
      properties:
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          exampleSetFlag: false
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
      description: "Identifier Update for Patch and Put"
      exampleSetFlag: false
    Identifiers:
      type: "array"
      exampleSetFlag: false
      items:
        $ref: "#/components/schemas/Identifier"
        exampleSetFlag: false
