---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths:
  /control-accounts:
    get:
      tags:
      - "ControlAccount"
      summary: "Retrieve a list of all ControlAccount records."
      operationId: "listControlAccounts"
      parameters:
      - name: "limit"
        in: "query"
        description: "Maximum number of records to return. (For pagination)"
        schema:
          maximum: 100
          minimum: 1
          type: "integer"
          default: 50
      - name: "cursor"
        in: "query"
        description: "A token or value representing the starting point for the next\
          \ set of results. (For cursor-based pagination)"
        schema:
          type: "string"
      responses:
        "200":
          description: "A list of ControlAccount records."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/ControlAccount"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"
    post:
      tags:
      - "ControlAccount"
      summary: "Create a new ControlAccount record."
      operationId: "createControlAccount"
      requestBody:
        description: "ControlAccount data to create the new resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ControlAccount_Create"
        required: true
      responses:
        "201":
          description: "ControlAccount created successfully."
          headers:
            Location:
              description: "The URI of the newly created resource."
              schema:
                type: "string"
                example: "//control-accounts/PR-1234567"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ControlAccount"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "409":
          $ref: "#/components/responses/ConflictError"
  /control-accounts/{controlAccountKey}:
    get:
      tags:
      - "ControlAccount"
      summary: "Retrieve a specific ControlAccount record."
      operationId: "getControlAccountById"
      responses:
        "200":
          description: "The requested ControlAccount record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ControlAccount"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    put:
      tags:
      - "ControlAccount"
      summary: "replace a ControlAccount record."
      operationId: "replaceControlAccount"
      requestBody:
        description: "Fields to be updated. Only included fields will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ControlAccount"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ControlAccount"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    delete:
      tags:
      - "ControlAccount"
      summary: "Delete a ControlAccount Record"
      description: "Marks the ControlAccount record as inactive or removes it entirely."
      operationId: "deleteControlAccountRecord"
      responses:
        "204":
          description: "Record successfully deleted (or deactivated)."
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    patch:
      tags:
      - "ControlAccount"
      summary: "Partially update a ControlAccount record."
      operationId: "updateControlAccount"
      requestBody:
        description: "Fields to be updated. Only included fields will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ControlAccount_Update"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ControlAccount"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    parameters:
    - name: "controlAccountKey"
      in: "path"
      description: "The unique identifier for the specific ControlAccount."
      required: true
      schema:
        type: "string"
        example: "PR-1234567"
  /control-accounts/{controlAccountKey}/identifiers:
    get:
      tags:
      - "Identifier"
      summary: "Retrieve a list of all Identifier records."
      operationId: "listIdentifiers"
      parameters:
      - name: "limit"
        in: "query"
        description: "Maximum number of records to return. (For pagination)"
        schema:
          maximum: 100
          minimum: 1
          type: "integer"
          default: 50
      - name: "cursor"
        in: "query"
        description: "A token or value representing the starting point for the next\
          \ set of results. (For cursor-based pagination)"
        schema:
          type: "string"
      responses:
        "200":
          description: "A list of Identifier records."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Identifier"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"
    post:
      tags:
      - "Identifier"
      summary: "Create a new Identifier record."
      operationId: "createIdentifier"
      requestBody:
        description: "Identifier data to create the new resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Identifier_Create"
        required: true
      responses:
        "201":
          description: "Identifier created successfully."
          headers:
            Location:
              description: "The URI of the newly created resource."
              schema:
                type: "string"
                example: "//control-accounts/{controlAccountKey}/identifiers/PR-1234567"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identifier"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "409":
          $ref: "#/components/responses/ConflictError"
  /control-accounts/{controlAccountKey}/identifiers/{identifierKey}:
    get:
      tags:
      - "Identifier"
      summary: "Retrieve a specific Identifier record."
      operationId: "getIdentifierById"
      responses:
        "200":
          description: "The requested Identifier record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identifier"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    put:
      tags:
      - "Identifier"
      summary: "replace a Identifier record."
      operationId: "replaceIdentifier"
      requestBody:
        description: "Fields to be updated. Only included fields will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Identifier"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identifier"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    delete:
      tags:
      - "Identifier"
      summary: "Delete a Identifier Record"
      description: "Marks the Identifier record as inactive or removes it entirely."
      operationId: "deleteIdentifierRecord"
      responses:
        "204":
          description: "Record successfully deleted (or deactivated)."
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    patch:
      tags:
      - "Identifier"
      summary: "Partially update a Identifier record."
      operationId: "updateIdentifier"
      requestBody:
        description: "Fields to be updated. Only included fields will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Identifier_Update"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the updated record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identifier"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    parameters:
    - name: "identifierKey"
      in: "path"
      description: "The unique identifier for the specific Identifier."
      required: true
      schema:
        type: "string"
        example: "PR-1234567"
        exampleSetFlag: true
components:
  schemas: {}
