---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    Codes:
      type: "array"
      description: "List of Codes"
      items:
        type: "string"
    FinancialCategoryTypes:
      type: "string"
      description: "types of financial categorys."
      extensions:
        x-governance:
          MAINTENANCE:
            description: "Financial category: Maintenance."
            published: false
            is_unique: true
            sortIndex: 0
            id: 4
            depreciated: false
          RENT:
            description: "Financial category: Rent."
            published: false
            is_unique: true
            sortIndex: 0
            id: 8
            depreciated: false
          SOFTWARE:
            description: "Financial category: Software."
            published: false
            is_unique: true
            sortIndex: 0
            id: 3
            depreciated: false
          CAPEX:
            description: "Financial category: Capital expenditure (CAPEX)."
            published: false
            is_unique: true
            sortIndex: 0
            id: 0
            depreciated: false
          SALARY:
            description: "Financial category: Salary."
            published: false
            is_unique: true
            sortIndex: 0
            id: 9
            depreciated: false
          TAX:
            description: "Financial category: Tax."
            published: false
            is_unique: true
            sortIndex: 0
            id: 11
            depreciated: false
          TRAINING:
            description: "Financial category: Training."
            published: false
            is_unique: true
            sortIndex: 0
            id: 6
            depreciated: false
          TRAVEL:
            description: "Financial category: Travel."
            published: false
            is_unique: true
            sortIndex: 0
            id: 5
            depreciated: false
          REVENUE:
            description: "Financial category: Revenue."
            published: false
            is_unique: true
            sortIndex: 0
            id: 10
            depreciated: false
          OPEX:
            description: "Financial category: Operating expenditure (OPEX)."
            published: false
            is_unique: true
            sortIndex: 0
            id: 1
            depreciated: false
          OTHER:
            description: "Financial category: Other."
            published: false
            is_unique: true
            sortIndex: 0
            id: 12
            depreciated: false
          HARDWARE:
            description: "Financial category: Hardware."
            published: false
            is_unique: true
            sortIndex: 0
            id: 2
            depreciated: false
          UTILITIES:
            description: "Financial category: Utilities."
            published: false
            is_unique: true
            sortIndex: 0
            id: 7
            depreciated: false
    GeneralLedgerAccount:
      type: "object"
      properties:
        identifiers:
          description: "List of identifiers associated with this control account."
          $ref: "#/components/schemas/Identifiers"
          nullable: true
        general_ledger_account_desc:
          maxLength: 255
          type: "string"
          description: "Description of the control account."
          nullable: true
        general_ledger_account_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier for the control account. Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
          nullable: true
        general_ledger_account_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Master record for a General Ledger Account (Chart of Accounts),\
            \ capturing its identity, type, and descriptive fields. Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
          nullable: false
        general_ledger_account_name:
          maxLength: 100
          type: "string"
          description: "Display name of the control account."
          nullable: true
        general_ledger_account_type:
          description: "Type of the control account, defining its classification within\
            \ the ledger."
          $ref: "#/components/schemas/GeneralLedgerAccountTypes"
          nullable: true
          
        control_type_id:
          type: "string"
          description: "Identifier for the control type of the account."
          nullable: false
          
        bank_account_id:
          type: "string"
          description: "Associated bank account identifier."
          nullable: false
          
        is_counted:
          type: "boolean"
          description: "Indicates if the account is a counted account (e.g., for inventory)."
          nullable: false
          
        prefix:
          type: "string"
          description: "The prefix of the account number."
          nullable: false
          
        financial_category_type:
          description: "Financial Category Type"
          $ref: "#/components/schemas/FinancialCategoryTypes"
          nullable: true
          
      description: "Master data record for a General Ledger Account, used to define\
        \ the Chart of Accounts."
      
    GeneralLedgerAccountTypes:
      type: "string"
      description: "types of general ledger accounts."
      extensions:
        x-governance:
          CREDIT:
            description: "Credit"
            published: false
            is_unique: true
            sortIndex: 0
            id: 19
            depreciated: false
          DEPRECIATION:
            description: "Depreciation"
            published: false
            is_unique: true
            sortIndex: 0
            id: 13
            depreciated: false
          OTHER_INCOME:
            description: "Other Income"
            published: false
            is_unique: true
            sortIndex: 0
            id: 10
            depreciated: false
          VENDOR:
            description: "Vendor Account"
            published: false
            is_unique: true
            sortIndex: 0
            id: 26
            depreciated: false
          ROUNDING:
            description: "Rounding Account"
            published: false
            is_unique: true
            sortIndex: 0
            id: 8
            depreciated: false
          CONTRA_ASSET:
            description: "Contra-Asset"
            published: false
            is_unique: true
            sortIndex: 0
            id: 2
            depreciated: false
          REPAIR_ORDER:
            description: "Repair Order (WIP)"
            published: false
            is_unique: true
            sortIndex: 0
            id: 29
            depreciated: false
          REVENUE:
            description: "Revenue"
            published: false
            is_unique: true
            sortIndex: 0
            id: 9
            depreciated: false
          EXPENSE:
            description: "Expense"
            published: false
            is_unique: true
            sortIndex: 0
            id: 12
            depreciated: false
          OTHER:
            description: "Other General Ledger Account"
            published: false
            is_unique: true
            sortIndex: 0
            id: 20
            depreciated: false
          OPTION:
            description: "Option"
            published: false
            is_unique: true
            sortIndex: 0
            id: 24
            depreciated: false
          ASSETS:
            description: "Assets"
            published: false
            is_unique: true
            sortIndex: 0
            id: 0
            depreciated: false
          PACKAGE:
            description: "Package"
            published: false
            is_unique: true
            sortIndex: 0
            id: 31
            depreciated: false
          PROVISION:
            description: "Provision"
            published: false
            is_unique: true
            sortIndex: 0
            id: 7
            depreciated: false
          FIXED_ASSETS:
            description: "Fixed Assets"
            published: false
            is_unique: true
            sortIndex: 0
            id: 1
            depreciated: false
          EMPLOYEE:
            description: "Employee Payable/Receivable"
            published: false
            is_unique: true
            sortIndex: 0
            id: 27
            depreciated: false
          LONG_TERM_LIABILITY:
            description: "Long-Term Liability"
            published: false
            is_unique: true
            sortIndex: 0
            id: 4
            depreciated: false
          LIABILITY:
            description: "Liability"
            published: false
            is_unique: true
            sortIndex: 0
            id: 3
            depreciated: false
          FEE:
            description: "Fee"
            published: false
            is_unique: true
            sortIndex: 0
            id: 17
            depreciated: false
          PRODUCT:
            description: "Product Inventory"
            published: false
            is_unique: true
            sortIndex: 0
            id: 28
            depreciated: false
          EQUITY:
            description: "Equity"
            published: false
            is_unique: true
            sortIndex: 0
            id: 5
            depreciated: false
          COGS:
            description: "Cost of Goods Sold (COGS)"
            published: false
            is_unique: true
            sortIndex: 0
            id: 11
            depreciated: false
          CLEARING:
            description: "Clearing Account"
            published: false
            is_unique: true
            sortIndex: 0
            id: 6
            depreciated: false
          DEALER:
            description: "Dealer"
            published: false
            is_unique: true
            sortIndex: 0
            id: 21
            depreciated: false
          REFERENCE:
            description: "Reference Account"
            published: false
            is_unique: true
            sortIndex: 0
            id: 32
            depreciated: false
          SERVICE:
            description: "Service Income"
            published: false
            is_unique: true
            sortIndex: 0
            id: 18
            depreciated: false
          CUSTOMER:
            description: "Customer Account"
            published: false
            is_unique: true
            sortIndex: 0
            id: 25
            depreciated: false
          ACCESSORIES:
            description: "Accessories Inventory"
            published: false
            is_unique: true
            sortIndex: 0
            id: 23
            depreciated: false
          REBATE:
            description: "Rebate"
            published: false
            is_unique: true
            sortIndex: 0
            id: 16
            depreciated: false
          DISCOUNT:
            description: "Discount"
            published: false
            is_unique: true
            sortIndex: 0
            id: 15
            depreciated: false
          TAX:
            description: "Tax Payable/Expense"
            published: false
            is_unique: true
            sortIndex: 0
            id: 14
            depreciated: false
          VEHICLE:
            description: "Vehicle Inventory"
            published: false
            is_unique: true
            sortIndex: 0
            id: 22
            depreciated: false
          PARTS_SALES_ORDER:
            description: "Parts Sales Order (WIP)"
            published: false
            is_unique: true
            sortIndex: 0
            id: 30
            depreciated: false
    GeneralLedgerAccount_Create:
      required:
      - "general_ledger_account_key"
      type: "object"
      description: "GeneralLedgerAccount Create for Post"
      exampleSetFlag: true
      allOf:
      - $ref: "#/components/schemas/GeneralLedgerAccount"
        
    GeneralLedgerAccount_Update:
      type: "object"
      properties:
        general_ledger_account_desc:
          maxLength: 255
          type: "string"
          description: "Description of the control account."
          nullable: true
          
        general_ledger_account_type:
          description: "Type of the control account, defining its classification within\
            \ the ledger."
          $ref: "#/components/schemas/GeneralLedgerAccountTypes"
          nullable: true
          
        identifiers:
          description: "List of identifiers associated with this control account."
          $ref: "#/components/schemas/Identifiers"
          nullable: true
          
        prefix:
          type: "string"
          description: "The prefix of the account number."
          nullable: false
          
        general_ledger_account_name:
          maxLength: 100
          type: "string"
          description: "Display name of the control account."
          nullable: true
          
        is_counted:
          type: "boolean"
          description: "Indicates if the account is a counted account (e.g., for inventory)."
          nullable: false
          
        financial_category_type:
          description: "Financial Category Type"
          $ref: "#/components/schemas/FinancialCategoryTypes"
          nullable: true
          
      description: "GeneralLedgerAccount Update for Patch and Put"
      exampleSetFlag: true
    Identifier:
      type: "object"
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          nullable: false
          
        identifier_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Business key for the identifier Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          nullable: false
          
        context:
          type: "string"
          description: "Context or domain of the identifier"
          nullable: true
          
        value:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
          
        detail:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
          
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
          
        system_codes:
          description: "Associated system codes for this identifier"
          $ref: "#/components/schemas/Codes"
          nullable: true
          
      description: "External system identifier"
      
    Identifier_Create:
      required:
      - "identifier_key"
      type: "object"
      description: "Identifier Create for Post"
      exampleSetFlag: true
      allOf:
      - $ref: "#/components/schemas/Identifier"
        
    Identifier_Update:
      type: "object"
      properties:
        system_codes:
          description: "Associated system codes for this identifier"
          $ref: "#/components/schemas/Codes"
          nullable: true
          
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
          
        context:
          type: "string"
          description: "Context or domain of the identifier"
          nullable: true
          
        detail:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
          
        value:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
          
      description: "Identifier Update for Patch and Put"
      exampleSetFlag: true
    Identifiers:
      type: "array"
      description: "List of Identifier"
      
      items:
        $ref: "#/components/schemas/Identifier"
        
    Identifiers_Create:
      type: "array"
      description: "Identifiers Create for Post"
      exampleSetFlag: true
      allOf:
      - $ref: "#/components/schemas/Identifiers"
        
    Identifiers_Update:
      type: "array"
      description: "Identifiers Update for Patch and Put"
      exampleSetFlag: true
    Link:
      type: "array"
      description: "Quick Link"
      
      items:
        type: "string"
        
    Links:
      type: "array"
      description: "List of Links"
      
      items:
        type: "string"
        
