---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    Codes:
      type: "array"
      description: "List of Codes"
      items:
        type: "string"
    FinancialCategoryTypes:
      type: "string"
      description: "types of financial categorys."
      extensions:
        x-governance:
          TRAVEL:
            sortIndex: 0
            description: "Financial category: Travel."
            is_unique: true
            depreciated: false
            published: false
            id: 5
          REVENUE:
            sortIndex: 0
            description: "Financial category: Revenue."
            is_unique: true
            depreciated: false
            published: false
            id: 10
          TAX:
            sortIndex: 0
            description: "Financial category: Tax."
            is_unique: true
            depreciated: false
            published: false
            id: 11
          CAPEX:
            sortIndex: 0
            description: "Financial category: Capital expenditure (CAPEX)."
            is_unique: true
            depreciated: false
            published: false
            id: 0
          SOFTWARE:
            sortIndex: 0
            description: "Financial category: Software."
            is_unique: true
            depreciated: false
            published: false
            id: 3
          TRAINING:
            sortIndex: 0
            description: "Financial category: Training."
            is_unique: true
            depreciated: false
            published: false
            id: 6
          OTHER:
            sortIndex: 0
            description: "Financial category: Other."
            is_unique: true
            depreciated: false
            published: false
            id: 12
          OPEX:
            sortIndex: 0
            description: "Financial category: Operating expenditure (OPEX)."
            is_unique: true
            depreciated: false
            published: false
            id: 1
          MAINTENANCE:
            sortIndex: 0
            description: "Financial category: Maintenance."
            is_unique: true
            depreciated: false
            published: false
            id: 4
          SALARY:
            sortIndex: 0
            description: "Financial category: Salary."
            is_unique: true
            depreciated: false
            published: false
            id: 9
          UTILITIES:
            sortIndex: 0
            description: "Financial category: Utilities."
            is_unique: true
            depreciated: false
            published: false
            id: 7
          HARDWARE:
            sortIndex: 0
            description: "Financial category: Hardware."
            is_unique: true
            depreciated: false
            published: false
            id: 2
          RENT:
            sortIndex: 0
            description: "Financial category: Rent."
            is_unique: true
            depreciated: false
            published: false
            id: 8
    GeneralLedgerAccount:
      type: "object"
      properties:
        identifiers:
          description: "List of identifiers associated with this control account."
          $ref: "#/components/schemas/Identifiers"
          nullable: true
        general_ledger_account_desc:
          maxLength: 255
          type: "string"
          description: "Description of the control account."
          nullable: true
        general_ledger_account_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier for the control account. Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
          nullable: true
          
        general_ledger_account_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Master record for a General Ledger Account (Chart of Accounts),\
            \ capturing its identity, type, and descriptive fields. Pattern: ^[a-zA-Z0-9_]+$\
            \ (Alphanumeric and underscores allowed)"
          nullable: false
        general_ledger_account_name:
          maxLength: 100
          type: "string"
          description: "Display name of the control account."
          nullable: true
          
        general_ledger_account_type:
          description: "Type of the control account, defining its classification within\
            \ the ledger."
          $ref: "#/components/schemas/GeneralLedgerAccountTypes"
          nullable: true
          
        control_type_id:
          type: "string"
          description: "Identifier for the control type of the account."
          nullable: false
          
        bank_account_id:
          type: "string"
          description: "Associated bank account identifier."
          nullable: false
          
        is_counted:
          type: "boolean"
          description: "Indicates if the account is a counted account (e.g., for inventory)."
          nullable: false
          
        prefix:
          type: "string"
          description: "The prefix of the account number."
          nullable: false
          
        financial_category_type:
          description: "Financial Category Type"
          $ref: "#/components/schemas/FinancialCategoryTypes"
          nullable: true
          
      description: "Master data record for a General Ledger Account, used to define\
        \ the Chart of Accounts."
      
    GeneralLedgerAccountTypes:
      type: "string"
      description: "types of general ledger accounts."
      extensions:
        x-governance:
          CREDIT:
            sortIndex: 0
            description: "Credit"
            is_unique: true
            depreciated: false
            published: false
            id: 19
          COGS:
            sortIndex: 0
            description: "Cost of Goods Sold (COGS)"
            is_unique: true
            depreciated: false
            published: false
            id: 11
          TAX:
            sortIndex: 0
            description: "Tax Payable/Expense"
            is_unique: true
            depreciated: false
            published: false
            id: 14
          PROVISION:
            sortIndex: 0
            description: "Provision"
            is_unique: true
            depreciated: false
            published: false
            id: 7
          FIXED_ASSETS:
            sortIndex: 0
            description: "Fixed Assets"
            is_unique: true
            depreciated: false
            published: false
            id: 1
          REPAIR_ORDER:
            sortIndex: 0
            description: "Repair Order (WIP)"
            is_unique: true
            depreciated: false
            published: false
            id: 29
          PRODUCT:
            sortIndex: 0
            description: "Product Inventory"
            is_unique: true
            depreciated: false
            published: false
            id: 28
          PACKAGE:
            sortIndex: 0
            description: "Package"
            is_unique: true
            depreciated: false
            published: false
            id: 31
          REFERENCE:
            sortIndex: 0
            description: "Reference Account"
            is_unique: true
            depreciated: false
            published: false
            id: 32
          CUSTOMER:
            sortIndex: 0
            description: "Customer Account"
            is_unique: true
            depreciated: false
            published: false
            id: 25
          SERVICE:
            sortIndex: 0
            description: "Service Income"
            is_unique: true
            depreciated: false
            published: false
            id: 18
          OTHER_INCOME:
            sortIndex: 0
            description: "Other Income"
            is_unique: true
            depreciated: false
            published: false
            id: 10
          EQUITY:
            sortIndex: 0
            description: "Equity"
            is_unique: true
            depreciated: false
            published: false
            id: 5
          ASSETS:
            sortIndex: 0
            description: "Assets"
            is_unique: true
            depreciated: false
            published: false
            id: 0
          CONTRA_ASSET:
            sortIndex: 0
            description: "Contra-Asset"
            is_unique: true
            depreciated: false
            published: false
            id: 2
          VEHICLE:
            sortIndex: 0
            description: "Vehicle Inventory"
            is_unique: true
            depreciated: false
            published: false
            id: 22
          REVENUE:
            sortIndex: 0
            description: "Revenue"
            is_unique: true
            depreciated: false
            published: false
            id: 9
          EMPLOYEE:
            sortIndex: 0
            description: "Employee Payable/Receivable"
            is_unique: true
            depreciated: false
            published: false
            id: 27
          FEE:
            sortIndex: 0
            description: "Fee"
            is_unique: true
            depreciated: false
            published: false
            id: 17
          OPTION:
            sortIndex: 0
            description: "Option"
            is_unique: true
            depreciated: false
            published: false
            id: 24
          LIABILITY:
            sortIndex: 0
            description: "Liability"
            is_unique: true
            depreciated: false
            published: false
            id: 3
          DEALER:
            sortIndex: 0
            description: "Dealer"
            is_unique: true
            depreciated: false
            published: false
            id: 21
          DISCOUNT:
            sortIndex: 0
            description: "Discount"
            is_unique: true
            depreciated: false
            published: false
            id: 15
          OTHER:
            sortIndex: 0
            description: "Other General Ledger Account"
            is_unique: true
            depreciated: false
            published: false
            id: 20
          LONG_TERM_LIABILITY:
            sortIndex: 0
            description: "Long-Term Liability"
            is_unique: true
            depreciated: false
            published: false
            id: 4
          CLEARING:
            sortIndex: 0
            description: "Clearing Account"
            is_unique: true
            depreciated: false
            published: false
            id: 6
          ROUNDING:
            sortIndex: 0
            description: "Rounding Account"
            is_unique: true
            depreciated: false
            published: false
            id: 8
          EXPENSE:
            sortIndex: 0
            description: "Expense"
            is_unique: true
            depreciated: false
            published: false
            id: 12
          VENDOR:
            sortIndex: 0
            description: "Vendor Account"
            is_unique: true
            depreciated: false
            published: false
            id: 26
          REBATE:
            sortIndex: 0
            description: "Rebate"
            is_unique: true
            depreciated: false
            published: false
            id: 16
          ACCESSORIES:
            sortIndex: 0
            description: "Accessories Inventory"
            is_unique: true
            depreciated: false
            published: false
            id: 23
          DEPRECIATION:
            sortIndex: 0
            description: "Depreciation"
            is_unique: true
            depreciated: false
            published: false
            id: 13
          PARTS_SALES_ORDER:
            sortIndex: 0
            description: "Parts Sales Order (WIP)"
            is_unique: true
            depreciated: false
            published: false
            id: 30
      
    Identifier:
      type: "object"
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          nullable: false
          
        identifier_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Business key for the identifier Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          nullable: false
          
        context:
          type: "string"
          description: "Context or domain of the identifier"
          nullable: true
          
        value:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
          
        detail:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
          
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the event."
          nullable: false
          
        system_codes:
          description: "Associated system codes for this identifier"
          $ref: "#/components/schemas/Codes"
          nullable: true
          
      description: "External system identifier"
      
    Identifiers:
      type: "array"
      description: "List of Identifier"
      
      items:
        $ref: "#/components/schemas/Identifier"
        
    Link:
      type: "array"
      description: "Quick Link"
      
      items:
        type: "string"
        
    Links:
      type: "array"
      description: "List of Links"
      
      items:
        type: "string"
        
