---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths:
  /general-ledger-accounts:
    get:
      tags:
      - "GeneralLedgerAccount"
      summary: "Retrieve a list of all GeneralLedgerAccount rec..."
      operationId: "listGeneralLedgerAccounts"
      parameters:
      - name: "limit"
        in: "query"
        description: "Maximum number of records to return."
        schema:
          maximum: 100
          minimum: 1
          type: "integer"
          default: 50
      - name: "cursor"
        in: "query"
        description: "starting point for next set of results"
        schema:
          type: "string"
      responses:
        "200":
          description: "A list of GeneralLedgerAccount records."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/GeneralLedgerAccount"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"
    post:
      tags:
      - "GeneralLedgerAccount"
      summary: "Create a new GeneralLedgerAccount record."
      operationId: "createGeneralLedgerAccount"
      requestBody:
        description: "GeneralLedgerAccount data to create the new res..."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GeneralLedgerAccountCreate"
        required: true
      responses:
        "201":
          description: "GeneralLedgerAccount created successfully."
          headers:
            Location:
              description: "The URI of the newly created resource."
              schema:
                type: "string"
                example: "/general-ledger-accounts/PR-1234567"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralLedgerAccount"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "409":
          $ref: "#/components/responses/ConflictError"
  /general-ledger-accounts/{generalLedgerAccountKey}:
    get:
      tags:
      - "GeneralLedgerAccount"
      summary: "Retrieve a specific GeneralLedgerAccount record."
      operationId: "getGeneralLedgerAccountById"
      responses:
        "200":
          description: "The requested GeneralLedgerAccount record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralLedgerAccount"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    put:
      tags:
      - "GeneralLedgerAccount"
      summary: "Replace a GeneralLedgerAccount record."
      operationId: "replaceGeneralLedgerAccount"
      requestBody:
        description: "Full record data to replace the existing resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GeneralLedgerAccount"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the update..."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralLedgerAccount"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    delete:
      tags:
      - "GeneralLedgerAccount"
      summary: "Delete a GeneralLedgerAccount Record"
      description: "Marks the GeneralLedgerAccount record as inacti..."
      operationId: "deleteGeneralLedgerAccountRecord"
      responses:
        "204":
          description: "Record successfully deleted (or deactivated)."
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    patch:
      tags:
      - "GeneralLedgerAccount"
      summary: "Partially update a GeneralLedgerAccount record."
      operationId: "updateGeneralLedgerAccount"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GeneralLedgerAccountUpdate"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the update..."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralLedgerAccount"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    parameters:
    - name: "generalLedgerAccountKey"
      in: "path"
      description: "The unique identifier for the specific GeneralLedgerAccount."
      required: true
      schema:
        type: "string"
        example: "PR-1234567"
  /general-ledger-accounts/{generalLedgerAccountKey}/identifiers:
    get:
      tags:
      - "Identifier"
      summary: "Retrieve a list of Identifier records scoped by..."
      operationId: "listIdentifiersByGeneralLedgerAccountKey"
      parameters:
      - name: "limit"
        in: "query"
        description: "Maximum number of records to return."
        schema:
          maximum: 100
          minimum: 1
          type: "integer"
          default: 50
      - name: "cursor"
        in: "query"
        description: "starting point for next set of results"
        schema:
          type: "string"
      responses:
        "200":
          description: "A list of Identifier records."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Identifier"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"
    post:
      tags:
      - "Identifier"
      summary: "Create a new Identifier record."
      operationId: "createIdentifier"
      requestBody:
        description: "Identifier data to create the new resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IdentifierCreate"
        required: true
      responses:
        "201":
          description: "Identifier created successfully."
          headers:
            Location:
              description: "The URI of the newly created resource."
              schema:
                type: "string"
                example: "/part-search-results/PS-12345/bill-of-materials/BOM-001"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identifier"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "409":
          $ref: "#/components/responses/ConflictError"
    parameters:
    - name: "generalLedgerAccountKey"
      in: "path"
      description: "The unique identifier for the parent resource."
      required: true
      schema:
        type: "string"
  /general-ledger-accounts/{generalLedgerAccountKey}/identifiers/{identifierKey}:
    get:
      tags:
      - "Identifier"
      summary: "Retrieve a specific Identifier record."
      operationId: "getIdentifierById"
      responses:
        "200":
          description: "The requested Identifier record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identifier"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    put:
      tags:
      - "Identifier"
      summary: "Replace a Identifier record."
      operationId: "replaceIdentifier"
      requestBody:
        description: "Full record data to replace the existing resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Identifier"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the update..."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identifier"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    delete:
      tags:
      - "Identifier"
      summary: "Delete a Identifier Record"
      description: "Marks the Identifier record as inactive or remo..."
      operationId: "deleteIdentifierRecord"
      responses:
        "204":
          description: "Record successfully deleted (or deactivated)."
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    patch:
      tags:
      - "Identifier"
      summary: "Partially update a Identifier record."
      operationId: "updateIdentifier"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IdentifierUpdate"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the update..."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identifier"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    parameters:
    - name: "generalLedgerAccountKey"
      in: "path"
      description: "The unique identifier for the parent resource."
      required: true
      schema:
        type: "string"
    - name: "identifierKey"
      in: "path"
      description: "The unique identifier for the specific Identifier."
      required: true
      schema:
        type: "string"
        example: "PR-1234567"
components:
  schemas:
    Codes:
      type: "array"
      items:
        type: "string"
    ErrorDetail:
      required:
      - "code"
      - "message"
      - "timestamp"
      type: "object"
      properties:
        code:
          type: "string"
          description: "A unique, system-defined error code (e.g., 'AUT..."
          example: "NOT_FOUND_PR"
        message:
          type: "string"
          description: "A human-readable summary providing specific det..."
          example: "Personnel Record with ID PR-1234567 was not found."
        details:
          type: "array"
          description: "Optional array of specific field-level validati..."
          items:
            type: "object"
            properties:
              field:
                type: "string"
                description: "The specific field that failed validation (e.g., 'firstName')."
                example: "payrollId"
              issue:
                type: "string"
                description: "The validation message for the field (e.g., 'must be\
                  \ numeric')."
                example: "must be unique"
        timestamp:
          type: "string"
          description: "The time the error occurred, in ISO 8601 format."
          format: "date-time"
          example: "2025-11-10T10:30:00Z"
      description: "Standard format for all API error responses."
    FinancialCategoryTypes:
      type: "string"
      description: "types of financial categorys."
      enum:
      - "CAPEX"
      - "OPEX"
      - "HARDWARE"
      - "SOFTWARE"
      - "MAINTENANCE"
      - "TRAVEL"
      - "TRAINING"
      - "UTILITIES"
      - "RENT"
      - "SALARY"
      - "REVENUE"
      - "TAX"
      - "OTHER"
    GeneralLedgerAccount:
      type: "object"
      properties:
        identifiers:
          $ref: "#/components/schemas/Identifiers"
        general_ledger_account_desc:
          maxLength: 255
          type: "string"
          description: "Description of the control account."
        general_ledger_account_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier for the control accoun... Pat..."
        general_ledger_account_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Master record for a General Ledger Accou... Pat..."
        general_ledger_account_name:
          maxLength: 100
          type: "string"
          description: "Display name of the control account."
        general_ledger_account_type:
          $ref: "#/components/schemas/GeneralLedgerAccountTypes"
        control_type_id:
          type: "string"
          description: "Identifier for the control type of the a..."
        bank_account_id:
          type: "string"
          description: "Associated bank account identifier."
        is_counted:
          type: "boolean"
          description: "Indicates if the account is a counted ac..."
        prefix:
          type: "string"
          description: "The prefix of the account number."
        financial_category_type:
          $ref: "#/components/schemas/FinancialCategoryTypes"
      description: "Master data record for a General Ledger Account..."
    GeneralLedgerAccountCreate:
      required:
      - "general_ledger_account_key"
      type: "object"
      description: "GeneralLedgerAccount Create for Post"
      allOf:
      - $ref: "#/components/schemas/GeneralLedgerAccount"
    GeneralLedgerAccountTypes:
      type: "string"
      description: "types of general ledger accounts."
      enum:
      - "ASSETS"
      - "BANK_ACCOUNT"
      - "FIXED_ASSETS"
      - "CONTRA_ASSET"
      - "LIABILITY"
      - "CREDIT_CARD_LIABILITY"
      - "LONG_TERM_LIABILITY"
      - "EQUITY"
      - "CLEARING"
      - "CREDIT_CARD_CLEARING"
      - "PROVISION"
      - "ROUNDING"
      - "REVENUE"
      - "OTHER_INCOME"
      - "COGS"
      - "EXPENSE"
      - "DEPRECIATION"
      - "TAX"
      - "DISCOUNT"
      - "REBATE"
      - "FEE"
      - "SERVICE"
      - "CREDIT"
      - "OTHER"
      - "DEALER"
      - "VEHICLE"
      - "ACCESSORIES"
      - "OPTION"
      - "CUSTOMER"
      - "VENDOR"
      - "EMPLOYEE"
      - "PRODUCT"
      - "REPAIR_ORDER"
      - "PARTS_SALES_ORDER"
      - "PACKAGE"
      - "REFERENCE"
    GeneralLedgerAccountUpdate:
      type: "object"
      properties:
        general_ledger_account_desc:
          maxLength: 255
          type: "string"
          description: "Description of the control account."
        general_ledger_account_type:
          $ref: "#/components/schemas/GeneralLedgerAccountTypes"
        identifiers:
          $ref: "#/components/schemas/Identifiers"
        prefix:
          type: "string"
          description: "The prefix of the account number."
        general_ledger_account_name:
          maxLength: 100
          type: "string"
          description: "Display name of the control account."
        is_counted:
          type: "boolean"
          description: "Indicates if the account is a counted ac..."
        financial_category_type:
          $ref: "#/components/schemas/FinancialCategoryTypes"
      description: "GeneralLedgerAccount Update for Patch and Put"
    Identifier:
      type: "object"
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+..."
        identifier_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Business key for the identifier Pattern: ^[a-zA..."
        context:
          type: "string"
          description: "Context or domain of the identifier"
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
        system_codes:
          $ref: "#/components/schemas/Codes"
      description: "External system identifier"
    IdentifierCreate:
      required:
      - "identifier_key"
      type: "object"
      description: "Identifier Create for Post"
      allOf:
      - $ref: "#/components/schemas/Identifier"
    IdentifierUpdate:
      type: "object"
      properties:
        system_codes:
          $ref: "#/components/schemas/Codes"
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
        context:
          type: "string"
          description: "Context or domain of the identifier"
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
      description: "Identifier Update for Patch and Put"
    Identifiers:
      type: "array"
      items:
        $ref: "#/components/schemas/Identifier"
  responses:
    NotFoundError:
      description: "The requested resource was not found."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
    BadRequestError:
      description: "The request was malformed, failed validation, o..."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
    UnauthorizedError:
      description: "Authentication failed. The access token is miss..."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
    ForbiddenError:
      description: "The authenticated user does not have the necess..."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
    ConflictError:
      description: "The request could not be completed because it c..."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
    ServerError:
      description: "An unexpected error occurred on the server whil..."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
