---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths:
  /accounting-periods:
    get:
      tags:
      - "AccountingPeriod"
      summary: "Retrieve a list of all AccountingPeriod records."
      operationId: "listAccountingPeriods"
      parameters:
      - name: "limit"
        in: "query"
        description: "Maximum number of records to return."
        schema:
          maximum: 100
          minimum: 1
          type: "integer"
          default: 50
      - name: "cursor"
        in: "query"
        description: "starting point for next set of results"
        schema:
          type: "string"
      responses:
        "200":
          description: "A list of AccountingPeriod records."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/AccountingPeriod"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"
    post:
      tags:
      - "AccountingPeriod"
      summary: "Create a new AccountingPeriod record."
      operationId: "createAccountingPeriod"
      requestBody:
        description: "AccountingPeriod data to create the new resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccountingPeriodCreate"
        required: true
      responses:
        "201":
          description: "AccountingPeriod created successfully."
          headers:
            Location:
              description: "The URI of the newly created resource."
              schema:
                type: "string"
                example: "/accounting-periods/PR-1234567"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountingPeriod"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "409":
          $ref: "#/components/responses/ConflictError"
  /accounting-periods/{accountingPeriodKey}:
    get:
      tags:
      - "AccountingPeriod"
      summary: "Retrieve a specific AccountingPeriod record."
      operationId: "getAccountingPeriodById"
      responses:
        "200":
          description: "The requested AccountingPeriod record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountingPeriod"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    put:
      tags:
      - "AccountingPeriod"
      summary: "Replace a AccountingPeriod record."
      operationId: "replaceAccountingPeriod"
      requestBody:
        description: "Full record data to replace the existing resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccountingPeriod"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the update..."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountingPeriod"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    delete:
      tags:
      - "AccountingPeriod"
      summary: "Delete a AccountingPeriod Record"
      description: "Marks the AccountingPeriod record as inactive o..."
      operationId: "deleteAccountingPeriodRecord"
      responses:
        "204":
          description: "Record successfully deleted (or deactivated)."
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    patch:
      tags:
      - "AccountingPeriod"
      summary: "Partially update a AccountingPeriod record."
      operationId: "updateAccountingPeriod"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccountingPeriodUpdate"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the update..."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountingPeriod"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    parameters:
    - name: "accountingPeriodKey"
      in: "path"
      description: "The unique identifier for the specific AccountingPeriod."
      required: true
      schema:
        type: "string"
        example: "PR-1234567"
  /accounting-periods/{accountingPeriodKey}/identifiers:
    get:
      tags:
      - "Identifier"
      summary: "Retrieve a list of Identifier records scoped by..."
      operationId: "listIdentifiersByAccountingPeriodKey"
      parameters:
      - name: "limit"
        in: "query"
        description: "Maximum number of records to return."
        schema:
          maximum: 100
          minimum: 1
          type: "integer"
          default: 50
      - name: "cursor"
        in: "query"
        description: "starting point for next set of results"
        schema:
          type: "string"
      responses:
        "200":
          description: "A list of Identifier records."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Identifier"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"
    post:
      tags:
      - "Identifier"
      summary: "Create a new Identifier record."
      operationId: "createIdentifier"
      requestBody:
        description: "Identifier data to create the new resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IdentifierCreate"
        required: true
      responses:
        "201":
          description: "Identifier created successfully."
          headers:
            Location:
              description: "The URI of the newly created resource."
              schema:
                type: "string"
                example: "/part-search-results/PS-12345/bill-of-materials/BOM-001"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identifier"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "409":
          $ref: "#/components/responses/ConflictError"
    parameters:
    - name: "accountingPeriodKey"
      in: "path"
      description: "The unique identifier for the parent resource."
      required: true
      schema:
        type: "string"
  /accounting-periods/{accountingPeriodKey}/identifiers/{identifierKey}:
    get:
      tags:
      - "Identifier"
      summary: "Retrieve a specific Identifier record."
      operationId: "getIdentifierById"
      responses:
        "200":
          description: "The requested Identifier record."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identifier"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    put:
      tags:
      - "Identifier"
      summary: "Replace a Identifier record."
      operationId: "replaceIdentifier"
      requestBody:
        description: "Full record data to replace the existing resource."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Identifier"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the update..."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identifier"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    delete:
      tags:
      - "Identifier"
      summary: "Delete a Identifier Record"
      description: "Marks the Identifier record as inactive or remo..."
      operationId: "deleteIdentifierRecord"
      responses:
        "204":
          description: "Record successfully deleted (or deactivated)."
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    patch:
      tags:
      - "Identifier"
      summary: "Partially update a Identifier record."
      operationId: "updateIdentifier"
      requestBody:
        description: "Included Fields to be updated will be modified."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IdentifierUpdate"
        required: true
      responses:
        "200":
          description: "Record updated successfully. Returns the update..."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identifier"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
    parameters:
    - name: "accountingPeriodKey"
      in: "path"
      description: "The unique identifier for the parent resource."
      required: true
      schema:
        type: "string"
    - name: "identifierKey"
      in: "path"
      description: "The unique identifier for the specific Identifier."
      required: true
      schema:
        type: "string"
        example: "PR-1234567"
components:
  schemas:
    AccountingPeriod:
      type: "object"
      properties:
        identifiers:
          $ref: "#/components/schemas/Identifiers"
        period_desc:
          maxLength: 255
          type: "string"
          description: "Descriptive name for the accounting peri..."
        accounting_period_id:
          pattern: "^[0-9]{6}$"
          type: "string"
          description: "Business key for the accounting period (... Pat..."
        accounting_period_key:
          pattern: "^[0-9]{6}$"
          type: "string"
          description: "Business key for the accounting period (... Pat..."
        period_name:
          maxLength: 100
          type: "string"
          description: "Display name of the accounting period."
        accounting_period_status_type:
          $ref: "#/components/schemas/AccountingPeriodStatusTypes"
        fiscal_year:
          type: "integer"
          description: "The fiscal year this period belongs to."
          format: "int32"
      description: "Defines a fiscal period, including its unique i..."
    AccountingPeriodCreate:
      required:
      - "accounting_period_key"
      type: "object"
      description: "AccountingPeriod Create for Post"
      allOf:
      - $ref: "#/components/schemas/AccountingPeriod"
    AccountingPeriodStatusTypes:
      type: "string"
      description: "types of accounting period status."
      enum:
      - "OPEN"
      - "ADJUSTMENT"
      - "CLOSED"
      - "FUTURE"
      - "PENDING_CLOSURE"
      - "LOCKED"
      - "OTHER"
    AccountingPeriodUpdate:
      type: "object"
      properties:
        period_desc:
          maxLength: 255
          type: "string"
          description: "Descriptive name for the accounting peri..."
        fiscal_year:
          type: "integer"
          description: "The fiscal year this period belongs to."
          format: "int32"
        identifiers:
          $ref: "#/components/schemas/Identifiers"
        accounting_period_status_type:
          $ref: "#/components/schemas/AccountingPeriodStatusTypes"
        period_name:
          maxLength: 100
          type: "string"
          description: "Display name of the accounting period."
      description: "AccountingPeriod Update for Patch and Put"
    Codes:
      type: "array"
      items:
        type: "string"
    ErrorDetail:
      required:
      - "code"
      - "message"
      - "timestamp"
      type: "object"
      properties:
        code:
          type: "string"
          description: "A unique, system-defined error code (e.g., 'AUT..."
          example: "NOT_FOUND_PR"
        message:
          type: "string"
          description: "A human-readable summary providing specific det..."
          example: "Personnel Record with ID PR-1234567 was not found."
        details:
          type: "array"
          description: "Optional array of specific field-level validati..."
          items:
            type: "object"
            properties:
              field:
                type: "string"
                description: "The specific field that failed validation (e.g., 'firstName')."
                example: "payrollId"
              issue:
                type: "string"
                description: "The validation message for the field (e.g., 'must be\
                  \ numeric')."
                example: "must be unique"
        timestamp:
          type: "string"
          description: "The time the error occurred, in ISO 8601 format."
          format: "date-time"
          example: "2025-11-10T10:30:00Z"
      description: "Standard format for all API error responses."
    Identifier:
      type: "object"
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+..."
        identifier_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Business key for the identifier Pattern: ^[a-zA..."
        context:
          type: "string"
          description: "Context or domain of the identifier"
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
        system_codes:
          $ref: "#/components/schemas/Codes"
      description: "External system identifier"
    IdentifierCreate:
      required:
      - "identifier_key"
      type: "object"
      description: "Identifier Create for Post"
      allOf:
      - $ref: "#/components/schemas/Identifier"
    IdentifierUpdate:
      type: "object"
      properties:
        system_codes:
          $ref: "#/components/schemas/Codes"
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
        context:
          type: "string"
          description: "Context or domain of the identifier"
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
      description: "Identifier Update for Patch and Put"
    Identifiers:
      type: "array"
      items:
        $ref: "#/components/schemas/Identifier"
  responses:
    NotFoundError:
      description: "The requested resource was not found."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
    BadRequestError:
      description: "The request was malformed, failed validation, o..."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
    UnauthorizedError:
      description: "Authentication failed. The access token is miss..."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
    ForbiddenError:
      description: "The authenticated user does not have the necess..."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
    ConflictError:
      description: "The request could not be completed because it c..."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
    ServerError:
      description: "An unexpected error occurred on the server whil..."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
