---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    AccountingPeriod:
      type: "object"
      properties:
        identifiers:
          $ref: "#/components/schemas/Identifiers"
          exampleSetFlag: false
        period_desc:
          maxLength: 255
          type: "string"
          description: "Descriptive name for the accounting peri..."
          exampleSetFlag: false
        accounting_period_id:
          pattern: "^[0-9]{6}$"
          type: "string"
          description: "Business key for the accounting period (... Pattern: ^[0-9]{6}$\
            \ (Must be in YYYYMM format)"
          exampleSetFlag: false
        accounting_period_key:
          pattern: "^[0-9]{6}$"
          type: "string"
          description: "Business key for the accounting period (... Pattern: ^[0-9]{6}$\
            \ (Must be in YYYYMM format)"
          exampleSetFlag: false
        period_name:
          maxLength: 100
          type: "string"
          description: "Display name of the accounting period."
          exampleSetFlag: false
        accounting_period_status_type:
          $ref: "#/components/schemas/AccountingPeriodStatusTypes"
          exampleSetFlag: false
        fiscal_year:
          type: "integer"
          description: "The fiscal year this period belongs to."
          format: "int32"
          exampleSetFlag: false
      description: "Defines a fiscal period, including its unique identifiers, start\
        \ and end dates, and current status."
      exampleSetFlag: false
    AccountingPeriodCreate:
      required:
      - "accounting_period_key"
      type: "object"
      description: "AccountingPeriod Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/AccountingPeriod"
        exampleSetFlag: false
    AccountingPeriodStatusTypes:
      type: "string"
      description: "types of accounting period status."
      exampleSetFlag: false
      enum:
      - "OPEN"
      - "ADJUSTMENT"
      - "CLOSED"
      - "FUTURE"
      - "PENDING_CLOSURE"
      - "LOCKED"
      - "OTHER"
    AccountingPeriodUpdate:
      type: "object"
      properties:
        period_desc:
          maxLength: 255
          type: "string"
          description: "Descriptive name for the accounting peri..."
          exampleSetFlag: false
        fiscal_year:
          type: "integer"
          description: "The fiscal year this period belongs to."
          format: "int32"
          exampleSetFlag: false
        identifiers:
          $ref: "#/components/schemas/Identifiers"
          exampleSetFlag: false
        accounting_period_status_type:
          $ref: "#/components/schemas/AccountingPeriodStatusTypes"
          exampleSetFlag: false
        period_name:
          maxLength: 100
          type: "string"
          description: "Display name of the accounting period."
          exampleSetFlag: false
      description: "AccountingPeriod Update for Patch and Put"
      exampleSetFlag: false
    Codes:
      type: "array"
      exampleSetFlag: false
      items:
        type: "string"
        exampleSetFlag: false
    Identifier:
      type: "object"
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        identifier_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Business key for the identifier Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          exampleSetFlag: false
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
      description: "External system identifier"
      exampleSetFlag: false
    IdentifierCreate:
      required:
      - "identifier_key"
      type: "object"
      description: "Identifier Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/Identifier"
        exampleSetFlag: false
    IdentifierUpdate:
      type: "object"
      properties:
        system_codes:
          $ref: "#/components/schemas/Codes"
          exampleSetFlag: false
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        context:
          type: "string"
          description: "Context or domain of the identifier"
          exampleSetFlag: false
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
          exampleSetFlag: false
      description: "Identifier Update for Patch and Put"
      exampleSetFlag: false
    Identifiers:
      type: "array"
      exampleSetFlag: false
      items:
        $ref: "#/components/schemas/Identifier"
        exampleSetFlag: false
