---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    AccountingPeriod:
      type: "object"
      properties:
        identifiers:
          $ref: "#/components/schemas/Identifiers"
        period_desc:
          maxLength: 255
          type: "string"
          description: "Descriptive name for the accounting peri..."
        accounting_period_id:
          pattern: "^[0-9]{6}$"
          type: "string"
          description: "Business key for the accounting period (... Pattern: ^[0-9]{6}$\
            \ (Must be in YYYYMM format)"
        accounting_period_key:
          pattern: "^[0-9]{6}$"
          type: "string"
          description: "Business key for the accounting period (... Pattern: ^[0-9]{6}$\
            \ (Must be in YYYYMM format)"
        period_name:
          maxLength: 100
          type: "string"
          description: "Display name of the accounting period."
        accounting_period_status_type:
          $ref: "#/components/schemas/AccountingPeriodStatusTypes"
        fiscal_year:
          type: "integer"
          description: "The fiscal year this period belongs to."
          format: "int32"
      description: "Defines a fiscal period, including its unique identifiers, start\
        \ and end dates, and current status."
    AccountingPeriodStatusTypes:
      type: "string"
      description: "types of accounting period status."
      enum:
      - "OPEN"
      - "ADJUSTMENT"
      - "CLOSED"
      - "FUTURE"
      - "PENDING_CLOSURE"
      - "LOCKED"
      - "OTHER"
    Codes:
      type: "array"
      items:
        type: "string"
    Identifier:
      type: "object"
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
        identifier_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: "string"
          description: "Business key for the identifier Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
        context:
          type: "string"
          description: "Context or domain of the identifier"
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
        system_codes:
          $ref: "#/components/schemas/Codes"
      description: "External system identifier"
    Identifiers:
      type: "array"
      items:
        $ref: "#/components/schemas/Identifier"
