---
openapi: "3.0.1"
info:
  title: "Domain API Specification"
  description: "Automotive Retail Ontology."
  version: "1.0.0"
paths: {}
components:
  schemas:
    BudgetVarianceLineItem:
      type: "object"
      properties:
        line_item_id:
          type: "string"
          description: "The unique ID for the report line item."
          exampleSetFlag: false
        financial_category:
          $ref: "#/components/schemas/FinancialCategoryTypes"
          exampleSetFlag: false
      description: "A line item within a Budget Variance Report, comparing budgeted\
        \ versus actual amounts for a specific account/category."
      exampleSetFlag: false
    BudgetVarianceLineItemCreate:
      required:
      - "budget_variance_line_item_key"
      type: "object"
      description: "BudgetVarianceLineItem Create for Post"
      exampleSetFlag: false
      allOf:
      - $ref: "#/components/schemas/BudgetVarianceLineItem"
        exampleSetFlag: false
    BudgetVarianceLineItemUpdate:
      type: "object"
      properties:
        financial_category:
          $ref: "#/components/schemas/FinancialCategoryTypes"
          exampleSetFlag: false
      description: "BudgetVarianceLineItem Update for Patch and Put"
      exampleSetFlag: false
    FinancialCategoryTypes:
      type: "string"
      description: "Financial Category Types"
      exampleSetFlag: false
      enum:
      - "CAPEX"
      - "OPEX"
      - "HARDWARE"
      - "SOFTWARE"
      - "MAINTENANCE"
      - "TRAVEL"
      - "TRAINING"
      - "UTILITIES"
      - "RENT"
      - "SALARY"
      - "REVENUE"
      - "TAX"
      - "OTHER"
